Repository xdslproject/xdsl, pull requests merged in 2022-09, with the labels that each got.

#173 [MLIR]: Conversion with ctx and update README
  README.md
  src/xdsl/mlir_converter.py
Labels: documentation, compiler

#174 Add float support to Dense attribute
  src/xdsl/dialects/builtin.py
  tests/filecheck/builtin_types.xdsl
Labels: compiler

#178 Add a parser for MLIR programs
  src/xdsl/dialects/builtin.py
  src/xdsl/parser.py
  src/xdsl/printer.py
  src/xdsl/xdsl_opt_main.py
  tests/filecheck/lit.cfg
  tests/filecheck/mlir-conversion/builtin_attrs.mlir
Labels: compiler

#186 compiler: refactor repo hierarchy
  MANIFEST.in
  README.md
  pyproject.toml
  setup.cfg
  tests/filecheck/lit.cfg
  xdsl/__init__.py
  xdsl/_version.py
  xdsl/diagnostic.py
  xdsl/dialects/__init__.py
  xdsl/dialects/affine.py
  xdsl/dialects/arith.py
  xdsl/dialects/builtin.py
  xdsl/dialects/cf.py
  xdsl/dialects/cmath.py
  xdsl/dialects/func.py
  xdsl/dialects/irdl.py
  xdsl/dialects/llvm.py
  xdsl/dialects/memref.py
  xdsl/dialects/scf.py
  xdsl/ir.py
  xdsl/irdl.py
  xdsl/irdl_mlir_printer.py
  xdsl/mlir_converter.py
  xdsl/parser.py
  xdsl/pattern_rewriter.py
  xdsl/printer.py
  xdsl/py.typed
  xdsl/rewriter.py
  xdsl/tools/xdsl-opt
  xdsl/util.py
  xdsl/xdsl_opt_main.py
Labels: compiler

#180 docs: Update README.md
  README.md
Labels: documentation
