Repository xdslproject/xdsl, pull requests merged in 2022-11, with the labels that each got.

#213 examples: Add notebooks to CI, add python3.11 in testing
  .github/workflows/ci-core.yml
  .github/workflows/ci-notebooks.yml
  docs/irdl.ipynb
  docs/tutorial.ipynb
  xdsl/dialects/cmath.py
  xdsl/dialects/memref.py
  xdsl/irdl.py
  xdsl/printer.py
Labels: CI

#221 Compiler: fix mlir module loading
  xdsl/__init__.py
Labels: compiler

#222 [func] fixes to return and call ops
  xdsl/dialects/func.py
Labels: bug

#207 xdsl: introduce {IRNode, BinaryOperation} baseclass
  tests/attribute_builder_test.py
  tests/attribute_definition_test.py
  tests/operation_builder_test.py
  tests/printer_test.py
  xdsl/dialects/arith.py
  xdsl/dialects/builtin.py
  xdsl/ir.py
  xdsl/irdl.py
  xdsl/parser.py
  xdsl/printer.py
  xdsl/utils/__init__.py
  xdsl/utils/diagnostic.py
  xdsl/utils/exceptions.py
  xdsl/xdsl_opt_main.py
Labels: compiler

#181 docs: Add website link and project description
  README.md
Labels: documentation

#224 docs: Add CI/pip badges
  README.md
Labels: documentation

#211 compiler: Towards better imports and other minor corrections
  tests/is_satisfying_hint_test.py
  tests/mlir_printer_test.py
  xdsl/dialects/arith.py
  xdsl/dialects/builtin.py
  xdsl/dialects/cf.py
  xdsl/dialects/cmath.py
  xdsl/dialects/func.py
  xdsl/dialects/irdl.py
  xdsl/dialects/llvm.py
  xdsl/dialects/memref.py
  xdsl/dialects/scf.py
  xdsl/irdl.py
  xdsl/irdl_mlir_printer.py
  xdsl/rewriter.py
  xdsl/utils/hints.py
  xdsl/xdsl_opt_main.py
Labels: compiler

#225 xdsl: adding f16, f64 in arith_ops.xdsl
  tests/attribute_builder_test.py
  tests/filecheck/arith_ops.xdsl
  tests/is_satisfying_hint_test.py
  tests/mlir_converter_test.py
  tests/pattern_rewriter_test.py
  tests/rewriter_test.py
  tests/use_test.py
  xdsl/dialects/arith.py
Labels: testing

#223 install: Add py.typed in the package
  MANIFEST.in
  setup.py
Labels: install

#239 tests: Add code coverage to the repository
  .coveragerc
  .github/workflows/ci-core.yml
  README.md
  codecov.yml
  requirements-optional.txt
Labels: CI

#237 CI: Rename testing job
  .github/workflows/ci-core.yml
Labels: CI

#242 misc: Add Output folders to gitignore
  .gitignore
Labels: minor

#229 xdsl: Add float Constant/ rename `int` custom constructors
  tests/pattern_rewriter_test.py
  tests/printer_test.py
  tests/rewriter_test.py
  xdsl/dialects/arith.py
Labels: compiler, API

#235 tests: Add tests related to func.py
  tests/func_test.py
Labels: testing

#243 CI: Add MLIR-based CI
  .github/workflows/ci-mlir.yml
Labels: CI
