Repository xdslproject/xdsl, pull requests merged in 2022-08, with the labels that each got.

#163 Fix func.func printing in test
  tests/filecheck/mlir-conversion/llvm_test.xdsl
Labels: testing

#164 workflows: Add release drafter workflow
  .github/workflows/release-notes.yml
Labels: documentation

#165 Renamed master to main in workflow
  .github/workflows/release-notes.yml
Labels: CI

#162 Rename module to builtin.module
  src/xdsl/dialects/builtin.py
  tests/filecheck/affine_ops.xdsl
  tests/filecheck/arith_invalid.xdsl
  tests/filecheck/arith_ops.xdsl
  tests/filecheck/cf_ops.xdsl
  tests/filecheck/cmath.xdsl
  tests/filecheck/cmath_ops.xdsl
  tests/filecheck/func_ops.xdsl
  tests/filecheck/irdl-printer/any_and_base_type.xdsl
  tests/filecheck/irdl-printer/cmath_program.xdsl
  tests/filecheck/irdl_any_and_base_type.xdsl
  tests/filecheck/memref_ops.xdsl
  tests/filecheck/mlir-conversion/llvm_test.xdsl
  tests/filecheck/mlir-conversion/ops.xdsl
  tests/filecheck/parser-printer/builtin_types.xdsl
  tests/filecheck/parser-printer/escaped_characters.xdsl
  tests/filecheck/parser-printer/float_parsing.xdsl
  tests/filecheck/parser-printer/region_name_clash.xdsl
  tests/filecheck/scf_ops.xdsl
  tests/mlir_converter_test.py
  tests/pattern_rewriter_test.py
  tests/printer_test.py
  tests/rewriter_test.py
  tests/use_test.py
Labels: compiler

#136 Printer: add support to print types in MLIR style
  CHANGELOG.md
  src/xdsl/dialects/builtin.py
  src/xdsl/dialects/cmath.py
  src/xdsl/dialects/llvm.py
  src/xdsl/dialects/memref.py
  src/xdsl/ir.py
  src/xdsl/printer.py
  src/xdsl/xdsl_opt_main.py
  tests/filecheck/mlir-conversion/llvm_test.xdsl
  tests/filecheck/mlir-conversion/ops.xdsl
  tests/filecheck/parser-printer/llvm_mlir_printer.xdsl
  tests/mlir_printer_test.py
Labels: compiler

#167 Add custom format for attributes
  src/xdsl/dialects/llvm.py
  src/xdsl/ir.py
  src/xdsl/parser.py
  src/xdsl/printer.py
  tests/mlir_printer_test.py
  tests/printer_test.py
Labels: compiler

#168 Make sym_visibility an optional attribute in func.func
  src/xdsl/dialects/func.py
Labels: compiler
