Repository xdslproject/xdsl, pull requests merged in 2022-12, with the labels that each got.

#240 tests: change to test_ prefix
  tests/test_attribute_builder.py
  tests/test_attribute_definition.py
  tests/test_is_satisfying_hint.py
  tests/test_mlir_converter.py
  tests/test_mlir_printer.py
  tests/test_operation_builder.py
  tests/test_operation_definition.py
  tests/test_parser.py
  tests/test_parser_error.py
  tests/test_pattern_rewriter.py
  tests/test_printer.py
  tests/test_rewriter.py
  tests/test_use.py
Labels: testing, minor

#252 API: Update type hints on constructors
  xdsl/dialects/builtin.py
  xdsl/dialects/scf.py
Labels: API, minor

#244 install: Update PyPI description
  setup.py
Labels: install

#230 compiler: Add verifiers to func.func and func.return
  tests/filecheck/affine_ops.xdsl
  tests/filecheck/arith_ops.xdsl
  tests/filecheck/builtin_attrs.xdsl
  tests/filecheck/cmath_ops.xdsl
  tests/filecheck/mlir-conversion/builtin_attrs.mlir
  xdsl/dialects/func.py
Labels: bug

#261 CI: Update Ninja installation
  .github/workflows/ci-mlir.yml
Labels: CI

#265 Fix types of Dialect fields
  xdsl/ir.py
Labels: compiler, API

#256 CI: Get coverage of filecheck tests
  .coveragerc
  .github/workflows/ci-core.yml
  .github/workflows/ci-mlir.yml
  requirements.txt
  tests/filecheck/lit.cfg
  xdsl/xdsl_opt_main.py
Labels: CI

#268 CI: Generate proper coverage for filecheck tests
  .github/workflows/ci-mlir.yml
  tests/filecheck/lit.cfg
  xdsl/xdsl_opt_main.py
Labels: CI

#254 tests: Initialize test covering
  tests/test_ir.py
  tests/test_mlctx.py
  tests/test_operation_builder.py
  tests/test_pattern_rewriter.py
  tests/test_ssavalue.py
Labels: testing

#267 compiler: Fix attribute builder
  tests/test_attribute_builder.py
  xdsl/irdl.py
  xdsl/utils/exceptions.py
  xdsl/utils/hints.py
Labels: xdsl

#260 tests: Enhance testing for memref dialect
  tests/dialects/test_memref.py
  xdsl/dialects/memref.py
Labels: testing, minor

#226 compiler: Fix tensor_from_list method of DenseIntOrFPElementsAttr to properly handle f32 input values
  tests/dialects/test_builtin.py
  xdsl/dialects/builtin.py
Labels: compiler
