Repository xdslproject/xdsl, pull requests merged in 2023-01, with the labels that each got.

#281 tests: Add some IRDL test
  tests/test_irdl.py
  xdsl/irdl.py
Labels: testing

#288 tests: Add more ir tests
  tests/dialects/test_irdl.py
  tests/test_ir.py
  tests/test_operation_builder.py
  xdsl/ir.py
  xdsl/rewriter.py
Labels: testing

#287 tests: Add tests for cf
  tests/dialects/test_cf.py
Labels: testing

#296 Readme update summary
  README.md
Labels: documentation, hackathon

#290 tests: Add testing for xdsl_opt_main
  tests/xdsl_opt/README.md
  tests/xdsl_opt/empty_program.xdsl
  tests/xdsl_opt/test_xdsl_opt.py
  xdsl/xdsl_opt_main.py
Labels: testing

#297 Add a link to our interactive notebooks
  README.md
Labels: documentation, hackathon

#199 mlir printing and parsing fix
  tests/filecheck/mlir-conversion/builtin_attrs.mlir
  tests/filecheck/mlir-conversion/with-bindings/symbol_tests.xdsl
  xdsl/parser.py
  xdsl/printer.py
Labels: compiler

#298 Add %pip install only in JupyterLite context.
  .github/workflows/jupyterlite.yml
  docs/irdl.ipynb
  docs/tutorial.ipynb
Labels: documentation

#299 tests: Add tests for affine
  tests/dialects/test_affine.py
Labels: testing

#301 tests: Add further testing of xdsl_opt_main
  .gitignore
  tests/xdsl_opt/empty_program.wrong
  tests/xdsl_opt/not_module.mlir
  tests/xdsl_opt/not_module.xdsl
  tests/xdsl_opt/test_xdsl_opt.py
Labels: testing

#289 tests: Add more coverage for dialects/arith
  tests/dialects/test_arith.py
  xdsl/dialects/arith.py
  xdsl/dialects/cmath.py
Labels: testing

#258 xdsl: DictionaryAttr for the builtin dialect
  tests/filecheck/builtin_attrs.xdsl
  tests/filecheck/mlir-conversion/builtin_attrs.mlir
  tests/test_parser.py
  tests/test_printer.py
  xdsl/dialects/builtin.py
  xdsl/parser.py
  xdsl/printer.py
Labels: xdsl

#303 CI: Add Python 3.11 to the CI
  .github/workflows/ci-core.yml
  .github/workflows/ci-mlir.yml
  tests/test_attribute_definition.py
Labels: CI, hackathon

#306 CI: Fix Codecov token issue
  .github/workflows/ci-mlir.yml
Labels: CI

#300 xDSL/Vector: Add support for broadcast, fma and maskedload op
  tests/dialects/test_vector.py
  tests/filecheck/dialects/vector/vector_broadcast_type_matching.xdsl
  tests/filecheck/dialects/vector/vector_fma_res_acc_shape_matching.xdsl
  tests/filecheck/dialects/vector/vector_fma_res_acc_type_matching.xdsl
  tests/filecheck/dialects/vector/vector_fma_res_lhs_shape_matching.xdsl
  tests/filecheck/dialects/vector/vector_fma_res_lhs_type_matching.xdsl
  tests/filecheck/dialects/vector/vector_fma_res_rhs_shape_matching.xdsl
  tests/filecheck/dialects/vector/vector_fma_res_rhs_type_matching.xdsl
  tests/filecheck/dialects/vector/vector_maskedload_indexing.xdsl
  tests/filecheck/dialects/vector/vector_maskedload_mask_rank_check.xdsl
  tests/filecheck/dialects/vector/vector_maskedload_mask_type_checking.xdsl
  tests/filecheck/dialects/vector/vector_maskedload_memref_passthrough_type_matching.xdsl
  tests/filecheck/dialects/vector/vector_maskedload_memref_res_type_matching.xdsl
  tests/filecheck/dialects/vector/vector_maskedload_res_rank_check.xdsl
  tests/filecheck/dialects/vector/vector_ops.xdsl
  tests/filecheck/dialects/vector/vector_ops_mlir_conversion.xdsl
  xdsl/dialects/vector.py
Labels: dialects

#313 tests: Add more func tests
  tests/dialects/test_func.py
Labels: testing

#312 misc: place all badges in README in one line
  README.md
Labels: documentation, hackathon

#302 doc: Link directly to interactive notebooks with less UI clutter.
  README.md
Labels: documentation, hackathon

#316 readme: udpate
  README.md
Labels: documentation

#320 tests: Add test for xdsl_opt passes
  tests/xdsl_opt/constant_program.xdsl
  tests/xdsl_opt/test_xdsl_opt.py
  xdsl/xdsl_opt_main.py
Labels: testing

#317 xDSL: Fix several pyright issues
  xdsl/_version.py
  xdsl/dialects/builtin.py
  xdsl/ir.py
  xdsl/irdl_mlir_printer.py
  xdsl/pattern_rewriter.py
  xdsl/rewriter.py
Labels: xdsl, hackathon

#322 frontend: Add initial skeleton
  tests/filecheck/frontend/programs/invalid.py
  tests/filecheck/frontend/programs/programs.py
  tests/filecheck/lit.cfg
  xdsl/frontend/__init__.py
  xdsl/frontend/context.py
  xdsl/frontend/program.py
Labels: hackathon, frontend

#325 xDSL: Add structural equivalence comparison for IRNode
  tests/test_ir.py
  xdsl/ir.py
Labels: xdsl

#315 install: add ipykernel as an optional requirement
  README.md
  requirements-optional.txt
Labels: install, hackathon

#336 frontend: checks for Python code structure
  tests/filecheck/frontend/programs/invalid.py
  xdsl/frontend/block.py
  xdsl/frontend/code_generation.py
  xdsl/frontend/context.py
  xdsl/frontend/python_code_check.py
Labels: hackathon, frontend

#340 docs: Minor overall tweaks
  setup.py
  tests/dialects/test_affine.py
  tests/dialects/test_arith.py
  tests/dialects/test_builtin.py
  tests/dialects/test_func.py
  tests/dialects/test_vector.py
  xdsl/parser.py
  xdsl/rewriter.py
  xdsl/xdsl_opt_main.py
Labels: minor

#339 xdsl: fix some type issues with DictionaryAttr printing and parsing
  tests/test_parser.py
  xdsl/dialects/builtin.py
  xdsl/parser.py
  xdsl/printer.py
Labels: bug, xdsl

#337 frontend: Add constants
  tests/filecheck/frontend/programs/invalid.py
  tests/test_frontend_python_code_check.py
  tests/test_frontend_type_conversion.py
  xdsl/frontend/const.py
  xdsl/frontend/python_code_check.py
Labels: hackathon, frontend

#344 dialects: Improve MemRefType.from_type_list() constructor
  tests/dialects/test_memref.py
  tests/dialects/test_vector.py
  xdsl/dialects/memref.py
Labels: dialects, API

#212 xdsl: parse custom memref format
  tests/filecheck/mlir-conversion/builtin_attrs.mlir
  tests/test_mlir_printer.py
  xdsl/dialects/memref.py
  xdsl/parser.py
  xdsl/printer.py
Labels: xdsl

#341 CI: Refresh drafter
  .github/release-drafter.yml
Labels: CI

#345 tests: Minor additions on testing frontend and attributes
  tests/test_attribute_definition.py
  tests/test_frontend_op_inserter.py
  tests/test_printer.py
Labels: testing

#342 xdsl: parse dictionary as non-optional
  tests/test_parser.py
  tests/test_parser_error.py
  xdsl/dialects/builtin.py
  xdsl/parser.py
Labels: xdsl

#262 New Parser
  tests/filecheck/parser-printer/float_parsing.xdsl
  tests/test_attribute_builder.py
  tests/test_attribute_definition.py
  tests/test_ir.py
  tests/test_irdl.py
  tests/test_mlir_converter.py
  tests/test_mlir_printer.py
  tests/test_parser.py
  tests/test_parser_error.py
  tests/test_pattern_rewriter.py
  tests/test_printer.py
  tests/test_ssa_value.py
  tests/xdsl_opt/test_xdsl_opt.py
  xdsl/dialects/builtin.py
  xdsl/dialects/irdl.py
  xdsl/dialects/llvm.py
  xdsl/ir.py
  xdsl/parser.py
  xdsl/printer.py
  xdsl/tools/xdsl-opt
  xdsl/utils/exceptions.py
  xdsl/xdsl_opt_main.py
Labels: xdsl, hackathon

#354 misc: add Toy chapter 1 python code, examples and notebook
  .coveragerc
  .github/workflows/ci-mlir.yml
  .github/workflows/ci-notebooks.yml
  docs/Toy/Toy_Ch1.ipynb
  docs/Toy/examples/ast.toy
  docs/Toy/examples/codegen.toy
  docs/Toy/examples/empty.toy
  docs/Toy/examples/scalar.toy
  docs/Toy/toy/__init__.py
  docs/Toy/toy/lexer.py
  docs/Toy/toy/location.py
  docs/Toy/toy/parser.py
  docs/Toy/toy/tests/__init__.py
  docs/Toy/toy/tests/test_toy.py
  docs/Toy/toy/toy_ast.py
Labels: documentation

#374 misc: replace triple single quotes by triple double quotes
  docs/Toy/Toy_Ch1.ipynb
  tests/test_printer.py
Labels: documentation

#378 misc: add flattened_values to LiteralExprAST
  docs/Toy/toy/toy_ast.py
Labels: documentation

#364 tests: Add print checker in conftest
  tests/__init__.py
  tests/conftest.py
  tests/test_pattern_rewriter.py
  tests/test_printer.py
  tests/test_pyrdl.py
  tests/test_rewriter.py
  xdsl/dialects/arith.py
  xdsl/dialects/llvm.py
  xdsl/dialects/scf.py
  xdsl/frontend/const.py
  xdsl/frontend/context.py
  xdsl/frontend/op_inserter.py
  xdsl/frontend/program.py
Labels: testing

#380 misc: add toy dialect
  docs/Toy/toy/dialect.py
Labels: documentation

#382 docs: Fix several PyLance issues
  tests/test_frontend_op_inserter.py
  tests/test_rewriter.py
  tests/test_ssa_value.py
  tests/test_ssavalue.py
  xdsl/dialects/builtin.py
  xdsl/ir.py
  xdsl/parser.py
  xdsl/pattern_rewriter.py
  xdsl/rewriter.py
  xdsl/utils/diagnostic.py
  xdsl/utils/exceptions.py
Labels: minor
