Repository xdslproject/xdsl, pull requests merged in 2023-06, with the labels that each got.

#1036 core: check correctness operation signatures
  docs/Toy/examples/tests/optimise_toy.mlir
  tests/filecheck/dialects/gpu/alloc_wrong_dynamic_size.mlir
  tests/filecheck/dialects/gpu/ops.mlir
  tests/filecheck/dialects/llvm/pointers.mlir
  tests/filecheck/dialects/riscv/riscv_assembly_emission.mlir
  tests/filecheck/dialects/riscv/riscv_ops.mlir
  tests/filecheck/dialects/riscv/riscv_register_allocation.mlir
  tests/filecheck/dialects/scf/for_args_number.mlir
  tests/filecheck/dialects/scf/for_args_types.mlir
  tests/filecheck/dialects/scf/for_body_args_number.mlir
  tests/filecheck/dialects/scf/for_body_args_types.mlir
  tests/filecheck/dialects/scf/for_yield.mlir
  tests/filecheck/dialects/scf/for_yield_number.mlir
  tests/filecheck/dialects/scf/for_yield_types.mlir
  tests/filecheck/dialects/scf/parallel_bounds.mlir
  tests/filecheck/dialects/scf/reduce_arg_type_missmatch.mlir
  tests/filecheck/dialects/stencil/hdiff_gpu.mlir
  tests/filecheck/dialects/stencil/stencil_ops.mlir
  tests/filecheck/dialects/vector/vector_maskedload_memref_passthrough_type_matching.mlir
  tests/filecheck/dialects/vector/vector_maskedload_memref_res_type_matching.mlir
  tests/filecheck/dialects/vector/vector_maskedstore_memref_storevec_type_matching.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/gpu/ops.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/stencil/hdiff.mlir
  tests/filecheck/parser-printer/operation_signature.mlir
  xdsl/parser.py
Labels: core

#995 dialects: riscv: Add basic register allocator strategy
  docs/Toy/toy/tests/test_regalloc.py
  tests/filecheck/dialects/riscv/riscv_register_allocation_block_naive.mlir
  tests/filecheck/dialects/riscv/riscv_register_allocation_jregs.mlir
  xdsl/transforms/riscv_register_allocation.py
Labels: dialects

#929 dialects: riscv-func add initial function call lowering
  tests/filecheck/dialects/riscv_func/lower_riscv_func.mlir
  xdsl/dialects/riscv_func.py
  xdsl/transforms/lower_riscv_func.py
Labels: dialects

#1052 dialects: (memref) Make alignment for memref.alloc optional
  xdsl/dialects/memref.py
Labels: dialects

#1039 core: Allow parsing graph regions
  tests/filecheck/parser-printer/graph_region.mlir
  tests/filecheck/parser-printer/operation_signature.mlir
  tests/test_printer.py
  xdsl/parser.py
Labels: core

#1054 transformations: Split ApplyOp and AccessOp shape inference patterns.
  tests/filecheck/transforms/stencil-shape-inference.mlir
  xdsl/transforms/experimental/StencilShapeInference.py
Labels: transformations

#1042 dialects: (builtin) add range verifier for `IntegerAttr`
  tests/filecheck/dialects/scf/for_body_args_number.mlir
  tests/filecheck/dialects/scf/for_body_args_number_much.mlir
  tests/filecheck/dialects/scf/for_body_args_types.mlir
  tests/filecheck/dialects/scf/for_yield.mlir
  tests/filecheck/dialects/scf/for_yield_number.mlir
  tests/filecheck/dialects/scf/for_yield_types.mlir
  tests/test_attribute_definition.py
  xdsl/dialects/builtin.py
Labels: dialects

#1017 core: use with blocks for implicit building
  docs/Toy/toy/tests/test_ir_gen.py
  tests/interpreters/test_pdl_interpreter.py
  xdsl/builder.py
Labels: core

#1051 dialects: FIR dialect
  xdsl/dialects/experimental/fir.py
  xdsl/xdsl_opt_main.py
Labels: dialects

#1062 core: allow None for optional region
  tests/test_operation_builder.py
  xdsl/irdl.py
Labels: core

#1064 core: separate out decorator for anonymous rewrite pattern
  tests/test_pattern_rewriter.py
  xdsl/interpreters/experimental/pdl.py
  xdsl/pattern_rewriter.py
Labels: core

#1050 core: better errors printing in operation
  docs/irdl.ipynb
  tests/dialects/test_func.py
  tests/dialects/test_stencil.py
  tests/dialects/test_vector.py
  tests/filecheck/parser-printer/verifier_error.mlir
  tests/test_builtin_traits.py
  tests/test_operation_definition.py
  tests/test_traits.py
  xdsl/ir.py
  xdsl/utils/diagnostic.py
Labels: core

#1061 dialects: (dmp) A bunch of fixes in the lowering
  xdsl/dialects/experimental/dmp.py
  xdsl/transforms/experimental/dmp/scatter_gather.py
  xdsl/transforms/experimental/dmp/stencil_global_to_local.py
  xdsl/transforms/lower_mpi.py
Labels: dialects

#1055 core: Add get_string_literal_value to Token
  tests/test_lexer.py
  xdsl/utils/lexer.py
Labels: core

#1056 core: (NFC) Move parsing of string attribute and literal to the lexer
  xdsl/dialects/builtin.py
  xdsl/dialects/llvm.py
  xdsl/dialects/pdl.py
  xdsl/parser.py
Labels: core

#1057 core: remove some legacy parser function
  xdsl/dialects/builtin.py
  xdsl/parser.py
Labels: core

#1058 core: (NFC) rewrite operation parser in lexer
  tests/filecheck/dialects/riscv/riscv_ops.mlir
  tests/filecheck/parser-printer/operation_signature.mlir
  tests/filecheck/parser-printer/value_tuple_wrong_number.mlir
  tests/test_parser_error.py
  xdsl/parser.py
Labels: core

#1060 transformations: Add a lowering test for counterintuitive stencil offsets.
  tests/filecheck/transforms/convert-stencil-to-ll-mlir.mlir
  xdsl/transforms/experimental/ConvertStencilToLLMLIR.py
Labels: transformations

#1070 docs: (toy) optional instead of error in parser
  docs/Toy/toy/frontend/parser.py
Labels: documentation

#1068 core: Move type parsing to lexer (NFC)
  xdsl/dialects/func.py
  xdsl/parser.py
Labels: core

#1069 core: move attribute parsing to lexer (NFC)
  tests/test_parser.py
  xdsl/parser.py
Labels: core

#1072 core: move identifier parsing to lexer
  xdsl/dialects/builtin.py
  xdsl/dialects/riscv.py
  xdsl/parser.py
Labels: core

#1025 tests: Fix waitall with empty sendbuf, add minor
  tests/dialects/test_mpi_lowering.py
  xdsl/dialects/mpi.py
Labels: testing

#1065 dialects: Add element_count to ShapedType and add ContainerType
  docs/Toy/toy/dialects/toy.py
  docs/Toy/toy/interpreter.py
  tests/dialects/test_builtin.py
  tests/dialects/test_vector.py
  xdsl/dialects/builtin.py
  xdsl/dialects/experimental/stencil.py
  xdsl/dialects/llvm.py
  xdsl/dialects/memref.py
  xdsl/printer.py
  xdsl/transforms/experimental/ConvertStencilToLLMLIR.py
Labels: dialects, xdsl

#1027 dialects: (riscv) add verifiers for riscv ops using immediate
  tests/dialects/test_riscv.py
  xdsl/dialects/riscv.py
Labels: dialects

#1074 core: Remove the tokenizer
  tests/test_attribute_definition.py
  tests/test_parser.py
  tests/test_printer.py
  tests/xdsl_opt/test_xdsl_opt.py
  xdsl/dialects/experimental/dmp.py
  xdsl/dialects/memref.py
  xdsl/parser.py
Labels: core

#1088 core: optimise attr clsdict calculation
  xdsl/irdl.py
Labels: core

#1094 bug: fix riscemu dependency crash
  xdsl/xdsl_opt_main.py
Labels: bug

#1096 misc: lint test_mpi_lowering.py
  pyproject.toml
  tests/dialects/test_mpi_lowering.py
Labels: CI, minor

#1099 tests: don't fail if can't run riscemu
  tests/filecheck/with-riscemu/lit.local.cfg
  tests/filecheck/with-riscemu/riscv_emulation.mlir
  tests/interpreters/test_riscv_emulator.py
Labels: testing

#1085 dialects: Add lowering pass to convert snitch-runtime to external func.funcs
  tests/filecheck/dialects/snitch_runtime/lower_snrt_to_func.mlir
  tests/filecheck/dialects/snitch_runtime/snitch_runtime_ops.mlir
  xdsl/dialects/snitch_runtime.py
  xdsl/transforms/lower_snitch_runtime.py
  xdsl/xdsl_opt_main.py
Labels: dialects

#1100 dialects: Port Stencil out of experimental
  tests/dialects/test_stencil.py
  xdsl/dialects/experimental/dmp.py
  xdsl/dialects/experimental/stencil.py
  xdsl/dialects/stencil.py
  xdsl/transforms/experimental/Apply1DMPIToStencil.py
  xdsl/transforms/experimental/ConvertStencilToLLMLIR.py
  xdsl/transforms/experimental/StencilShapeInference.py
  xdsl/transforms/experimental/dmp/stencil_global_to_local.py
  xdsl/xdsl_opt_main.py
Labels: dialects

#1102 dialects: Implement stencil.BufferOp
  tests/filecheck/dialects/stencil/invalid.mlir
  tests/filecheck/dialects/stencil/stencil_ops.mlir
  tests/filecheck/transforms/convert-stencil-to-ll-mlir.mlir
  tests/filecheck/transforms/stencil-shape-inference.mlir
  xdsl/dialects/stencil.py
  xdsl/transforms/experimental/ConvertStencilToLLMLIR.py
  xdsl/transforms/experimental/StencilShapeInference.py
Labels: dialects, transformations

#1071 bench: set up airspeed velocity for performance tracking
  .gitignore
  asv.conf.json
  bench/asv_bench/README.md
  bench/asv_bench/__init__.py
  bench/asv_bench/import_xdsl_opt.py
  requirements-optional.txt
Labels: CI, bench

#1103 docs: lint database notebook
  docs/database_example.ipynb
Labels: documentation

#1080 Core: Add IsTerminator trait
  tests/filecheck/parser-printer/graph_region.mlir
  tests/test_builtin_traits.py
  tests/test_ir.py
  tests/test_operation_builder.py
  xdsl/dialects/cf.py
  xdsl/dialects/func.py
  xdsl/dialects/scf.py
  xdsl/dialects/test.py
  xdsl/ir/core.py
  xdsl/traits.py
Labels: core

#1095 core: don't use type hints for OpDef
  docs/Toy/Toy_Ch2.ipynb
  docs/Toy/toy/dialects/toy.py
  docs/database_example.ipynb
  docs/irdl.ipynb
  docs/xdsl-introduction.ipynb
  remove_annotated.sed
  tests/dialects/test_mpi_lowering.py
  tests/test_builtin_traits.py
  tests/test_ir.py
  tests/test_operation_builder.py
  tests/test_operation_definition.py
  tests/test_parser.py
  tests/test_parser_error.py
  tests/test_printer.py
  tests/test_ssa_value.py
  tests/test_traits.py
  xdsl/dialects/affine.py
  xdsl/dialects/arith.py
  xdsl/dialects/builtin.py
  xdsl/dialects/cf.py
  xdsl/dialects/cmath.py
  xdsl/dialects/experimental/dmp.py
  xdsl/dialects/experimental/fir.py
  xdsl/dialects/experimental/math.py
  xdsl/dialects/func.py
  xdsl/dialects/gpu.py
  xdsl/dialects/irdl.py
  xdsl/dialects/llvm.py
  xdsl/dialects/memref.py
  xdsl/dialects/mpi.py
  xdsl/dialects/pdl.py
  xdsl/dialects/riscv.py
  xdsl/dialects/riscv_func.py
  xdsl/dialects/scf.py
  xdsl/dialects/snitch.py
  xdsl/dialects/snitch_runtime.py
  xdsl/dialects/stencil.py
  xdsl/dialects/test.py
  xdsl/dialects/vector.py
  xdsl/frontend/symref.py
  xdsl/irdl.py
Labels: API, core, bench

#1104 core: Move backend related files to separate directories
  .github/CODEOWNERS
  tests/backend/riscv/test_regalloc.py
  tests/filecheck/backend/riscv/riscv_register_allocation_block_naive.mlir
  tests/filecheck/backend/riscv/riscv_register_allocation_jregs.mlir
  xdsl/backend/__init__.py
  xdsl/backend/riscv/__init__.py
  xdsl/backend/riscv/register_allocation.py
  xdsl/transforms/riscv_register_allocation.py
Labels: core

#1114 core: Create ParserState (NFC)
  xdsl/parser.py
Labels: core

#1113 dialects: (print) Initial println op added
  tests/filecheck/dialects/print/invalid.mlir
  tests/filecheck/dialects/print/print_basics.mlir
  xdsl/dialects/print.py
  xdsl/xdsl_opt_main.py
Labels: dialects

#1110 dialects: Add more stencil rank verification
  tests/dialects/test_stencil.py
  tests/filecheck/dialects/stencil/invalid.mlir
  tests/filecheck/transforms/stencil-shape-inference.mlir
  xdsl/dialects/stencil.py
Labels: dialects

#1106 core: IRDL to PyRDL translation
  setup.py
  tests/filecheck/dialects/irdl/irdl-to-pyrdl/testd.irdl.mlir
  tests/filecheck/lit.cfg
  xdsl/dialects/irdl/__init__.py
  xdsl/dialects/irdl/irdl.py
  xdsl/dialects/irdl/irdl_to_pyrdl.py
  xdsl/tools/irdl_to_pyrdl.py
Labels: core

#1119 core: deprecate Block.from_callable and replace with builder/implicit builder
  docs/Toy/toy/dialects/toy.py
  docs/xdsl-introduction.ipynb
  tests/dialects/test_affine.py
  tests/dialects/test_func.py
  xdsl/dialects/affine.py
  xdsl/dialects/func.py
  xdsl/dialects/pdl.py
  xdsl/ir/core.py
Labels: core

#1125 core: Allow to have a different accessor than attribute name
  tests/test_operation_definition.py
  xdsl/dialects/builtin.py
  xdsl/dialects/memref.py
  xdsl/dialects/pdl.py
  xdsl/irdl.py
Labels: core

#1127 core: Add support for `isa(..., set)`
  tests/test_is_satisfying_hint.py
  xdsl/utils/hints.py
Labels: core

#1126 core: Remove runtime type check in Data
  tests/test_attribute_definition.py
  xdsl/dialects/builtin.py
  xdsl/irdl.py
Labels: core

#1129 core: Add successor branching verification
  tests/test_ir.py
  tests/test_operation_builder.py
  xdsl/ir/core.py
Labels: core

#1123 [WIP] dialects: Add more stencil verification
  tests/filecheck/dialects/stencil/invalid.mlir
  xdsl/dialects/stencil.py
Labels: dialects

#1111 transformations: Add stencil-storage-materialization and first tests.
  tests/filecheck/transforms/stencil-storage-materialization.mlir
  xdsl/dialects/stencil.py
  xdsl/transforms/experimental/StencilStorageMaterialization.py
  xdsl/xdsl_opt_main.py
Labels: transformations

#1134 misc: Rename stencil transformations files
  xdsl/transforms/experimental/convert_stencil_to_ll_mlir.py
  xdsl/transforms/experimental/dmp/stencil_global_to_local.py
  xdsl/transforms/experimental/stencil_shape_inference.py
  xdsl/transforms/experimental/stencil_storage_materialization.py
  xdsl/xdsl_opt_main.py
Labels: minor

#1121 dialects: (llvm) Add `func` and `call` ops
  tests/dialects/test_llvm.py
  tests/filecheck/dialects/llvm/invalid.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/llvm/llvm_func.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/llvm/llvm_types.mlir
  xdsl/dialects/arith.py
  xdsl/dialects/llvm.py
Labels: dialects

#1135 transformations: Update the stencil lowerings targetting GPU
  tests/filecheck/dialects/stencil/hdiff_gpu.mlir
  xdsl/transforms/experimental/convert_stencil_to_ll_mlir.py
Labels: transformations

#1136 dialects: use Op __init__ and traits on gpu operations
  tests/dialects/test_gpu.py
  tests/filecheck/dialects/gpu/module_unterminated.mlir
  tests/filecheck/dialects/gpu/terminator_terminate.mlir
  tests/filecheck/dialects/gpu/yield_terminate.mlir
  xdsl/dialects/gpu.py
  xdsl/transforms/experimental/convert_stencil_to_ll_mlir.py
Labels: dialects

#1141 core: pyrdl generation fix codegen
  tests/filecheck/dialects/irdl/irdl-to-pyrdl/testd.irdl.mlir
  xdsl/dialects/irdl/irdl_to_pyrdl.py
Labels: core

#1139 dialects: implement partial gpu.FuncOp and gpu.ReturnOp
  tests/filecheck/dialects/gpu/invalid.mlir
  tests/filecheck/dialects/gpu/ops.mlir
  xdsl/dialects/gpu.py
Labels: dialects

#1142 transforms: (print) Add a lowering to printf
  tests/dialects/test_print.py
  tests/filecheck/dialects/print/print_to_printf.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/print/print_to_printf.mlir
  xdsl/dialects/llvm.py
  xdsl/dialects/print.py
  xdsl/transforms/print_to_println.py
  xdsl/xdsl_opt_main.py
Labels: transformations

#1153 core: Fix generic Operation verifier for termination
  tests/test_builtin_traits.py
  xdsl/ir/core.py
Labels: minor, core

#1151 dialects: Implement and test memref.CopyOp.
  tests/dialects/test_memref.py
  tests/filecheck/mlir-conversion/with-mlir/dialects/memref/memref_ops_mlir_conversion.mlir
  xdsl/dialects/memref.py
Labels: dialects, minor

#1154 dialects/core: Add missing `IsTerminator` and `HasParent` traits to dialects
  docs/Toy/toy/dialects/toy.py
  docs/xdsl-introduction.ipynb
  tests/dialects/test_scf.py
  tests/filecheck/dialects/pdl/custom-format-empty-rewriter-with-root-op.mlir
  tests/filecheck/dialects/pdl/custom-format-empty-rewriter.mlir
  tests/filecheck/dialects/pdl/custom-format-external-rewriter-with-arg.mlir
  tests/filecheck/dialects/pdl/custom-format-external-rewriter.mlir
  tests/filecheck/dialects/pdl/custom-format-inline-rewriter.mlir
  tests/filecheck/dialects/riscv/riscv_assembly_emission.mlir
  tests/filecheck/dialects/riscv/riscv_ops.mlir
  tests/filecheck/dialects/scf/reduce_no_return.mlir
  xdsl/dialects/affine.py
  xdsl/dialects/irdl/irdl.py
  xdsl/dialects/pdl.py
  xdsl/dialects/riscv.py
  xdsl/dialects/riscv_func.py
  xdsl/dialects/scf.py
  xdsl/ir/core.py
Labels: dialects

#1146 core: add SymbolOpInterface and leverage in interpreter
  docs/Toy/toy/__main__.py
  docs/Toy/toy/dialects/toy.py
  docs/Toy/toy/interpreter.py
  tests/interpreters/test_pdl_interpreter.py
  tests/test_traits.py
  xdsl/interpreter.py
  xdsl/traits.py
Labels: core

#1163 dialects: (pdl) simplify rewrite pattern and implementations
  tests/interpreters/test_pdl_interpreter.py
  xdsl/interpreters/experimental/pdl.py
Labels: dialects

#1164 api: add concept of running blocks and regions to interpreter
  docs/Toy/toy/__main__.py
  docs/Toy/toy/dialects/toy.py
  docs/Toy/toy/interpreter.py
  xdsl/interpreter.py
  xdsl/interpreters/experimental/pdl.py
Labels: API

#1159 transformations: Use subviews and memcopy in stencil distribution pass.
  xdsl/transforms/experimental/dmp/stencil_global_to_local.py
Labels: minor, transformations

#1156 core: Simplify successor terminator conditions
  tests/test_builtin_traits.py
  tests/test_ir.py
  xdsl/ir/core.py
Labels: core

#1165 api: add impl_terminator annotation and leverage in interpretation
  docs/Toy/toy/interpreter.py
  xdsl/interpreter.py
  xdsl/interpreters/experimental/pdl.py
Labels: API

#1124 core: Add boilerplate to convert PyRDL to an IRDL program
  tests/filecheck/dialects/irdl/pyrdl-to-irdl/cmath-conversion.py
  xdsl/dialects/irdl/pyrdl_to_irdl.py
Labels: core

#1161 dialects: Implement gpu.unregister_host and gpu.launch_func.
  tests/dialects/test_gpu.py
  tests/filecheck/dialects/gpu/ops.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/gpu/ops.mlir
  xdsl/dialects/gpu.py
Labels: dialects

#1166 core: add CallableOpInterface and use in interpreter
  docs/Toy/toy/__main__.py
  docs/Toy/toy/dialects/toy.py
  docs/Toy/toy/interpreter.py
  xdsl/interpreter.py
  xdsl/traits.py
Labels: core

#1168 dialects: (func) Add custom syntax for func.return
  tests/dialects/test_func.py
  tests/dialects/test_memref.py
  tests/filecheck/dialects/affine/examples.mlir
  tests/filecheck/dialects/cf/cf_ops.mlir
  tests/filecheck/dialects/cmath/cmath_ops.mlir
  tests/filecheck/dialects/func/func_ops.mlir
  tests/filecheck/dialects/scf/scf_ops.mlir
  tests/filecheck/dialects/stencil/hdiff_gpu.mlir
  tests/filecheck/dialects/stencil/stencil_ops.mlir
  tests/filecheck/frontend/dialects/affine.py
  tests/filecheck/frontend/dialects/func.py
  tests/filecheck/frontend/dialects/scf.py
  tests/filecheck/mlir-conversion/with-mlir/dialects/func/func_ops.mlir
  tests/filecheck/transforms/convert-stencil-to-ll-mlir.mlir
  tests/filecheck/transforms/stencil-shape-inference.mlir
  tests/filecheck/transforms/stencil-storage-materialization.mlir
  tests/interpreters/test_pdl_interpreter.py
  xdsl/dialects/func.py
  xdsl/frontend/code_generation.py
Labels: dialects

#1147 core: Implement parsing for Affine IR constructs
  tests/filecheck/mlir-conversion/with-mlir/affine_map.mlir
  tests/filecheck/parser-printer/affine_map.mlir
  tests/filecheck/parser-printer/unregistered_affine.mlir
  xdsl/dialects/builtin.py
  xdsl/ir/affine/affine_map.py
  xdsl/parser/__init__.py
  xdsl/parser/affine_parser.py
  xdsl/parser/core.py
Labels: core

#1173 misc: Add makefile and update readme
  Makefile
  README.md
Labels: xdsl

#1109 Add more Snitch runtime operations
  tests/filecheck/dialects/snitch_runtime/snitch_runtime_ops.mlir
  xdsl/dialects/snitch_runtime.py
Labels: dialects

#1177 dialects: offset mapping on stencil apply
  tests/dialects/test_stencil.py
  tests/filecheck/dialects/stencil/hdiff_gpu.mlir
  tests/filecheck/dialects/stencil/stencil_ops.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/stencil/hdiff.mlir
  tests/filecheck/transforms/convert-stencil-to-ll-mlir.mlir
  xdsl/dialects/stencil.py
  xdsl/transforms/experimental/convert_stencil_to_ll_mlir.py
Labels: dialects, transformations

#1184 core: Fix affine_map printing
  tests/filecheck/mlir-conversion/with-mlir/affine_map.mlir
  tests/filecheck/parser-printer/affine_map.mlir
  xdsl/printer.py
Labels: core

#1181 testing: use current environment for notebook tests
  Makefile
Labels: testing

#1182 transformations: Fix a crash on stencil conversion
  tests/filecheck/transforms/convert-stencil-to-ll-mlir.mlir
  xdsl/transforms/experimental/convert_stencil_to_ll_mlir.py
Labels: transformations

#1187 core: print floats same way MLIR does
  tests/filecheck/dialects/scf/reduce.mlir
  tests/filecheck/dialects/stencil/hdiff_gpu.mlir
  tests/filecheck/dialects/stencil/stencil_ops.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/builtin/unrealized_conversion_cast.mlir
  tests/filecheck/parser-printer/builtin_attrs.mlir
  tests/filecheck/parser-printer/float_parsing.mlir
  tests/filecheck/transforms/convert-stencil-to-ll-mlir.mlir
  tests/filecheck/transforms/stencil-shape-inference.mlir
  xdsl/printer.py
Labels: core

#1185 misc: use black to format notebooks
  docs/Toy/Toy_Ch1.ipynb
  docs/Toy/Toy_Ch2.ipynb
  docs/Toy/Toy_Ch3.ipynb
  docs/database_example.ipynb
  docs/irdl.ipynb
  docs/tutorial.ipynb
  docs/xdsl-introduction.ipynb
  requirements-optional.txt
Labels: minor

#1189 bug: Add missing __init__.py file
  xdsl/tools/__init__.py
Labels: bug

#1180 core: Remove unused backtracking function in parser
  tests/xdsl_opt/test_xdsl_opt.py
  xdsl/parser/core.py
  xdsl/utils/exceptions.py
Labels: core

#1190 misc: minor clean-up in stencil
  xdsl/dialects/stencil.py
Labels: minor

#1178 core: Implement constant folding for AffineExpr
  tests/filecheck/parser-printer/affine_map.mlir
  xdsl/ir/affine/affine_expr.py
  xdsl/parser/affine_parser.py
Labels: core

#1193 documentation: (toy) add option to print generic format in toy cli
  docs/Toy/toy/__main__.py
Labels: documentation

#1191 core: Factor BaseParser out of the parser (NFC)
  xdsl/parser/affine_parser.py
  xdsl/parser/base_parser.py
  xdsl/parser/core.py
Labels: core

#1192 core: surface original error when raising verification error
  xdsl/ir/core.py
  xdsl/utils/diagnostic.py
Labels: core

#1183 dialects: (affine) add store and load operations
  tests/filecheck/dialects/affine/affine_ops.mlir
  tests/filecheck/mlir-conversion/with-mlir/affine_map.mlir
  xdsl/dialects/affine.py
Labels: dialects

#1194 core: Cleanup Operation and IRNode definition
  xdsl/dialects/builtin.py
  xdsl/dialects/scf.py
  xdsl/ir/core.py
  xdsl/parser/core.py
Labels: core

#1200 misc: reorder test execution order in Makefile
  Makefile
Labels: CI

#1203 dialects: Remove deprecated builtin constructors
  xdsl/dialects/builtin.py
Labels: core

#1204 interpreter: add print interpreter functions
  tests/interpreters/test_print_interpreter.py
  xdsl/interpreters/print.py
Labels: interpreter

#1199 interpreter: introduce ShapedArray class for interpreter functions
  docs/Toy/toy/interpreter.py
  docs/Toy/toy/tests/test_interpreter.py
  tests/interpreters/test_shaped_array.py
  xdsl/interpreters/shaped_array.py
Labels: interpreter

#1196 core: Add structure to view an op operands
  tests/dialects/test_gpu.py
  tests/dialects/test_scf.py
  tests/test_ir.py
  tests/test_operation_builder.py
  xdsl/ir/core.py
  xdsl/irdl.py
  xdsl/printer.py
  xdsl/transforms/experimental/convert_stencil_to_ll_mlir.py
Labels: core

#1208 interpreter: add some floating point arith functions
  tests/interpreters/test_arith_interpreter.py
  xdsl/interpreters/arith.py
Labels: interpreter

#1188 dialects: (riscv) add initial support for F extension
  tests/backend/riscv/test_regalloc.py
  tests/dialects/test_riscv.py
  tests/dialects/test_snitch.py
  tests/filecheck/backend/riscv/riscv_register_allocation_block_naive.mlir
  tests/filecheck/backend/riscv/riscv_register_allocation_jregs.mlir
  tests/filecheck/dialects/riscv/riscv_assembly_emission.mlir
  tests/filecheck/dialects/riscv/riscv_ops.mlir
  xdsl/backend/riscv/register_allocation.py
  xdsl/dialects/riscv.py
  xdsl/interpreters/riscv_emulator.py
Labels: dialects

#1201 core: Fix terminator conditions for unregistered operations
  tests/filecheck/parser-printer/unregistered_dialect.mlir
  xdsl/ir/core.py
Labels: core

#1206 interpreter: add interpreter for func
  xdsl/dialects/func.py
  xdsl/interpreters/func.py
Labels: interpreter

#1207 docs: (toy) fix bug in toy interpreter test
  docs/Toy/examples/interpret.toy
  docs/Toy/toy/interpreter.py
Labels: interpreter

#1214 dialects: (printf) print -> printf
  tests/dialects/test_printf.py
  tests/filecheck/dialects/print/invalid.mlir
  tests/filecheck/dialects/print/print_basics.mlir
  tests/filecheck/dialects/print/printf_to_llvm.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/print/printf_to_llvm.mlir
  tests/interpreters/test_print_interpreter.py
  xdsl/dialects/printf.py
  xdsl/interpreters/printf.py
  xdsl/transforms/printf_to_llvm.py
  xdsl/xdsl_opt_main.py
Labels: dialects
