Repository xdslproject/xdsl, pull requests merged in 2023-02, with the labels that each got.

#391 API: Add parser methods to parse SSA values
  tests/test_printer.py
  xdsl/parser.py
Labels: API

#385 docs: Use JupyterLite 0.1.0b17
  .github/workflows/jupyterlite.yml
Labels: documentation

#397 misc: make op_type_rewrite_pattern type check
  tests/conftest.py
  tests/test_pattern_rewriter.py
  xdsl/pattern_rewriter.py
Labels: minor

#376 frontend: Add support for basic binary/comparison overloads and return
  tests/filecheck/frontend/dialects/arith.py
  tests/filecheck/frontend/dialects/func.py
  tests/filecheck/frontend/dialects/invalid.py
  tests/test_frontend_op_resolver.py
  tests/test_frontend_python_code_check.py
  xdsl/frontend/code_generation.py
  xdsl/frontend/context.py
  xdsl/frontend/dialects/arith.py
  xdsl/frontend/dialects/builtin.py
  xdsl/frontend/exception.py
  xdsl/frontend/op_inserter.py
  xdsl/frontend/op_resolver.py
  xdsl/frontend/program.py
  xdsl/frontend/python_code_check.py
  xdsl/frontend/type_conversion.py
Labels: frontend

#399 misc: pyright CI for diffs
  .github/workflows/ci-pyright.yml
Labels: CI

#386 xDSL/Vector: Add support for maskedstore, print and createmask op
  tests/dialects/test_vector.py
  tests/filecheck/dialects/vector/vector_createmask_indexing.xdsl
  tests/filecheck/dialects/vector/vector_createmask_verify_mask_type.xdsl
  tests/filecheck/dialects/vector/vector_maskedstore_indexing.xdsl
  tests/filecheck/dialects/vector/vector_maskedstore_mask_rank_check.xdsl
  tests/filecheck/dialects/vector/vector_maskedstore_mask_type_checking.xdsl
  tests/filecheck/dialects/vector/vector_maskedstore_memref_storevec_type_matching.xdsl
  tests/filecheck/dialects/vector/vector_maskedstore_storevec_rank_check.xdsl
  tests/filecheck/dialects/vector/vector_ops.xdsl
  tests/filecheck/dialects/vector/vector_ops_mlir_conversion.xdsl
  xdsl/dialects/vector.py
Labels: dialects

#402 CI: Remove CI dependencies from requirements
  .github/workflows/ci-core.yml
  .github/workflows/ci-mlir.yml
  requirements-optional.txt
Labels: CI

#403 core: Disallow fields in IRDL
  tests/test_attribute_definition.py
  tests/test_operation_definition.py
  tests/test_printer.py
  xdsl/irdl.py
  xdsl/utils/exceptions.py
  xdsl/utils/hints.py
Labels: xdsl, core

#414 xDSL: Add public print_block
  docs/Toy/toy/parser.py
  xdsl/ir.py
  xdsl/parser.py
  xdsl/printer.py
  xdsl/utils/diagnostic.py
Labels: core

#417 CI: Upload the line by line coverage
  codecov.yml
Labels: CI

#409 installation: Add xdsl-opt location to known paths
  .github/workflows/ci-mlir.yml
  setup.py
Labels: CI, installation

#412 dialects: Add dense_resource attribute
  tests/filecheck/mlir-conversion/builtin_attrs.mlir
  xdsl/dialects/builtin.py
  xdsl/parser.py
  xdsl/printer.py
Labels: dialects

#415 core: Allow to parse types where attributes are expected
  tests/filecheck/mlir-conversion/builtin_attrs.mlir
  xdsl/parser.py
Labels: bug, core

#327 Update MLIR hash to latest MLIR
  .github/workflows/ci-mlir.yml
  docs/mlir_interoperation.md
  tests/dialects/test_builtin.py
  tests/filecheck/cf_ops.xdsl
  tests/filecheck/dialects/builtin/attrs.xdsl
  tests/filecheck/dialects/builtin/dense_array_invalid_dims.xdsl
  tests/filecheck/dialects/builtin/dense_array_invalid_element.xdsl
  tests/filecheck/memref_ops.xdsl
  tests/filecheck/mlir-conversion/llvm_test.xdsl
  tests/filecheck/mlir-conversion/with-mlir/lit.local.cfg
  tests/filecheck/mlir-conversion/with-mlir/llvm_test.xdsl
  tests/filecheck/mlir-conversion/with-mlir/ops.xdsl
  tests/filecheck/mlir-conversion/with-mlir/symbol_tests.xdsl
  tests/test_mlir_converter.py
  tests/test_operation_builder.py
  xdsl/dialects/builtin.py
  xdsl/dialects/llvm.py
  xdsl/dialects/memref.py
  xdsl/irdl.py
  xdsl/mlir_converter.py
  xdsl/parser.py
  xdsl/printer.py
  xdsl/xdsl_opt_main.py
Labels: CI

#420 API: Fix some pyright issues in parser and dialects
  tests/filecheck/dialects/builtin/attrs.xdsl
  xdsl/dialects/arith.py
  xdsl/dialects/builtin.py
  xdsl/parser.py
Labels: API, core

#418 API: Fix pyright issues in xdsl-opt-main
  xdsl/irdl_mlir_printer.py
  xdsl/xdsl_opt_main.py
Labels: API, core

#419 API: Fix pyright issue in printer.py
  xdsl/printer.py
Labels: API, core

#392 docs: Rewrite README partially
  README.md
Labels: documentation

#369 CI: Reconfigure CI to cache built binaries
  .github/workflows/ci-mlir.yml
  tests/filecheck/mlir-conversion/with-mlir/lit.local.cfg
Labels: CI

#422 CI: Remove all occurences of the Python Bindings
  .github/workflows/ci-mlir.yml
Labels: CI

#423 xDSL/Vector: Improve tests
  tests/dialects/test_vector.py
  tests/filecheck/dialects/vector/vector_ops.xdsl
Labels: testing

#434 tests: fix PytestCollectionWarning due to naming
  tests/test_parser.py
Labels: testing

#438 CI: Remove coverage from the pyodide/JupyterLite deployment.
  .github/workflows/jupyterlite.yml
Labels: documentation, CI, minor

#436 tests: Add func.call tests
  docs/Toy/toy/dialect.py
  tests/dialects/test_func.py
  xdsl/dialects/builtin.py
  xdsl/dialects/func.py
Labels: testing

#442 xdsl: use irdl_definition in Operation.verify
  tests/test_operation_builder.py
  tests/test_operation_definition.py
  xdsl/ir.py
  xdsl/irdl.py
Labels: xdsl, core

#429 core: Add support for nested symbol references
  docs/Toy/toy/dialect.py
  tests/filecheck/dialects/builtin/attrs.xdsl
  tests/test_parser.py
  xdsl/dialects/builtin.py
  xdsl/dialects/func.py
  xdsl/dialects/memref.py
  xdsl/frontend/symref.py
  xdsl/parser.py
  xdsl/printer.py
Labels: core

#398 docs: Notebook introducing MLIR/xDSL concepts with examples
  docs/xdsl-introduction.ipynb
Labels: documentation

#435 dialects: Add basic MPI dialect
  tests/dialects/test_mpi.py
  xdsl/dialects/mpi.py
Labels: dialects, core

#406 bench: Defer error message formatting to when they are printed
  tests/filecheck/dialects/builtin/dense_array_invalid_dims.xdsl
  xdsl/utils/exceptions.py
Labels: enhancement

#416 core: Remove builder for attributes
  tests/test_attribute_builder.py
  tests/test_attribute_definition.py
  tests/test_operation_builder.py
  tests/test_ssa_value.py
  xdsl/dialects/builtin.py
  xdsl/dialects/func.py
  xdsl/dialects/llvm.py
  xdsl/dialects/memref.py
  xdsl/frontend/symref.py
  xdsl/ir.py
  xdsl/irdl.py
  xdsl/parser.py
Labels: core

#453 bug: Remove use of Attribute `build` method
  xdsl/dialects/mpi.py
Labels: bug

#445 xdsl: provide custom __str__ and __format__ functions for attrs and ops
  tests/test_ir.py
  xdsl/ir.py
Labels: xdsl, core

#310 CI: Add Pyright CI
  .github/workflows/ci-pyright-fails.yml
  pyright-ci.json
Labels: CI

#451 Reduce number of files with lint errors
  pyproject.toml
  pyright-ci.json
  tests/test_ir.py
  xdsl/_version.py
  xdsl/dialects/affine.py
  xdsl/dialects/arith.py
  xdsl/dialects/memref.py
  xdsl/dialects/mpi.py
  xdsl/utils/exceptions.py
  xdsl/xdsl_opt_main.py
Labels: CI, API

#443 dialects: Add scf.for
  tests/dialects/test_scf.py
  tests/filecheck/dialects/scf/for_args_number.mlir
  tests/filecheck/dialects/scf/for_args_types.mlir
  tests/filecheck/dialects/scf/for_body_args_number.mlir
  tests/filecheck/dialects/scf/for_body_args_number_much.mlir
  tests/filecheck/dialects/scf/for_body_args_types.mlir
  tests/filecheck/dialects/scf/for_iv.mlir
  tests/filecheck/dialects/scf/for_yield.mlir
  tests/filecheck/dialects/scf/for_yield_number.mlir
  tests/filecheck/dialects/scf/for_yield_types.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/scf/for_mlir.mlir
  tests/filecheck/scf_ops.xdsl
  xdsl/dialects/scf.py
Labels: dialects

#452 Lint frontend files
  pyright-ci.json
  tests/filecheck/frontend/dialects/arith.py
  tests/test_frontend_type_conversion.py
  xdsl/frontend/code_generation.py
  xdsl/frontend/context.py
  xdsl/frontend/dialects/arith.py
  xdsl/frontend/dialects/builtin.py
  xdsl/frontend/exception.py
  xdsl/frontend/op_resolver.py
  xdsl/frontend/program.py
  xdsl/frontend/python_code_check.py
  xdsl/frontend/type_conversion.py
Labels: enhancement, frontend

#465 dialects: Extend arith and func
  tests/dialects/test_arith.py
  tests/dialects/test_func.py
  xdsl/dialects/arith.py
  xdsl/dialects/func.py
Labels: dialects

#464 llvm: Add additional ops
  tests/dialects/test_llvm.py
  tests/filecheck/dialects/llvm/pointers.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/llvm/llvm_pointer_ops.mlir
  xdsl/dialects/llvm.py
Labels: dialects

#447 builtins: Extend MemRef to cover more of the MLIR dialect
  tests/dialects/test_memref.py
  tests/filecheck/mlir-conversion/with-mlir/dialects/memref/matmul.mlir
  xdsl/dialects/memref.py
Labels: dialects

#466 mpi: Cleanup definitions in preperations of the lowering
  tests/dialects/test_mpi.py
  xdsl/dialects/mpi.py
Labels: dialects

#470 core: Add SSAValue.definition property.
  tests/test_ir.py
  xdsl/ir.py
Labels: enhancement, API, minor, core

#456 dialects: Add GPU dialect first operations.
  tests/dialects/test_gpu.py
  tests/filecheck/dialects/gpu/example.mlir
  tests/filecheck/dialects/gpu/module_unnamed.mlir
  tests/filecheck/dialects/gpu/module_unterminated.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/gpu/example.mlir
  xdsl/dialects/gpu.py
  xdsl/xdsl_opt_main.py
Labels: dialects

#474 dialects: Add DimensionAttr and AllReduceOperationAttr to GPU dialect
  tests/dialects/test_gpu.py
  tests/filecheck/dialects/gpu/all_reduce_operation_unknown.mlir
  tests/filecheck/dialects/gpu/dimension_unknown.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/gpu/example.mlir
  xdsl/dialects/gpu.py
Labels: dialects

#475 install: Switch to using entry_points for xdsl-opt script.
  setup.py
  xdsl/tools/xdsl_opt.py
Labels: installation

#484 dialects: Add trivial GPU operations.
  tests/dialects/test_gpu.py
  tests/filecheck/dialects/gpu/example.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/gpu/example.mlir
  xdsl/dialects/gpu.py
Labels: dialects
