Repository xdslproject/xdsl, pull requests merged in 2023-04, with the labels that each got.

#625 core: rename MLIRType to TypeAttribute
  tests/test_mlir_printer.py
  xdsl/dialects/builtin.py
  xdsl/dialects/cmath.py
  xdsl/dialects/experimental/stencil.py
  xdsl/dialects/gpu.py
  xdsl/dialects/llvm.py
  xdsl/dialects/memref.py
  xdsl/dialects/mpi.py
  xdsl/dialects/pdl.py
  xdsl/ir.py
  xdsl/printer.py
Labels: API, core

#637 bug: Remove remaining use of MLIRType
  xdsl/interpreters/experimental/pdl.py
Labels: bug

#635 dialects: Minor bug fix for stencil transformation
  xdsl/transforms/experimental/ConvertStencilToLLMLIR.py
Labels: dialects, minor

#627 core: Add lexer in parser
  tests/test_parser.py
  xdsl/parser.py
Labels: core

#641 dialects: Missing math operations
  xdsl/dialects/experimental/math.py
Labels: dialects

#626 core: add UnregisteredAttr
  tests/test_mlctx.py
  xdsl/dialects/builtin.py
  xdsl/ir.py
Labels: dialects, core

#638 core: Add get_int_value method to Token
  tests/test_lexer.py
  xdsl/utils/lexer.py
Labels: core

#632 core: Add parsing and printing for UnregisteredAttr
  bench/parser/bench_parser.py
  docs/mlir_interoperation.ipynb
  tests/filecheck/mlir-conversion/unregistered_dialect.mlir
  tests/filecheck/mlir-conversion/unregistered_ops.mlir
  tests/filecheck/parser-printer/unregistered_ops.xdsl
  xdsl/parser.py
  xdsl/printer.py
  xdsl/xdsl_opt_main.py
Labels: core

#639 core: remove generic attr parsing
  tests/test_printer.py
Labels: core

#640 dialects: Add strided layout attribute
  tests/dialects/test_builtin.py
  tests/filecheck/mlir-conversion/builtin_attrs.mlir
  xdsl/dialects/builtin.py
  xdsl/parser.py
  xdsl/printer.py
Labels: dialects

#643 core: move backtracking from tokenizer to parser
  xdsl/parser.py
Labels: core

#644 core: add punctuation parsing
  tests/test_parser.py
  xdsl/parser.py
  xdsl/utils/lexer.py
Labels: core

#648 dialects: Add support for returning multiple results using stencil.return
  tests/filecheck/dialects/stencil/hdiff.mlir
  xdsl/dialects/experimental/stencil.py
  xdsl/transforms/experimental/ConvertStencilToLLMLIR.py
Labels: dialects

#649 core: allow optional attribute values in build argument
  xdsl/dialects/experimental/math.py
  xdsl/dialects/gpu.py
  xdsl/dialects/mpi.py
  xdsl/dialects/pdl.py
  xdsl/ir.py
  xdsl/irdl.py
Labels: core

#646 dialects: cmpf operation in arith dialect
  tests/dialects/test_arith.py
  tests/filecheck/arith_ops.xdsl
  tests/filecheck/mlir-conversion/with-mlir/dialects/arith/arith_cmp.mlir
  xdsl/dialects/arith.py
  xdsl/frontend/dialects/arith.py
Labels: dialects, minor

#652 misc: add pyright to requirements-optional.txt
  requirements-optional.txt
Labels: minor

#651 core: operands, result_types, and regions args in build accept optional values
  docs/Toy/toy/dialect.py
  xdsl/dialects/gpu.py
  xdsl/ir.py
  xdsl/irdl.py
Labels: core

#657 dialects: A revert for PR 648
  tests/filecheck/dialects/stencil/hdiff.mlir
  xdsl/dialects/experimental/stencil.py
  xdsl/transforms/experimental/ConvertStencilToLLMLIR.py
Labels: dialects

#654 dialects: Negf operation added to arith dialect
  tests/dialects/test_arith.py
  tests/filecheck/arith_ops.xdsl
  tests/filecheck/mlir-conversion/with-mlir/dialects/arith/arith_fp_ops.mlir
  xdsl/dialects/arith.py
Labels: dialects, minor

#653 dialects: Add a builder for fully static memref.subview
  tests/dialects/test_memref.py
  tests/filecheck/dialects/memref/memref_ops.mlir
  tests/filecheck/dialects/memref/memref_ops.xdsl
  xdsl/dialects/memref.py
Labels: dialects

#634 RFC: implicit builder regions
  docs/Toy/toy/tests/test_ir_gen.py
  tests/dialects/test_op_builder.py
  tests/interpreters/test_pdl_interpreter.py
  tests/test_op_builder.py
  xdsl/builder.py
Labels: core

#661 dialects: 1D MPI halo swapping for stencil dialect
  xdsl/transforms/experimental/Apply1DMPIToStencil.py
Labels: dialects

#662 dialects: Enhance stencil testing
  tests/filecheck/dialects/stencil/heat_stencil.mlir
  tests/filecheck/dialects/stencil/heat_stencil_inference.mlir
  tests/filecheck/dialects/stencil/heat_stencil_inference_ll.mlir
  tests/filecheck/dialects/stencil/test_access_lowering_1d.mlir
  tests/filecheck/dialects/stencil/test_access_lowering_2d.mlir
  tests/filecheck/dialects/stencil/test_access_lowering_3d.mlir
  tests/filecheck/dialects/stencil/test_castop_lowering_1d.mlir
  tests/filecheck/dialects/stencil/test_castop_lowering_3d.mlir
  xdsl/dialects/experimental/stencil.py
  xdsl/transforms/experimental/ConvertStencilToLLMLIR.py
Labels: tests

#670 ci: bump pyright version in CI
  .github/workflows/ci-pyright-fails.yml
  .github/workflows/ci-pyright.yml
Labels: CI

#669 dialects: Reverse array indexing for converting `stencil` to LLMLIR
  tests/filecheck/dialects/stencil/hdiff.mlir
  tests/filecheck/dialects/stencil/hdiff_gpu.mlir
  tests/filecheck/dialects/stencil/heat_stencil_inference_ll.mlir
  tests/filecheck/dialects/stencil/test_access_lowering_2d.mlir
  tests/filecheck/dialects/stencil/test_access_lowering_3d.mlir
  tests/filecheck/dialects/stencil/test_store_lowering.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/stencil/hdiff.mlir
  xdsl/transforms/experimental/ConvertStencilToLLMLIR.py
Labels: dialects

#672 tests: add a TestSSAValue object for tests
  tests/dialects/test_memref.py
  tests/dialects/test_vector.py
  tests/test_traits.py
  xdsl/utils/test_value.py
Labels: tests

#677 misc: lint test_vector.py
  pyproject.toml
  tests/dialects/test_vector.py
  xdsl/dialects/vector.py
Labels: CI, minor

#676 core: Allow op_type_rewrite_pattern to use unions
  tests/test_pattern_rewriter.py
  xdsl/pattern_rewriter.py
Labels: core

#679 dialects: mpi+stencil Add a loop-invariant-code-motion pass to move allocations and mpi_comm_rank calls out of loops
  xdsl/transforms/experimental/ConvertStencilToLLMLIR.py
  xdsl/transforms/experimental/stencil_global_to_local.py
Labels: dialects

#684 ci: lint test_func.py
  pyproject.toml
  tests/dialects/test_func.py
Labels: minor

#680 core: add block init with all the fields
  xdsl/ir.py
  xdsl/parser.py
Labels: core

#682 core: use init for creating regions, as opposed to constructor method
  docs/Toy/toy/dialect.py
  docs/Toy/toy/ir_gen.py
  docs/mlir_interoperation.ipynb
  tests/dialects/test_affine.py
  tests/dialects/test_func.py
  tests/dialects/test_scf.py
  tests/test_frontend_op_inserter.py
  tests/test_ir.py
  tests/test_operation_builder.py
  xdsl/builder.py
  xdsl/dialects/affine.py
  xdsl/dialects/experimental/stencil.py
  xdsl/dialects/func.py
  xdsl/dialects/pdl.py
  xdsl/frontend/code_generation.py
  xdsl/ir.py
  xdsl/irdl.py
  xdsl/rewriting/composable_rewriting/immutable_ir/immutable_ir.py
Labels: API, core

#665 core: Add parse_integer function
  tests/test_parser.py
  xdsl/parser.py
Labels: core

#686 core: deprecate Block.from_arg_types
  docs/Toy/toy/ir_gen.py
  docs/irdl.ipynb
  tests/dialects/test_affine.py
  tests/dialects/test_cf.py
  tests/dialects/test_func.py
  tests/dialects/test_gpu.py
  tests/dialects/test_pdl.py
  tests/dialects/test_scf.py
  tests/test_printer.py
  xdsl/builder.py
  xdsl/ir.py
  xdsl/rewriting/composable_rewriting/immutable_ir/immutable_ir.py
Labels: API

#685 core: Allow to parse comma separated undelimeted lists
  tests/test_parser.py
  xdsl/parser.py
Labels: core

#694 examples: Update database example to latest xDSL
  .github/workflows/ci-notebooks.yml
  docs/database_example.ipynb
Labels: documentation

#687 core: Allow using value tuples in MLIR syntax
  tests/filecheck/mlir-conversion/value_tuple.mlir
  tests/filecheck/mlir-conversion/value_tuple_access_oob.mlir
  tests/filecheck/mlir-conversion/value_tuple_wrong_number.mlir
  tests/test_parser.py
  xdsl/parser.py
Labels: core

#688 dialects: Add encoding on tensors
  tests/filecheck/dialects/builtin/attrs.xdsl
  tests/filecheck/mlir-conversion/builtin_attrs.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/memref/memref_ops_mlir_conversion.mlir
  tests/filecheck/mlir-conversion/with-mlir/symbol_tests.mlir
  tests/filecheck/mlir-conversion/with-mlir/symbol_tests.xdsl
  tests/test_printer.py
  xdsl/dialects/builtin.py
  xdsl/parser.py
  xdsl/printer.py
Labels: dialects, core

#689 dialects: Add ComplexType, and parsing for it
  tests/dialects/test_builtin.py
  tests/filecheck/mlir-conversion/builtin_attrs.mlir
  xdsl/dialects/builtin.py
  xdsl/parser.py
  xdsl/printer.py
Labels: dialects, core

#690 core: Reimplement shape parser with new lexer
  tests/filecheck/mlir-conversion/builtin_attrs.mlir
  xdsl/parser.py
Labels: dialects

#692 dialects: Add better init for IntegerAttr
  xdsl/dialects/builtin.py
Labels: dialects

#696 misc: Slight refactoring/improvement for docs
  tests/rewriting/composable_rewriting/immutable_ir/test_immutable_ir.py
  tests/test_frontend_op_inserter.py
  tests/test_frontend_op_resolver.py
  tests/test_interpreter.py
  tests/test_ir.py
  tests/test_is_satisfying_hint.py
  tests/test_operation_builder.py
  tests/test_operation_definition.py
  tests/test_parser.py
  tests/test_pattern_rewriter.py
  tests/test_pyrdl.py
  tests/test_traits.py
  tests/test_use.py
  xdsl/dialects/experimental/math.py
  xdsl/dialects/memref.py
Labels: minor

#611 dialects: Make passes a type
  tests/xdsl_opt/test_xdsl_opt.py
  xdsl/frontend/passes/desymref.py
  xdsl/passes.py
  xdsl/transforms/experimental/ConvertStencilToLLMLIR.py
  xdsl/transforms/experimental/stencil_global_to_local.py
  xdsl/transforms/lower_mpi.py
  xdsl/xdsl_opt_main.py
Labels: dialects, API

#666 dialects: Tobias stencil memref.subview
  tests/filecheck/dialects/stencil/hdiff.mlir
  tests/filecheck/dialects/stencil/hdiff_gpu.mlir
  tests/filecheck/dialects/stencil/heat_stencil_inference_ll.mlir
  tests/filecheck/dialects/stencil/test_access_lowering_1d.mlir
  tests/filecheck/dialects/stencil/test_access_lowering_2d.mlir
  tests/filecheck/dialects/stencil/test_access_lowering_3d.mlir
  tests/filecheck/dialects/stencil/test_apply_lowering.mlir
  tests/filecheck/dialects/stencil/test_loadop_lowering.mlir
  tests/filecheck/dialects/stencil/test_store_lowering.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/stencil/hdiff.mlir
  xdsl/transforms/experimental/ConvertStencilToLLMLIR.py
Labels: dialects

#678 dialects: Use memref.subview for stencil.store
  tests/filecheck/dialects/stencil/hdiff.mlir
  tests/filecheck/dialects/stencil/hdiff_gpu.mlir
  tests/filecheck/dialects/stencil/heat_stencil_inference_ll.mlir
  tests/filecheck/dialects/stencil/test_store_lowering.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/stencil/hdiff.mlir
  xdsl/transforms/experimental/ConvertStencilToLLMLIR.py
Labels: dialects

#701 core: Add tuple support to isa
  tests/test_is_satisfying_hint.py
  xdsl/utils/hints.py
Labels: minor, core

#713 docs: Fix install guide in the README
  README.md
Labels: documentation, installation

#705 dialects: Make vector generic arguments covariants
  xdsl/dialects/builtin.py
Labels: dialects, API

#716 CI: Remove codecov in CI
  .github/workflows/ci-mlir.yml
Labels: CI

#706 dialects: Disallow unranked dense attributes
  xdsl/dialects/builtin.py
  xdsl/parser.py
Labels: dialects

#709 core: Add public 'parse_boolean' methods
  tests/test_parser.py
  xdsl/parser.py
Labels: core

#708 core: Parse negative and hexadecimal values in integer attributes
  tests/filecheck/mlir-conversion/builtin_attrs.mlir
  xdsl/parser.py
Labels: core

#720 dialects: Move stencil shape inference to its own file
  xdsl/transforms/experimental/ConvertStencilToLLMLIR.py
  xdsl/transforms/experimental/StencilShapeInference.py
  xdsl/xdsl_opt_main.py
Labels: dialects

#718 core: Add scalable dimensions to vector
  tests/dialects/test_builtin.py
  tests/filecheck/arith_ops.xdsl
  tests/filecheck/dialects/vector/vector_broadcast_type_matching.xdsl
  tests/filecheck/dialects/vector/vector_createmask_indexing.xdsl
  tests/filecheck/dialects/vector/vector_fma_res_acc_shape_matching.xdsl
  tests/filecheck/dialects/vector/vector_fma_res_acc_type_matching.xdsl
  tests/filecheck/dialects/vector/vector_fma_res_lhs_shape_matching.xdsl
  tests/filecheck/dialects/vector/vector_fma_res_lhs_type_matching.xdsl
  tests/filecheck/dialects/vector/vector_fma_res_rhs_shape_matching.xdsl
  tests/filecheck/dialects/vector/vector_fma_res_rhs_type_matching.xdsl
  tests/filecheck/dialects/vector/vector_load_indexing.xdsl
  tests/filecheck/dialects/vector/vector_load_type_matching.xdsl
  tests/filecheck/dialects/vector/vector_maskedload_indexing.xdsl
  tests/filecheck/dialects/vector/vector_maskedload_memref_passthrough_type_matching.xdsl
  tests/filecheck/dialects/vector/vector_maskedload_memref_res_type_matching.xdsl
  tests/filecheck/dialects/vector/vector_maskedstore_indexing.xdsl
  tests/filecheck/dialects/vector/vector_maskedstore_memref_storevec_type_matching.xdsl
  tests/filecheck/dialects/vector/vector_ops.xdsl
  tests/filecheck/dialects/vector/vector_ops_mlir_conversion.xdsl
  tests/filecheck/dialects/vector/vector_store_indexing.xdsl
  tests/filecheck/dialects/vector/vector_store_type_matching.xdsl
  tests/filecheck/mlir-conversion/builtin_attrs.mlir
  xdsl/dialects/builtin.py
  xdsl/parser.py
  xdsl/printer.py
Labels: dialects, core

#719 core: Fix function type parsing
  tests/filecheck/mlir-conversion/builtin_attrs.mlir
  xdsl/parser.py
Labels: core

#664 core: Move custom Operation verification 'verify_()' to end of verify function
  tests/test_ir.py
  xdsl/ir.py
Labels: bug, core

#723 core: allow block.insert_op to take negative positions
  tests/test_pattern_rewriter.py
  xdsl/ir.py
Labels: API, minor, core

#726 minor: Remove classmethod from op constructors
  xdsl/dialects/arith.py
  xdsl/dialects/gpu.py
  xdsl/dialects/llvm.py
  xdsl/dialects/memref.py
Labels: minor

#659 dialects: Update support for returning multiple results using stencil.return
  tests/dialects/test_stencil.py
  tests/filecheck/dialects/stencil/hdiff.mlir
  xdsl/dialects/experimental/stencil.py
  xdsl/transforms/experimental/ConvertStencilToLLMLIR.py
Labels: dialects

#735 CI: Add coverage back.
  .github/workflows/ci-mlir.yml
Labels: CI

#733 tests: Move tests to their correct folders
  tests/filecheck/dialects/affine/affine_ops.xdsl
  tests/filecheck/dialects/arith/arith_invalid.xdsl
  tests/filecheck/dialects/arith/arith_ops.xdsl
  tests/filecheck/dialects/cf/cf_ops.mlir
  tests/filecheck/dialects/cf/cf_ops.xdsl
  tests/filecheck/dialects/cmath/cmath_ops.xdsl
  tests/filecheck/dialects/func/func_ops.xdsl
  tests/filecheck/dialects/irdl/cmath.xdsl
  tests/filecheck/dialects/irdl/irdl_any_and_base_type.xdsl
  tests/filecheck/dialects/irdl/irdl_missing_operand.xdsl
  tests/filecheck/dialects/scf/scf_ops.xdsl
Labels: tests

#725 dialects: Add helpers to FuncOp to make rewriting easier
  tests/dialects/test_func.py
  xdsl/dialects/func.py
Labels: enhancement, dialects

#743 Add Region.block property for single-block Regions
  xdsl/dialects/builtin.py
  xdsl/dialects/scf.py
  xdsl/frontend/code_generation.py
  xdsl/ir.py
  xdsl/transforms/experimental/ConvertStencilToLLMLIR.py
  xdsl/transforms/lower_mpi.py
Labels: API, core

#738 misc: lint tutorial.ipynb
  docs/tutorial.ipynb
Labels: minor

#736 core: deprecate Region.from_op_list
  docs/tutorial.ipynb
  tests/dialects/test_func.py
  tests/dialects/test_gpu.py
  tests/dialects/test_irdl.py
  tests/test_ir.py
  tests/test_pattern_rewriter.py
  xdsl/dialects/builtin.py
  xdsl/dialects/func.py
  xdsl/ir.py
  xdsl/transforms/experimental/stencil_global_to_local.py
Labels: API

#722 core: Define IRDLOperation, and simply move Operation.build there for now.
  docs/Toy/toy/dialect.py
  docs/database_example.ipynb
  docs/irdl.ipynb
  docs/xdsl-introduction.ipynb
  tests/dialects/test_mpi_lowering.py
  tests/test_ir.py
  tests/test_mlctx.py
  tests/test_mlir_printer.py
  tests/test_operation_builder.py
  tests/test_operation_definition.py
  tests/test_parser.py
  tests/test_parser_error.py
  tests/test_printer.py
  tests/test_ssa_value.py
  tests/test_traits.py
  xdsl/dialects/affine.py
  xdsl/dialects/arith.py
  xdsl/dialects/builtin.py
  xdsl/dialects/cf.py
  xdsl/dialects/cmath.py
  xdsl/dialects/experimental/math.py
  xdsl/dialects/experimental/stencil.py
  xdsl/dialects/func.py
  xdsl/dialects/gpu.py
  xdsl/dialects/irdl.py
  xdsl/dialects/llvm.py
  xdsl/dialects/memref.py
  xdsl/dialects/mpi.py
  xdsl/dialects/pdl.py
  xdsl/dialects/scf.py
  xdsl/dialects/vector.py
  xdsl/frontend/symref.py
  xdsl/ir.py
  xdsl/irdl.py
Labels: API, core

#745 misc: add first/last_op to Block
  docs/Toy/toy/dialect.py
  docs/Toy/toy/interpreter.py
  docs/Toy/toy/ir_gen.py
  tests/test_pattern_rewriter.py
  tests/test_rewriter.py
  xdsl/dialects/func.py
  xdsl/dialects/gpu.py
  xdsl/dialects/scf.py
  xdsl/ir.py
Labels: API

#700 core: Refactor operation creation to be __init__ based.
  xdsl/ir.py
  xdsl/irdl.py
Labels: API, core

#749 misc: Add missing __init__ files
  xdsl/interpreters/__init__.py
  xdsl/interpreters/experimental/__init__.py
  xdsl/rewriting/__init__.py
  xdsl/rewriting/composable_rewriting/__init__.py
  xdsl/rewriting/composable_rewriting/immutable_ir/__init__.py
  xdsl/transforms/experimental/__init__.py
Labels: core

#744 misc: allow passing single block to Region init
  docs/Toy/toy/dialect.py
  docs/Toy/toy/ir_gen.py
  docs/database_example.ipynb
  docs/irdl.ipynb
  docs/mlir_interoperation.ipynb
  docs/xdsl-introduction.ipynb
  tests/dialects/test_affine.py
  tests/dialects/test_func.py
  tests/dialects/test_scf.py
  tests/test_ir.py
  tests/test_operation_builder.py
  xdsl/builder.py
  xdsl/dialects/affine.py
  xdsl/dialects/experimental/stencil.py
  xdsl/dialects/func.py
  xdsl/dialects/pdl.py
  xdsl/frontend/code_generation.py
  xdsl/ir.py
  xdsl/irdl.py
  xdsl/transforms/experimental/ConvertStencilToLLMLIR.py
Labels: API

#758 core: add Block.insert_op(s?)_(before|after)
  xdsl/ir.py
  xdsl/pattern_rewriter.py
  xdsl/rewriter.py
Labels: core

#753 misc: migrate Toy dialect to inits
  docs/Toy/toy/dialect.py
  docs/Toy/toy/ir_gen.py
  docs/Toy/toy/tests/test_interpreter.py
  docs/Toy/toy/tests/test_ir_gen.py
Labels: API, minor

#727 dialects: scf.if make else region optional
  tests/dialects/test_scf.py
  xdsl/dialects/scf.py
Labels: enhancement, dialects, minor

#757 misc: add is_empty property to block
  docs/Toy/toy/dialect.py
  docs/Toy/toy/ir_gen.py
  xdsl/dialects/func.py
  xdsl/dialects/gpu.py
  xdsl/ir.py
Labels: API

#751 misc: move irdl_definition to IRDLOperation
  xdsl/ir.py
  xdsl/irdl.py
Labels: minor

#742 tests: Add test dialect
  tests/filecheck/dialects/func/func_ops.xdsl
  tests/filecheck/dialects/scf/scf_ops.xdsl
  xdsl/dialects/test.py
  xdsl/xdsl_opt_main.py
Labels: dialects, tests

#759 docu: Make notebook use MLIR output
  docs/database_example.ipynb
  docs/irdl.ipynb
  docs/xdsl-introduction.ipynb
Labels: documentation

#761 docs: fix ch2
  docs/Toy/Toy_Ch2.ipynb
Labels: documentation

#767 core: deprecate ModuleOp.from_region_or_ops
  docs/Toy/Toy_Ch2.ipynb
  docs/Toy/toy/ir_gen.py
  docs/Toy/toy/tests/test_interpreter.py
  docs/Toy/toy/tests/test_ir_gen.py
  docs/database_example.ipynb
  docs/mlir_interoperation.ipynb
  tests/dialects/test_func.py
  tests/dialects/test_llvm.py
  tests/dialects/test_memref.py
  tests/dialects/test_mpi_lowering.py
  tests/dialects/test_scf.py
  tests/interpreters/test_pdl_interpreter.py
  tests/test_interpreter.py
  tests/test_ir.py
  tests/test_pattern_rewriter.py
  tests/test_printer.py
  xdsl/dialects/builtin.py
  xdsl/frontend/code_generation.py
Labels: core

#760 dialects: Support in LLVM dialect for global and addressof operations
  tests/dialects/test_llvm.py
  tests/filecheck/dialects/llvm/global.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/llvm/global.mlir
  xdsl/dialects/llvm.py
Labels: dialects

#756 core: Add detach_region and get_region_index in Operation
  tests/test_ir.py
  xdsl/ir.py
Labels: core

#741 builtin: Add `__iter__` method to `ArrayAttr`
  tests/dialects/test_builtin.py
  xdsl/dialects/builtin.py
  xdsl/irdl.py
Labels: enhancement, API

#771 CI: Fix typo in CI
  .github/workflows/jupyterlite.yml
Labels: CI

#748 dialects: Move Addi.get to Addi.__init__.
  docs/database_example.ipynb
  docs/mlir_interoperation.ipynb
  docs/xdsl-introduction.ipynb
  tests/dialects/test_arith.py
  tests/dialects/test_cf.py
  tests/dialects/test_func.py
  tests/dialects/test_gpu.py
  tests/interpreters/test_pdl_interpreter.py
  tests/test_frontend_op_inserter.py
  tests/test_ir.py
  tests/test_pattern_rewriter.py
  tests/test_printer.py
  tests/test_rewriter.py
  xdsl/dialects/arith.py
  xdsl/frontend/dialects/arith.py
  xdsl/transforms/experimental/Apply1DMPIToStencil.py
  xdsl/transforms/experimental/ConvertStencilToLLMLIR.py
  xdsl/transforms/experimental/stencil_global_to_local.py
  xdsl/transforms/lower_mpi.py
Labels: dialects

#772 core: allow passing None for optional OpResult
  tests/test_operation_builder.py
  xdsl/irdl.py
Labels: core

#774 misc: Update README and remove .yapfignore after switching to black
  .yapfignore
  README.md
Labels: documentation, xdsl

#777 tests: Move arith tests to MLIR syntax
  tests/filecheck/dialects/arith/arith_attrs.mlir
  tests/filecheck/dialects/arith/arith_invalid.mlir
  tests/filecheck/dialects/arith/arith_invalid.xdsl
  tests/filecheck/dialects/arith/arith_ops.mlir
  tests/filecheck/dialects/arith/arith_ops.xdsl
Labels: tests

#778 tests: Move builtin tests to MLIR syntax
  tests/filecheck/dialects/builtin/attrs.mlir
  tests/filecheck/dialects/builtin/attrs.xdsl
  tests/filecheck/dialects/builtin/dense_array_invalid_dims.mlir
  tests/filecheck/dialects/builtin/dense_array_invalid_dims.xdsl
  tests/filecheck/dialects/builtin/dense_array_invalid_element.mlir
  tests/filecheck/dialects/builtin/dense_array_invalid_element.xdsl
  tests/filecheck/dialects/builtin/unrealized_conv_cast.mlir
  tests/filecheck/dialects/builtin/unrealized_conv_cast.xdsl
Labels: tests

#779 tests: Remove xdsl syntax from cf tests
  tests/filecheck/dialects/cf/cf_ops.xdsl
Labels: tests

#780 tests: Move cmath tests to MLIR syntax
  tests/filecheck/dialects/cmath/cmath_ops.mlir
  tests/filecheck/dialects/cmath/cmath_ops.xdsl
Labels: tests

#766 CI: Retrieve pyright version from requirements file
  .github/parse_pyright_version.py
  .github/workflows/ci-pyright-fails.yml
  .github/workflows/ci-pyright.yml
  requirements-optional.txt
Labels: CI

#783 tests: Move vector tests to MLIR format
  tests/filecheck/dialects/vector/vector_broadcast_type_matching.mlir
  tests/filecheck/dialects/vector/vector_broadcast_type_matching.xdsl
  tests/filecheck/dialects/vector/vector_createmask_indexing.mlir
  tests/filecheck/dialects/vector/vector_createmask_indexing.xdsl
  tests/filecheck/dialects/vector/vector_fma_res_acc_shape_matching.mlir
  tests/filecheck/dialects/vector/vector_fma_res_acc_shape_matching.xdsl
  tests/filecheck/dialects/vector/vector_fma_res_acc_type_matching.mlir
  tests/filecheck/dialects/vector/vector_fma_res_acc_type_matching.xdsl
  tests/filecheck/dialects/vector/vector_fma_res_lhs_shape_matching.mlir
  tests/filecheck/dialects/vector/vector_fma_res_lhs_shape_matching.xdsl
  tests/filecheck/dialects/vector/vector_fma_res_lhs_type_matching.mlir
  tests/filecheck/dialects/vector/vector_fma_res_lhs_type_matching.xdsl
  tests/filecheck/dialects/vector/vector_fma_res_rhs_shape_matching.mlir
  tests/filecheck/dialects/vector/vector_fma_res_rhs_shape_matching.xdsl
  tests/filecheck/dialects/vector/vector_fma_res_rhs_type_matching.mlir
  tests/filecheck/dialects/vector/vector_fma_res_rhs_type_matching.xdsl
  tests/filecheck/dialects/vector/vector_load_indexing.mlir
  tests/filecheck/dialects/vector/vector_load_indexing.xdsl
  tests/filecheck/dialects/vector/vector_load_type_matching.mlir
  tests/filecheck/dialects/vector/vector_load_type_matching.xdsl
  tests/filecheck/dialects/vector/vector_maskedload_indexing.mlir
  tests/filecheck/dialects/vector/vector_maskedload_indexing.xdsl
  tests/filecheck/dialects/vector/vector_maskedload_memref_passthrough_type_matching.mlir
  tests/filecheck/dialects/vector/vector_maskedload_memref_passthrough_type_matching.xdsl
  tests/filecheck/dialects/vector/vector_maskedload_memref_res_type_matching.mlir
  tests/filecheck/dialects/vector/vector_maskedload_memref_res_type_matching.xdsl
  tests/filecheck/dialects/vector/vector_maskedstore_indexing.mlir
  tests/filecheck/dialects/vector/vector_maskedstore_indexing.xdsl
  tests/filecheck/dialects/vector/vector_maskedstore_memref_storevec_type_matching.mlir
  tests/filecheck/dialects/vector/vector_maskedstore_memref_storevec_type_matching.xdsl
  tests/filecheck/dialects/vector/vector_ops.mlir
  tests/filecheck/dialects/vector/vector_ops.xdsl
  tests/filecheck/dialects/vector/vector_ops_mlir_conversion.xdsl
  tests/filecheck/dialects/vector/vector_store_indexing.mlir
  tests/filecheck/dialects/vector/vector_store_indexing.xdsl
  tests/filecheck/dialects/vector/vector_store_type_matching.mlir
  tests/filecheck/dialects/vector/vector_store_type_matching.xdsl
Labels: tests

#782 dialects: Remove IRDL dialect
  tests/dialects/test_irdl.py
  tests/filecheck/dialects/irdl/cmath.xdsl
  tests/filecheck/dialects/irdl/irdl_any_and_base_type.xdsl
  tests/filecheck/dialects/irdl/irdl_missing_operand.xdsl
  tests/filecheck/irdl-printer/any_and_base_type.xdsl
  tests/filecheck/irdl-printer/cmath_program.xdsl
  tests/xdsl_opt/test_xdsl_opt.py
  xdsl/dialects/irdl.py
  xdsl/xdsl_opt_main.py
Labels: dialects

#785 core: Hoist get_type_hint in from_pyrdl
  xdsl/irdl.py
Labels: core

#786 CI: Change CI name for better readability
  .github/workflows/code-formatting.yml
Labels: CI

#789 misc: lint test_xdsl_opt.py
  pyproject.toml
  tests/xdsl_opt/test_xdsl_opt.py
Labels: minor

#794 tests: migrate op builder tests to structural equivalence
  tests/test_op_builder.py
Labels: tests

#795 core: ModuleOp.ops, Region.ops and Block.ops are BlockOps
  tests/dialects/test_cf.py
  tests/dialects/test_func.py
  tests/dialects/test_gpu.py
  tests/dialects/test_scf.py
  tests/test_ir.py
  tests/test_linked_list.py
  tests/test_pattern_rewriter.py
  tests/test_printer.py
  tests/test_rewriter.py
  tests/test_use.py
  tests/xdsl_opt/test_xdsl_opt.py
  xdsl/dialects/builtin.py
  xdsl/dialects/func.py
  xdsl/dialects/gpu.py
  xdsl/dialects/scf.py
  xdsl/interpreters/experimental/pdl.py
  xdsl/ir.py
  xdsl/pattern_rewriter.py
  xdsl/rewriter.py
  xdsl/transforms/experimental/Apply1DMPIToStencil.py
Labels: core

#762 core: move Block.ops to a doubly-linked list structure
  tests/test_linked_list.py
  xdsl/ir.py
  xdsl/pattern_rewriter.py
  xdsl/rewriter.py
Labels: core

#799 frontend: Add support for If and IfExpr
  tests/filecheck/frontend/dialects/scf.py
  xdsl/frontend/code_generation.py
Labels: frontend

#803 tests: Move parser/printer tests to MLIR syntax
  tests/filecheck/dialects/llvm/example.mlir
  tests/filecheck/parser-printer/builtin_attrs.mlir
  tests/filecheck/parser-printer/builtin_types.xdsl
  tests/filecheck/parser-printer/escaped_characters.mlir
  tests/filecheck/parser-printer/escaped_characters.xdsl
  tests/filecheck/parser-printer/float_parsing.mlir
  tests/filecheck/parser-printer/float_parsing.xdsl
  tests/filecheck/parser-printer/region_name_clash.mlir
  tests/filecheck/parser-printer/region_name_clash.xdsl
  tests/filecheck/parser-printer/unregistered_affine.mlir
  tests/filecheck/parser-printer/unregistered_dialect.mlir
  tests/filecheck/parser-printer/unregistered_ops.xdsl
  tests/filecheck/parser-printer/value_tuple.mlir
  tests/filecheck/parser-printer/value_tuple_access_oob.mlir
  tests/filecheck/parser-printer/value_tuple_wrong_number.mlir
Labels: tests

#805 tests: move SCF test to MLIR syntax
  tests/filecheck/dialects/scf/scf_ops.mlir
  tests/filecheck/dialects/scf/scf_ops.xdsl
Labels: tests

#808 tests: Move desymref test to MLIR syntax
  tests/filecheck/frontend/passes/desymref.mlir
  tests/filecheck/frontend/passes/desymref.xdsl
Labels: tests

#807 tests: Move mlir_interoperation notebook test to MLIR syntax
  docs/mlir_interoperation.ipynb
  docs/source.mlir
  docs/source.xdsl
Labels: tests

#809 tests: Remove redundant tests using the xDSL syntax
  tests/filecheck/mlir-conversion/with-mlir/llvm_test.xdsl
  tests/filecheck/mlir-conversion/with-mlir/ops.xdsl
Labels: tests

#811 tests: Move some pytest tests to MLIR syntax
  tests/conftest.py
  tests/dialects/test_func.py
  tests/test_pattern_rewriter.py
  tests/test_printer.py
  tests/test_rewriter.py
Labels: tests

#801 dialects: Add cf.assert
  tests/dialects/test_cf.py
  tests/filecheck/dialects/cf/cf_ops.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/cf/assert.mlir
  xdsl/dialects/cf.py
Labels: dialects

#812 tests: Remove test that was already ported to MLIR syntax
  tests/filecheck/mlir-conversion/llvm_test.xdsl
Labels: tests

#787 core: remove inline_block_at_pos
  tests/test_pattern_rewriter.py
  tests/test_rewriter.py
  xdsl/pattern_rewriter.py
  xdsl/rewriter.py
Labels: minor, core

#823 core: replace Rewriter.insert_op_at_pos with start/end
  tests/test_pattern_rewriter.py
  xdsl/pattern_rewriter.py
  xdsl/transforms/lower_mpi.py
Labels: core
