Repository xdslproject/xdsl, pull requests merged in 2024-08, with the labels that each got.

#2963 transformations: lift arith to linalg named ops
  tests/filecheck/transforms/lift-arith-to-linalg.mlir
  xdsl/tools/command_line_tool.py
  xdsl/transforms/lift_arith_to_linalg.py
Labels: transformations

#2966 testing: (linalg-snitch) change order of incrementally added passes
  tests/transforms/test_test_lower_linalg_to_snitch.py
  xdsl/transforms/test_lower_linalg_to_snitch.py
Labels: testing

#2969 dialects: (arith, core) Constant op to accept tensor and memref
  tests/filecheck/dialects/arith/arith_ops.mlir
  xdsl/dialects/arith.py
  xdsl/dialects/builtin.py
  xdsl/parser/attribute_parser.py
Labels: bug, dialects

#2974 dialects: (tensor) Incorrect default 'dynamic index' on insert_slice op
  tests/dialects/test_tensor.py
  tests/filecheck/transforms/stencil-to-csl-stencil.mlir
  xdsl/dialects/tensor.py
Labels: dialects, minor

#2970 transform: (stencil-tensorize-z-dimension) Tensorize arith.constant directly
  tests/filecheck/transforms/stencil-tensorize-z-dimension.mlir
  xdsl/transforms/experimental/stencil_tensorize_z_dimension.py
Labels: minor, transformations

#2975 transformations: (stencil-tensorize-z-dim) Scaling z-shifts to avoid negative offsets
  tests/filecheck/transforms/stencil-tensorize-z-dimension.mlir
  tests/filecheck/transforms/stencil-to-csl-stencil.mlir
  xdsl/transforms/experimental/stencil_tensorize_z_dimension.py
  xdsl/transforms/stencil_to_csl_stencil.py
Labels: bug, minor, transformations

#2982 dialects: Enable bufferized stencil.apply
  tests/filecheck/dialects/csl/csl-stencil-ops.mlir
  tests/filecheck/dialects/stencil/invalid.mlir
  tests/filecheck/dialects/stencil/stencil_ops.mlir
  tests/filecheck/transforms/stencil-tensorize-z-dimension.mlir
  xdsl/dialects/stencil.py
Labels: dialects

#2984 transformations: Enable bufferized stencil lowering.
  tests/filecheck/transforms/convert-stencil-to-ll-mlir.mlir
  xdsl/transforms/experimental/convert_stencil_to_ll_mlir.py
Labels: minor, transformations

#2985 dialects: Add stencil features meant for bufferization
  tests/filecheck/dialects/stencil/invalid.mlir
  tests/filecheck/dialects/stencil/stencil_ops.mlir
  tests/filecheck/transforms/convert-stencil-to-ll-mlir.mlir
  tests/filecheck/transforms/distribute-stencil.mlir
  tests/filecheck/transforms/stencil-shape-inference.mlir
  xdsl/dialects/stencil.py
  xdsl/traits.py
  xdsl/transforms/canonicalization_patterns/stencil.py
Labels: dialects

#2983 transformations: First implementation of stencil-bufferize
  tests/filecheck/transforms/stencil-bufferize.mlir
  xdsl/dialects/stencil.py
  xdsl/tools/command_line_tool.py
  xdsl/transforms/canonicalization_patterns/stencil.py
  xdsl/transforms/dead_code_elimination.py
  xdsl/transforms/stencil_bufferize.py
Labels: transformations

#2986 bug: (snitch_stream) fix stride pattern repeat param parsing
  tests/filecheck/dialects/snitch_stream/ops.mlir
  xdsl/dialects/snitch_stream.py
Labels: bug

#2988 dialects: (riscv_snitch) add vfmax.s
  tests/filecheck/dialects/riscv_snitch/assembly_emission.mlir
  tests/filecheck/dialects/riscv_snitch/ops.mlir
  xdsl/dialects/riscv_snitch.py
Labels: dialects

#2995 (core) Support UnitAttr in assembly format
  tests/irdl/test_declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format_parser.py
Labels: core

#2994 dialects: (csl_stencil) Enable bufferized `csl_stencil.apply`
  tests/dialects/test_csl_stencil.py
  tests/filecheck/dialects/csl/csl-stencil-canonicalize.mlir
  tests/filecheck/dialects/csl/csl-stencil-ops.mlir
  tests/filecheck/transforms/csl-stencil-to-csl-wrapper.mlir
  tests/filecheck/transforms/stencil-to-csl-stencil.mlir
  xdsl/dialects/csl/csl_stencil.py
  xdsl/transforms/stencil_to_csl_stencil.py
Labels: dialects

#2987 core: implement EffectInstance
  xdsl/dialects/riscv.py
  xdsl/dialects/stencil.py
  xdsl/traits.py
  xdsl/transforms/canonicalization_patterns/stencil.py
  xdsl/transforms/common_subexpression_elimination.py
  xdsl/transforms/dead_code_elimination.py
  xdsl/transforms/stencil_bufferize.py
Labels: core

#3009 CI: don't run coverage by default in cmath conversion test
  tests/filecheck/dialects/irdl/pyrdl-to-irdl/cmath-conversion.py
Labels: CI

#3008 CI: add clean-caches make rule and remove *.cover files
  Makefile
Labels: CI

#3006 CI: update ruff precommit
  .pre-commit-config.yaml
Labels: CI

#3012 CI: include onnx interpreter for pyright
  pyproject.toml
  xdsl/interpreters/onnx.py
Labels: CI

#3010 CI: lint jupyter notebooks using ruff
  .pre-commit-config.yaml
  docs/Toy/Toy_Ch1.ipynb
  docs/Toy/Toy_Ch2.ipynb
  docs/mlir_interoperation.ipynb
  pyproject.toml
Labels: CI

#3005 misc: don't set pass spec arguments from instance when they are the default value
  tests/test_pass_to_spec.py
  xdsl/passes.py
Labels: misc

#3011 CI: remove isort from dev dependencies
  pyproject.toml
Labels: CI

#3003 misc: Add `Dialect.split_name` method
  tests/test_dialect_utils.py
  tests/test_parser_error.py
  tests/test_printer.py
  xdsl/context.py
  xdsl/dialects/riscv.py
  xdsl/dialects/x86/ops.py
  xdsl/interpreters/irdl.py
  xdsl/ir/core.py
Labels: testing, minor, misc

#3004 transformations: (csl_stencil) Add bufferization pass
  tests/filecheck/transforms/csl_stencil_bufferize.mlir
  xdsl/dialects/csl/csl_stencil.py
  xdsl/tools/command_line_tool.py
  xdsl/transforms/csl_stencil_bufferize.py
Labels: transformations

#3022 CI: move ruff line setting to only linting
  pyproject.toml
Labels: CI

#3023 CI: use ruff to format xdsl
  .pre-commit-config.yaml
  docs/Toy/toy/emulator/toy_accelerator_instruction_functions.py
  docs/Toy/toy/frontend/ir_gen.py
  docs/Toy/toy/frontend/location.py
  docs/Toy/toy/frontend/toy_ast.py
  docs/xdsl-introduction.ipynb
  pyproject.toml
  tests/backend/riscv/test_live_ins.py
  tests/backend/riscv/test_register_allocation.py
  tests/filecheck/dialects/irdl/cmath_irdl_loading.py
  tests/filecheck/dialects/irdl/cmath_irdl_stub.py
  tests/pattern_rewriter/test_pattern_rewriter.py
  tests/test_interpreter.py
  xdsl/backend/register_allocatable.py
  xdsl/backend/riscv/lowering/convert_memref_to_riscv.py
  xdsl/builder.py
  xdsl/dialects/experimental/dmp.py
  xdsl/dialects/experimental/fir.py
  xdsl/dialects/linalg.py
  xdsl/dialects/memref.py
  xdsl/dialects/memref_stream.py
  xdsl/dialects/onnx.py
  xdsl/dialects/stencil.py
  xdsl/dialects/tensor.py
  xdsl/dialects/utils.py
  xdsl/dialects/wasm/encoding.py
  xdsl/dialects/wasm/ops.py
  xdsl/dialects/wasm/wat.py
  xdsl/frontend/python_code_check.py
  xdsl/interactive/add_arguments_screen.py
  xdsl/interpreter.py
  xdsl/interpreters/experimental/wgpu.py
  xdsl/interpreters/irdl.py
  xdsl/interpreters/linalg.py
  xdsl/interpreters/memref_stream.py
  xdsl/interpreters/ml_program.py
  xdsl/interpreters/onnx.py
  xdsl/interpreters/tensor.py
  xdsl/ir/core.py
  xdsl/irdl/constraints.py
  xdsl/pattern_rewriter.py
  xdsl/transforms/common_subexpression_elimination.py
  xdsl/transforms/convert_memref_stream_to_loops.py
  xdsl/transforms/convert_onnx_to_linalg.py
  xdsl/transforms/experimental/convert_stencil_to_ll_mlir.py
  xdsl/transforms/memref_stream_generalize_fill.py
  xdsl/transforms/memref_stream_infer_fill.py
  xdsl/transforms/memref_stream_interleave.py
  xdsl/transforms/memref_stream_legalize.py
  xdsl/transforms/memref_stream_tile_outer_loops.py
  xdsl/transforms/memref_stream_unnest_out_parameters.py
  xdsl/transforms/scf_for_loop_flatten.py
  xdsl/transforms/stencil_bufferize.py
  xdsl/utils/comparisons.py
Labels: CI

#3024 core: Implement simple helpers for construct type access.
  tests/dialects/test_hw.py
  tests/dialects/test_linalg.py
  tests/dialects/test_pdl.py
  tests/irdl/test_operation_builder.py
  tests/pattern_rewriter/test_pattern_rewriter.py
  tests/test_ir.py
  xdsl/backend/riscv/lowering/convert_func_to_riscv_func.py
  xdsl/backend/riscv/lowering/convert_riscv_scf_to_riscv_cf.py
  xdsl/backend/riscv/lowering/convert_snitch_stream_to_snitch.py
  xdsl/dialects/affine.py
  xdsl/dialects/csl/csl.py
  xdsl/dialects/fsm.py
  xdsl/dialects/func.py
  xdsl/dialects/gpu.py
  xdsl/dialects/hw.py
  xdsl/dialects/pdl.py
  xdsl/ir/core.py
  xdsl/irdl/operations.py
  xdsl/printer.py
  xdsl/rewriting/composable_rewriting/immutable_ir/immutable_ir.py
  xdsl/transforms/common_subexpression_elimination.py
  xdsl/transforms/stencil_bufferize.py
  xdsl/transforms/stencil_to_csl_stencil.py
  xdsl/transforms/stencil_unroll.py
Labels: core

#3025 core: helpers for IRDL construct type access.
  tests/dialects/test_mpi_lowering.py
  xdsl/backend/riscv/lowering/convert_func_to_riscv_func.py
  xdsl/backend/riscv/lowering/convert_scf_to_riscv_scf.py
  xdsl/backend/riscv/register_allocation.py
  xdsl/dialects/affine.py
  xdsl/dialects/comb.py
  xdsl/dialects/csl/csl_stencil.py
  xdsl/dialects/csl/csl_wrapper.py
  xdsl/dialects/fsm.py
  xdsl/dialects/func.py
  xdsl/dialects/gpu.py
  xdsl/dialects/hw.py
  xdsl/dialects/linalg.py
  xdsl/dialects/memref.py
  xdsl/dialects/memref_stream.py
  xdsl/dialects/snitch_stream.py
  xdsl/dialects/stencil.py
  xdsl/irdl/declarative_assembly_format.py
  xdsl/irdl/operations.py
  xdsl/transforms/csl_stencil_bufferize.py
  xdsl/transforms/lower_mpi.py
  xdsl/transforms/reconcile_unrealized_casts.py
  xdsl/transforms/stencil_bufferize.py
Labels: core

#3020 dialects: (stablehlo) Add initial contribution for stablehlo dialect
  tests/filecheck/dialects/stablehlo/test.mlir
  xdsl/dialects/__init__.py
  xdsl/dialects/stablehlo.py
Labels: dialects

#3029 misc: make some pyright ignores more specific [NFC]
  xdsl/interactive/_pasteboard.py
  xdsl/interpreters/experimental/wgpu.py
Labels: minor, misc

#3032 misc: remove mentions of black formatter
  .git-blame-ignored-commits
  .github/workflows/code-formatting.yml
  Makefile
  README.md
  pyproject.toml
Labels: misc

#3030 dialects: (stablehlo) add elementwise add, sub, mul
  tests/filecheck/dialects/stablehlo/ops.mlir
  tests/filecheck/dialects/stablehlo/test.mlir
  xdsl/dialects/stablehlo.py
Labels: dialects

#3035 interpreter: fix int64 format in ptr dtypes
  tests/interpreters/test_ptr.py
  xdsl/interpreters/ptr.py
Labels: bug, interpreter

#3002 dialects: (irdl) Update for mlir compatibility
  tests/dialects/test_irdl.py
  tests/filecheck/dialects/irdl/pyrdl-to-irdl/cmath-conversion.py
  tests/filecheck/dialects/irdl/testd.irdl.mlir
  xdsl/dialects/irdl/irdl.py
  xdsl/dialects/irdl/pyrdl_to_irdl.py
Labels: dialects, testing

#3031 dialects: (stablehlo) add transpose
  tests/filecheck/dialects/stablehlo/invalid.mlir
  tests/filecheck/dialects/stablehlo/ops.mlir
  xdsl/dialects/stablehlo.py
Labels: dialects

#3028 transformations: Add linalg-to-csl pass
  tests/filecheck/transforms/linalg-to-csl.mlir
  xdsl/dialects/csl/csl.py
  xdsl/tools/command_line_tool.py
  xdsl/transforms/linalg_to_csl.py
Labels: transformations

#2617 core: Add `BitEnumAttribute`
  tests/irdl/test_attribute_definition.py
  xdsl/dialects/llvm.py
  xdsl/ir/core.py
Labels: help wanted

#3037 dependencies: add JAX as an optional dependency of xDSL
  README.md
  pyproject.toml
  requirements.txt
Labels: dependencies

#3040 core: CanonicaliZation naming consistency
  docs/Toy/toy/dialects/toy.py
  xdsl/dialects/arith.py
  xdsl/dialects/csl/csl_stencil.py
  xdsl/dialects/memref.py
  xdsl/dialects/memref_stream.py
  xdsl/dialects/riscv.py
  xdsl/dialects/riscv_cf.py
  xdsl/dialects/riscv_snitch.py
  xdsl/dialects/scf.py
  xdsl/dialects/stencil.py
  xdsl/traits.py
  xdsl/transforms/canonicalize.py
  xdsl/transforms/individual_rewrite.py
Labels: minor, core

#3044 core: Improved treatment of whitespace in assembly format
  tests/dialects/test_stencil.py
  tests/filecheck/dialects/csl/csl-stencil-canonicalize.mlir
  tests/filecheck/dialects/csl/csl-stencil-ops.mlir
  tests/filecheck/dialects/stencil/canonicalize.mlir
  tests/filecheck/dialects/stencil/oec-kernels/fvtp2d_qi.mlir
  tests/filecheck/dialects/stencil/stencil_ops.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/stencil/ops.mlir
  tests/filecheck/transforms/csl-stencil-to-csl-wrapper.mlir
  tests/filecheck/transforms/distribute-stencil.mlir
  tests/filecheck/transforms/stencil-shape-inference.mlir
  tests/filecheck/transforms/stencil-storage-materialization.mlir
  tests/filecheck/transforms/stencil-tensorize-z-dimension.mlir
  tests/filecheck/transforms/stencil-to-csl-stencil.mlir
  tests/filecheck/transforms/stencil-unroll.mlir
  tests/irdl/test_declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format_parser.py
Labels: testing, xdsl, core

#3048 misc: Fix typo achorable -> anchorable
  tests/irdl/test_declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format_parser.py
Labels: minor, misc

#3039 dependencies: update ruff-pre-commit to v0.6.0
  .pre-commit-config.yaml
  tests/interactive/test_app.py
Labels: dependencies

#3001 transformations: stencil bufferization polish
  tests/filecheck/dialects/stencil/oec-kernels/fvtp2d_qi.mlir
  tests/filecheck/transforms/stencil-bufferize.mlir
  xdsl/dialects/stencil.py
  xdsl/transforms/canonicalization_patterns/stencil.py
  xdsl/transforms/stencil_bufferize.py
Labels: transformations

#3046 transformations: stencil shape inference polish
  tests/filecheck/transforms/stencil-shape-inference.mlir
  xdsl/transforms/experimental/stencil_shape_inference.py
Labels: transformations

#3047 transformations: Implement `shape-inference` pass
  tests/filecheck/dialects/stencil/oec-kernels/fvtp2d_qi.mlir
  tests/filecheck/transforms/stencil-shape-inference.mlir
  tests/xdsl_opt/test_xdsl_opt.py
  xdsl/dialects/stencil.py
  xdsl/tools/command_line_tool.py
  xdsl/traits.py
  xdsl/transforms/experimental/dmp/stencil_global_to_local.py
  xdsl/transforms/shape_inference.py
  xdsl/transforms/shape_inference_patterns/stencil.py
Labels: core, transformations

#3045 rewriting: Make `modify_block_argument_type` `modify_value_type`
  tests/pattern_rewriter/test_pattern_rewriter.py
  xdsl/pattern_rewriter.py
  xdsl/transforms/convert_memref_stream_to_snitch_stream.py
  xdsl/transforms/experimental/hls_convert_stencil_to_ll_mlir.py
  xdsl/transforms/memref_stream_legalize.py
  xdsl/transforms/shape_inference_patterns/stencil.py
Labels: minor, rewriting

#3052 CI: update pre-commit-hooks
  .pre-commit-config.yaml
Labels: CI

#3053 CI: add end of file and end of line pre-commit hooks
  .pre-commit-config.yaml
  tests/filecheck/backend/convert_riscv_scf_to_riscv_cf_with_regalloc.mlir
  tests/filecheck/backend/riscv/convert_arith_to_riscv_snitch.mlir
  tests/filecheck/dialects/accfg/accfg_ops.mlir
  tests/filecheck/dialects/memref_stream/canonicalize.mlir
  tests/filecheck/dialects/quantum/attrs.mlir
  tests/filecheck/dialects/riscv_scf/loop_range_folding.mlir
  tests/filecheck/dialects/riscv_snitch/ops.mlir
  tests/filecheck/dialects/riscv_snitch/verification.mlir
  tests/filecheck/dialects/snitch_stream/convert_snitch_stream_to_snitch.mlir
  tests/filecheck/dialects/tensor/ops.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/linalg/invalid_ops.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/linalg/ops.mlir
  tests/filecheck/projects/riscv-backend-paper/ddot_regalloc.mlir
  tests/filecheck/transforms/arith-add-immediate-zero.mlir
  tests/filecheck/transforms/arith-individual-rewrite-patterns-DivisionOfSameVariableToOne.mlir
  tests/filecheck/transforms/convert_onnx_to_linalg.mlir
  tests/filecheck/transforms/convert_qref_to_qssa.mlir
  tests/filecheck/transforms/convert_qssa_to_qref.mlir
  xdsl/dialects/cmath.irdl
Labels: CI

#3059 installation: Update nix flake
  flake.lock
  flake.nix
Labels: installation, minor

#3049 dialect: (irdl) Add region and attributes operations
  tests/filecheck/dialects/irdl/testd.irdl.mlir
  xdsl/dialects/irdl/irdl.py
Labels: dialects, testing

#3015 dialects: (Transform) Add new selecting operations
  tests/dialects/test_transform.py
  tests/filecheck/dialects/transform/transform_types.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/transform/transform_types.mlir
  xdsl/dialects/transform.py
Labels: dialects

#3062 dependencies: fix numpy version for subprojects that depend on it
  pyproject.toml
  xdsl/interpreters/onnx.py
Labels: bug, dependencies, CI

#3016 transformations: update stencil lowering to properly accomodate bufferized stencils.
  tests/filecheck/transforms/convert-stencil-to-ll-mlir.mlir
  xdsl/transforms/experimental/convert_stencil_to_ll_mlir.py
Labels: transformations

#3051 transformations: (csl-stencil-to-csl-wrapper) Translate func args to exportable memref.global
  tests/dialects/test_csl_wrapper.py
  tests/filecheck/transforms/csl-stencil-to-csl-wrapper.mlir
  xdsl/dialects/csl/csl_wrapper.py
  xdsl/transforms/csl_stencil_to_csl_wrapper.py
Labels: transformations

#3050 dialects: dmp: make strategies attributes and carry them in IR
  tests/dialects/test_dmp.py
  tests/filecheck/dialects/dmp/canonicalize.mlir
  tests/filecheck/dialects/dmp/ops.mlir
  tests/filecheck/transforms/distribute-stencil.mlir
  tests/filecheck/transforms/stencil-to-csl-stencil.mlir
  xdsl/dialects/experimental/dmp.py
  xdsl/transforms/canonicalize_dmp.py
  xdsl/transforms/experimental/dmp/decompositions.py
  xdsl/transforms/experimental/dmp/stencil_global_to_local.py
  xdsl/transforms/stencil_to_csl_stencil.py
Labels: dialects, transformations

#3054 transformations: Decouple `distribute-stencil` from `shape-inference`
  tests/filecheck/transforms/distribute-stencil.mlir
  xdsl/dialects/experimental/dmp.py
  xdsl/transforms/experimental/dmp/stencil_global_to_local.py
  xdsl/transforms/shape_inference_patterns/dmp.py
Labels: dialects, transformations

#3056 dialects: Update dmp.swap
  tests/filecheck/dialects/dmp/canonicalize.mlir
  tests/filecheck/dialects/dmp/ops.mlir
  tests/filecheck/transforms/distribute-stencil.mlir
  tests/filecheck/transforms/stencil-to-csl-stencil.mlir
  xdsl/dialects/csl/csl_stencil.py
  xdsl/dialects/experimental/dmp.py
  xdsl/transforms/canonicalize_dmp.py
  xdsl/transforms/experimental/dmp/stencil_global_to_local.py
  xdsl/transforms/shape_inference_patterns/dmp.py
  xdsl/transforms/stencil_to_csl_stencil.py
Labels: dialects, transformations

#3063 transformations: Tensorize new result of `dmp.swap`
  tests/filecheck/transforms/stencil-tensorize-z-dimension.mlir
  xdsl/dialects/experimental/dmp.py
  xdsl/transforms/experimental/stencil_tensorize_z_dimension.py
Labels: minor, transformations

#3066 transformations: Enable dmp.swap stencil bufferization.
  tests/filecheck/transforms/distribute-stencil.mlir
  xdsl/dialects/experimental/dmp.py
  xdsl/transforms/stencil_bufferize.py
Labels: dialects, transformations

#3068 transformations: (stencil-to-csl-stencil) Support also bufferized `dmp.swap`
  tests/filecheck/transforms/stencil-to-csl-stencil.mlir
  xdsl/transforms/stencil_to_csl_stencil.py
Labels: minor, transformations

#3069 dialects: Update `tensor` side-effect traits
  tests/filecheck/transforms/stencil-bufferize.mlir
  xdsl/dialects/tensor.py
  xdsl/transforms/stencil_bufferize.py
Labels: dialects, minor

#3072 transformations: Forgotten xdsl/transforms/shape_inference_patterns/__init__.py
  xdsl/transforms/shape_inference_patterns/__init__.py
Labels: minor, transformations

#3073 transformations: Enable bufferized `dmp.swap` lowering.
  xdsl/transforms/experimental/dmp/stencil_global_to_local.py
Labels: transformations

#3057 backend: (JAX) add export to JAX executable
  tests/backend/test_jax_executable.py
  xdsl/backend/jax_executable.py
Labels: backend

#3067 core: Implement IRDL SameSize options
  tests/irdl/test_operation_builder.py
  tests/irdl/test_operation_definition.py
  xdsl/irdl/operations.py
Labels: core

#3058 backend: (JAX) add some syntax sugar for typed compiled functions
  tests/backend/test_jax_executable.py
  xdsl/backend/jax_executable.py
Labels: backend

#3070 dialects: Update dialects with SameSize IRDL options.
  tests/filecheck/dialects/memref/memref_ops.mlir
  xdsl/dialects/memref.py
Labels: dialects, minor

#3074 CI: Python 3.12
  .github/workflows/ci-core.yml
  .github/workflows/ci-mlir.yml
  .github/workflows/ci-notebooks.yml
  .github/workflows/ci-pyright-fails.yml
  asv.conf.json
Labels: CI

#3071 dialects: stencil: Allow loading and storing from a same field.
  tests/dialects/test_stencil.py
  tests/filecheck/transforms/convert-stencil-to-ll-mlir.mlir
  xdsl/dialects/stencil.py
  xdsl/transforms/experimental/convert_stencil_to_ll_mlir.py
Labels: dialects, transformations

#3076 transformations: `stencil-bufferize` side-effect analysis fix
  tests/filecheck/transforms/stencil-bufferize.mlir
  xdsl/dialects/stencil.py
  xdsl/transforms/stencil_bufferize.py
Labels: bug, minor, transformations

#3081 dialects: (stablehlo) Add support for andOp
  tests/filecheck/dialects/stablehlo/ops.mlir
  xdsl/dialects/stablehlo.py
Labels: dialects

#3079 dialects: (transform) Add structured match operation
  tests/dialects/test_transform.py
  tests/filecheck/dialects/transform/transform_types.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/transform/transform_types.mlir
  xdsl/dialects/transform.py
Labels: dialects

#3085 dialects: (stablehlo) Add support for returnOp
  tests/filecheck/dialects/stablehlo/ops.mlir
  xdsl/dialects/stablehlo.py
Labels: dialects

#3088 bug: remove duplicate isattr definition
  xdsl/transforms/csl_stencil_bufferize.py
  xdsl/utils/isa.py
  xdsl/utils/isattr.py
Labels: bug

#3089 dialects: (stablehlo) add stablehlo.precision
  tests/filecheck/dialects/stablehlo/attrs.mlir
  xdsl/dialects/stablehlo.py
Labels: dialects

#3093 dialects: (stablehlo) add stablehlo.token
  tests/filecheck/dialects/stablehlo/attrs.mlir
  xdsl/dialects/stablehlo.py
Labels: dialects

#3080 dialects: (transform) Fix amount of returned loops in TileOp
  tests/dialects/test_transform.py
  xdsl/dialects/transform.py
Labels: dialects

#3038 frontend: (stablehlo) add ir generation from jaxpr
  tests/frontend/jaxpr/test_build_jaxpr_ir.py
  tests/frontend/onnx/test_build_onnx_ir.py
  xdsl/frontend/jaxpr/__init__.py
Labels: frontend

#3100 dialects: (stablehlo) add stablehlo.bitcast_convert
  tests/filecheck/dialects/stablehlo/ops.mlir
  xdsl/dialects/stablehlo.py
Labels: dialects

#3098 ci: Enable pip caching
  .github/workflows/ci-core.yml
  .github/workflows/ci-mlir.yml
  .github/workflows/ci-notebooks.yml
  .github/workflows/ci-pyright-fails.yml
  .github/workflows/code-formatting.yml
  .github/workflows/jupyterlite.yml
  .github/workflows/pythonpublish.yml
Labels: CI

#3084 transformations: (csl-stencil-bufferize) Fold `csl_stencil.access` that have no effect
  tests/filecheck/transforms/csl_stencil_bufferize.mlir
  xdsl/dialects/csl/csl_stencil.py
  xdsl/transforms/csl_stencil_bufferize.py
Labels: minor, transformations

#3095 dialects: (stablehlo) add stablehlo.case
  tests/filecheck/dialects/stablehlo/ops.mlir
  xdsl/dialects/stablehlo.py
Labels: dialects

#3104 dialects: (stablehlo) add stablehlo.after_all
  tests/filecheck/dialects/stablehlo/ops.mlir
  xdsl/dialects/stablehlo.py
Labels: dialects

#3102 core: Implement speculability trait and helper.
  tests/test_traits.py
  xdsl/traits.py
Labels: minor, core

#3103 transformations: Implement `control-flow-hoist`
  tests/filecheck/mlir-conversion/with-mlir/control_flow_hoist_collab.mlir
  xdsl/dialects/affine.py
  xdsl/dialects/arith.py
  xdsl/dialects/scf.py
  xdsl/ir/affine/affine_set.py
  xdsl/tools/command_line_tool.py
  xdsl/transforms/control_flow_hoist.py
Labels: transformations

#3077 transformations: Support safe inplace stencil bufferization.
  tests/filecheck/transforms/stencil-bufferize.mlir
  xdsl/transforms/stencil_bufferize.py
Labels: transformations

#3092 transformations: Translate memref to dsd
  tests/filecheck/backend/csl/print_csl.mlir
  tests/filecheck/transforms/memref-to-dsd.mlir
  xdsl/backend/csl/print_csl.py
  xdsl/dialects/csl/csl.py
  xdsl/tools/command_line_tool.py
  xdsl/transforms/memref_to_dsd.py
Labels: transformations

#3101 transformations: (csl-stencil-to-csl-wrapper) Generate symbol export and no memref.globals
  tests/filecheck/transforms/csl-stencil-to-csl-wrapper.mlir
  xdsl/dialects/csl/csl.py
  xdsl/transforms/csl_stencil_to_csl_wrapper.py
Labels: transformations

#3090 dialects: (stablehlo) add stablehlo.dot
  tests/filecheck/dialects/stablehlo/attrs.mlir
  xdsl/dialects/stablehlo.py
Labels: dialects

#3111 backend: (riscv) print list of registers to regalloc stats
  tests/backend/riscv/test_register_allocation.py
  tests/filecheck/backend/riscv/register-allocation/preallocated.mlir
  tests/filecheck/projects/riscv-backend-paper/bottom_up.mlir
  tests/filecheck/projects/riscv-backend-paper/nsnet.mlir
  xdsl/backend/riscv/register_allocation.py
Labels: backend

#3108 fix: Param names were not correctly referenced in the printer
  tests/filecheck/backend/csl/print_csl.mlir
  xdsl/backend/csl/print_csl.py
Labels: backend

#3112 bug: (csl-stencil-to-csl-wrapper) Reverse generated operands
  tests/filecheck/transforms/csl-stencil-to-csl-wrapper.mlir
  xdsl/dialects/csl/csl_wrapper.py
  xdsl/transforms/csl_stencil_to_csl_wrapper.py
Labels: minor, transformations

#3042 dialects: (stim) initialise dialect
  tests/dialects/stim/test_stim_printer_parser.py
  tests/filecheck/dialects/stim/stim_ops.mlir
  xdsl/dialects/__init__.py
  xdsl/dialects/stim/__init__.py
  xdsl/dialects/stim/ops.py
  xdsl/dialects/stim/stim_printer_parser.py
Labels: dialects

#3119 CI: update ruff precommit
  .pre-commit-config.yaml
Labels: CI

#3121 dialects: (riscv) canonize x ^ x = 0
  tests/filecheck/backend/riscv/canonicalize.mlir
  xdsl/dialects/riscv.py
  xdsl/transforms/canonicalization_patterns/riscv.py
Labels: dialects

#3106 core: (irdl) Add support for regions in optional groups to declarative assembly format
  tests/irdl/test_declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format_parser.py
Labels: minor, core
