Repository xdslproject/xdsl, pull requests merged in 2024-09, with the labels that each got.

#3125 tests: Increase timeout on lit tests
  Makefile
Labels: bug, testing

#3124 core: Add successors to assembly format
  tests/irdl/test_declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format_parser.py
Labels: xdsl, core

#3127 dialects: Add NoMemoryEffect trait in various LLVM and builtin ops
  xdsl/dialects/builtin.py
  xdsl/dialects/llvm.py
Labels: invalid, dialects

#3131 transforms: Fix constant pinning breaking for external functions
  tests/filecheck/transforms/function-constant-pinning.mlir
  xdsl/transforms/experimental/function_constant_pinning.py
Labels: transformations

#3123 core: Assembly format shouldn't require `$*SegmentSizes`
  tests/irdl/test_declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format_parser.py
Labels: bug, minor, core

#3118 transformations: (stencil-tensorize-z-dim) Support loops
  tests/filecheck/transforms/stencil-tensorize-z-dimension.mlir
  xdsl/transforms/experimental/stencil_tensorize_z_dimension.py
Labels: transformations

#3120 misc: remove type annotations from operand definitions [NFC]
  docs/Toy/Toy_Ch2.ipynb
  docs/Toy/toy/dialects/toy.py
  docs/database_example.ipynb
  docs/irdl.ipynb
  docs/xdsl-introduction.ipynb
  remove_annotated.sed
  tests/dialects/test_mpi_lowering.py
  tests/irdl/test_operation_builder.py
  tests/irdl/test_operation_definition.py
  tests/test_builtin_traits.py
  tests/test_ir.py
  tests/test_parser.py
  tests/test_parser_error.py
  tests/test_printer.py
  tests/test_ssa_value.py
  tests/test_traits.py
  xdsl/dialects/affine.py
  xdsl/dialects/arith.py
  xdsl/dialects/builtin.py
  xdsl/dialects/cf.py
  xdsl/dialects/comb.py
  xdsl/dialects/csl/csl.py
  xdsl/dialects/csl/csl_wrapper.py
  xdsl/dialects/experimental/aie.py
  xdsl/dialects/experimental/dmp.py
  xdsl/dialects/experimental/fir.py
  xdsl/dialects/experimental/hlfir.py
  xdsl/dialects/experimental/hls.py
  xdsl/dialects/experimental/math.py
  xdsl/dialects/fsm.py
  xdsl/dialects/func.py
  xdsl/dialects/gpu.py
  xdsl/dialects/hw.py
  xdsl/dialects/irdl/irdl.py
  xdsl/dialects/linalg.py
  xdsl/dialects/llvm.py
  xdsl/dialects/memref.py
  xdsl/dialects/memref_stream.py
  xdsl/dialects/mpi.py
  xdsl/dialects/pdl.py
  xdsl/dialects/printf.py
  xdsl/dialects/qref.py
  xdsl/dialects/qssa.py
  xdsl/dialects/riscv.py
  xdsl/dialects/riscv_cf.py
  xdsl/dialects/riscv_func.py
  xdsl/dialects/riscv_scf.py
  xdsl/dialects/riscv_snitch.py
  xdsl/dialects/scf.py
  xdsl/dialects/seq.py
  xdsl/dialects/snitch.py
  xdsl/dialects/snitch_runtime.py
  xdsl/dialects/stencil.py
  xdsl/dialects/stream.py
  xdsl/dialects/tensor.py
  xdsl/dialects/test.py
  xdsl/dialects/vector.py
  xdsl/dialects/x86/ops.py
  xdsl/frontend/symref.py
Labels: misc

#3136 dialects: (csl) Add `direction` type
  tests/filecheck/backend/csl/print_csl.mlir
  tests/filecheck/dialects/csl/ops.mlir
  xdsl/backend/csl/print_csl.py
  xdsl/dialects/csl/csl.py
Labels: dialects, minor

#3107 transformations: from `csl_wrapper` to `csl` modules
  tests/filecheck/transforms/csl_wrapper_to_csl.mlir
  xdsl/dialects/csl/csl.py
  xdsl/tools/command_line_tool.py
  xdsl/transforms/csl_wrapper_to_csl.py
Labels: transformations

#3132 dialects: (cf) Custom Parsing and assert change
  tests/dialects/test_cf.py
  tests/filecheck/dialects/cf/cf_ops.mlir
  tests/filecheck/frontend/dialects/cf.py
  tests/filecheck/transforms/cse.mlir
  tests/filecheck/transforms/reconcile_unrealized_casts.mlir
  xdsl/dialects/cf.py
Labels: dialects, testing

#3138 dialects: (scf) make iteration variable type explicit
  tests/filecheck/backend/csl/print_csl.mlir
  tests/filecheck/dialects/scf/scf_ops.mlir
  tests/filecheck/projects/riscv-backend-paper/bottom_up.mlir
  tests/filecheck/transforms/convert_memref_stream_to_snitch_stream.mlir
  xdsl/dialects/scf.py
Labels: dialects, testing

#3134 transformations: Add pass to lower csl-stencil dialect
  tests/filecheck/transforms/lower-csl-stencil.mlir
  tests/filecheck/transforms/memref-to-dsd.mlir
  xdsl/dialects/csl/csl.py
  xdsl/tools/command_line_tool.py
  xdsl/transforms/lower_csl_stencil.py
  xdsl/transforms/memref_to_dsd.py
Labels: transformations

#3137 transformations: Lower `csl_wrapper.import` to `csl.import`
  tests/filecheck/transforms/csl_wrapper_to_csl.mlir
  xdsl/dialects/csl/csl.py
  xdsl/dialects/csl/csl_wrapper.py
  xdsl/transforms/csl_wrapper_to_csl.py
Labels: transformations

#3139 backend: (csl) Add comparison operators to CSL
  tests/filecheck/backend/csl/print_csl.mlir
  xdsl/backend/csl/print_csl.py
Labels: backend

#3147 dialects: llvm.InLineAsmOp has_side_effects, is_align_stack are properties
  tests/filecheck/dialects/llvm/inline_asm.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/llvm/inline_asm.mlir
  xdsl/dialects/llvm.py
Labels: dialects

#3152 backend: (csl) Don't use CSL keywords as var names
  tests/filecheck/backend/csl/print_csl.mlir
  xdsl/backend/csl/print_csl.py
Labels: backend

#3149 fix: Add the missing call to `@set_rectangle`
  tests/filecheck/transforms/csl_wrapper_to_csl.mlir
  xdsl/transforms/csl_wrapper_to_csl.py
Labels: transformations

#3165 transformations: Add new csl-wrapper-hoist-buffers pass
  tests/filecheck/transforms/csl-wrapper-hoist-buffers.mlir
  xdsl/tools/command_line_tool.py
  xdsl/transforms/csl_wrapper_hoist_buffers.py
Labels: transformations

#3166 Revert "pip prod(deps): bump jax from 0.4.31 to 0.4.32 (#3161)"
  pyproject.toml
Labels: CI

#3153 transformation: Scf to cf lowering
  tests/filecheck/transforms/convert-scf-to-cf.mlir
  xdsl/tools/command_line_tool.py
  xdsl/transforms/convert_scf_to_cf.py
Labels: testing, transformations

#3156 dialects: (cf) add switch
  tests/filecheck/dialects/cf/cf_ops.mlir
  xdsl/dialects/cf.py
Labels: dialects, testing

#3175 dialects: (eqsat) add dialect and create new eclass op
  tests/filecheck/dialects/eqsat/eqsat_ops.mlir
  xdsl/dialects/__init__.py
  xdsl/dialects/eqsat.py
Labels: dialects

#3178 dialects: (scf) small refactor for index_switch
  xdsl/dialects/scf.py
Labels: dialects, minor, misc

#3181 misc: remove redundant `AnyAttr()` constraints from op definitions [NFC]
  docs/Toy/toy/dialects/toy.py
  tests/test_parser_error.py
  xdsl/dialects/affine.py
  xdsl/dialects/experimental/aie.py
  xdsl/dialects/experimental/air.py
  xdsl/dialects/experimental/hls.py
  xdsl/dialects/fsm.py
  xdsl/dialects/hw.py
  xdsl/dialects/vector.py
  xdsl/frontend/symref.py
Labels: misc

#3182 misc: raise instead of returning error in MemrefLayoutAttr.get_affine_map
  xdsl/dialects/builtin.py
Labels: misc

#3184 fix: various minor fixes for the csl variables
  xdsl/dialects/csl/csl.py
Labels: dialects

#3191 dialects: (csl) add `csl.activate`
  tests/filecheck/backend/csl/print_csl.mlir
  tests/filecheck/dialects/csl/ops.mlir
  xdsl/backend/csl/print_csl.py
  xdsl/dialects/csl/csl.py
Labels: dialects

#3188 dialects: (tosa) turn attributes into properties
  tests/filecheck/dialects/tosa/ops.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/tosa/ops.mlir
  xdsl/dialects/tosa.py
Labels: dialects

#3197 dialects: (riscv) Add rewrite pattern to optimize bitwise xor by zero
  GETTING_STARTED.md
  tests/filecheck/backend/riscv/canonicalize.mlir
  xdsl/dialects/riscv.py
  xdsl/transforms/canonicalization_patterns/riscv.py
Labels: dialects

#3192 transformations: (csl-stencil) Add pass to handle async ops and enclosing cf
  tests/filecheck/transforms/csl-stencil-handle-async-flow.mlir
  xdsl/dialects/csl/csl.py
  xdsl/tools/command_line_tool.py
  xdsl/transforms/csl_stencil_handle_async_flow.py
Labels: transformations

#3198 transformations: (csl-stencil-to-csl-wrapper) Add `unblock_cmd_stream` call
  tests/filecheck/transforms/csl-stencil-to-csl-wrapper.mlir
  xdsl/transforms/csl_stencil_to_csl_wrapper.py
Labels: minor, transformations

#3201 bug: (csl-stencil-handle-async-flow) Increment counter correctly
  tests/filecheck/transforms/csl-stencil-handle-async-flow.mlir
  xdsl/transforms/csl_stencil_handle_async_flow.py
Labels: bug, minor

#3199 backend: (csl) added arith.select to csl backend
  tests/filecheck/backend/csl/print_csl.mlir
  xdsl/backend/csl/print_csl.py
Labels: backend

#3203 transformations: (lower-csl-stencil) Store results to apply.dest
  tests/filecheck/transforms/lower-csl-stencil.mlir
  xdsl/transforms/lower_csl_stencil.py
Labels: minor, transformations

#3202 backend: (csl) allow `get_dir` to be inlined
  tests/filecheck/backend/csl/print_csl.mlir
  xdsl/backend/csl/print_csl.py
Labels: minor, backend

#3207 bug: Print csl namehint fix
  xdsl/backend/csl/print_csl.py
Labels: bug, minor

#3204 enhancement: Changing names and namehints in the csl pipeline
  tests/filecheck/transforms/convert-stencil-to-csl-stencil.mlir
  tests/filecheck/transforms/lower-csl-stencil.mlir
  tests/filecheck/transforms/lower-csl-wrapper.mlir
  xdsl/dialects/csl/csl_stencil.py
  xdsl/tools/command_line_tool.py
  xdsl/transforms/canonicalization_patterns/csl_stencil.py
  xdsl/transforms/convert_stencil_to_csl_stencil.py
  xdsl/transforms/csl_stencil_bufferize.py
  xdsl/transforms/csl_stencil_handle_async_flow.py
  xdsl/transforms/csl_stencil_to_csl_wrapper.py
  xdsl/transforms/lower_csl_stencil.py
  xdsl/transforms/lower_csl_wrapper.py
Labels: enhancement, help wanted

#3179 transformations: (scf-to-cf) add lowering for index_switch
  tests/filecheck/transforms/convert-scf-to-cf.mlir
  xdsl/transforms/convert_scf_to_cf.py
Labels: testing, transformations

#3208 transformations: Add CSL dsd canonicalisation
  tests/filecheck/dialects/csl/csl-canonicalize.mlir
  xdsl/dialects/csl/csl.py
  xdsl/transforms/canonicalization_patterns/csl.py
Labels: transformations

#3209 fix: (csl) adjusted width and height of the PE
  tests/filecheck/transforms/csl-stencil-to-csl-wrapper.mlir
  xdsl/transforms/csl_stencil_to_csl_wrapper.py
Labels: minor, transformations

#3078 transformations: (licm) add `can_be_hoisted` helper function
  tests/transforms/test_loop_invariant_code_motion.py
  xdsl/transforms/loop_invariant_code_motion.py
Labels: transformations

#3223 transformations: (lower-csl-stencil) Send only core data
  tests/filecheck/transforms/lower-csl-stencil.mlir
  xdsl/transforms/lower_csl_stencil.py
Labels: minor, transformations

#3114 dialects: (stim) add qubit attribute and qubit coordinate attribute
  tests/dialects/stim/test_stim_printer_parser.py
  tests/filecheck/dialects/stim/attrs.mlir
  xdsl/dialects/stim/__init__.py
  xdsl/dialects/stim/ops.py
  xdsl/dialects/stim/stim_printer_parser.py
Labels: dialects

#3222 transformations: New csl-stencil-materialize-stores pass
  tests/filecheck/transforms/csl-stencil-materialize-stores.mlir
  tests/filecheck/transforms/lower-csl-stencil.mlir
  xdsl/tools/command_line_tool.py
  xdsl/transforms/csl_stencil_materialize_stores.py
  xdsl/transforms/lower_csl_stencil.py
Labels: transformations
