Repository xdslproject/xdsl, pull requests merged in 2024-06, with the labels that each got.

#2661 transformations: linalg.generic to loops uses InsertPoint
  xdsl/transforms/convert_linalg_to_loops.py
  xdsl/transforms/convert_memref_stream_to_loops.py
  xdsl/transforms/loop_nest_lowering_utils.py
Labels: transformations

#2680 dialects: (memref_stream) add a verifier for order of iterator types in memref_stream.generic
  tests/filecheck/dialects/memref_stream/verify.mlir
  xdsl/dialects/memref_stream.py
Labels: dialects

#2675 core: implement RangeConstraint and use it without functional change
  tests/filecheck/dialects/scf/parallel_multiple_blocks.mlir
  xdsl/dialects/irdl/pyrdl_to_irdl.py
  xdsl/irdl/declarative_assembly_format.py
  xdsl/irdl/irdl.py
Labels: core

#2684 backend: (csl) Added printing for `param`, `comptime_struct` and some builtins
  tests/filecheck/backend/csl/print_csl.mlir
  xdsl/backend/csl/print_csl.py
Labels: backend

#2662 transformations: linalg.generic to loops factor out some helpers
  xdsl/transforms/convert_linalg_to_loops.py
  xdsl/transforms/convert_memref_stream_to_loops.py
  xdsl/transforms/loop_nest_lowering_utils.py
Labels: transformations

#2677 transformations: add memref-stream-unnest-out-parameters
  tests/filecheck/transforms/memref_stream_unnest_out_parameters.mlir
  xdsl/tools/command_line_tool.py
  xdsl/transforms/memref_stream_unnest_out_parameters.py
Labels: transformations

#2678 transformations: Handle imperfect loop nest when lowering memref_stream.generic to loops
  tests/filecheck/projects/riscv-backend-paper/add.mlir
  tests/filecheck/transforms/convert_memref_stream_to_loops.mlir
  xdsl/transforms/convert_memref_stream_to_loops.py
  xdsl/transforms/loop_nest_lowering_utils.py
Labels: transformations

#2687 core: (irdl) Allow ClassVar with all uppercase name
  tests/dialects/test_irdl.py
  tests/dialects/test_irdl_with_annotations.py
  xdsl/irdl/irdl.py
Labels: core

#2660 core: unify (Pattern)Rewriter insertion and inlining APIs around InsertPoint
  docs/Toy/toy/rewrites/lower_toy_affine.py
  docs/Toy/toy/rewrites/setup_riscv_pass.py
  tests/pattern_rewriter/test_pattern_rewriter.py
  tests/test_rewriter.py
  xdsl/backend/riscv/lowering/convert_riscv_scf_to_riscv_cf.py
  xdsl/backend/riscv/lowering/convert_snitch_stream_to_snitch.py
  xdsl/backend/riscv/lowering/utils.py
  xdsl/backend/riscv/riscv_scf_to_asm.py
  xdsl/pattern_rewriter.py
  xdsl/rewriter.py
  xdsl/transforms/canonicalization_patterns/scf.py
  xdsl/transforms/canonicalization_patterns/stencil.py
  xdsl/transforms/convert_linalg_to_loops.py
  xdsl/transforms/convert_memref_stream_to_loops.py
  xdsl/transforms/convert_memref_stream_to_snitch_stream.py
  xdsl/transforms/experimental/convert_stencil_to_ll_mlir.py
  xdsl/transforms/experimental/dmp/stencil_global_to_local.py
  xdsl/transforms/experimental/function_constant_pinning.py
  xdsl/transforms/experimental/hls_convert_stencil_to_ll_mlir.py
  xdsl/transforms/experimental/stencil_tensorize_z_dimension.py
  xdsl/transforms/loop_hoist_memref.py
  xdsl/transforms/loop_nest_lowering_utils.py
  xdsl/transforms/lower_riscv_func.py
  xdsl/transforms/memref_streamify.py
Labels: core

#2650 ci: fix codecov
  .github/workflows/ci-mlir.yml
Labels: CI

#2682 dialects: (arith) Add verifier to 'arith.index_cast' op and fix returns in inits
  tests/filecheck/dialects/arith/arith_invalid.mlir
  tests/filecheck/dialects/arith/arith_ops.mlir
  xdsl/dialects/arith.py
Labels: dialects

#2694 dialects: (csl) print dsd ops
  tests/filecheck/backend/csl/print_csl.mlir
  tests/filecheck/dialects/csl/ops.mlir
  xdsl/backend/csl/print_csl.py
  xdsl/dialects/csl.py
Labels: dialects, backend

#2698 tests: Add filecheck for distribute-stencil as it is.
  tests/filecheck/transforms/distribute-stencil.mlir
Labels: testing

#2702 dialects: Define memref.atomic rmw
  tests/filecheck/dialects/memref/memref_ops.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/memref/memref_ops_mlir_conversion.mlir
  xdsl/dialects/builtin.py
  xdsl/dialects/memref.py
Labels: dialects, minor

#2699 core: allow to define a RangeConstraint on a region's entry arguments.
  tests/irdl/test_operation_definition.py
  xdsl/irdl/irdl.py
Labels: core

#2697 backend: (csl) conditional statements
  tests/filecheck/backend/csl/print_csl.mlir
  xdsl/backend/csl/print_csl.py
Labels: backend

#2700 core: Implement and use ConstraintContext
  docs/irdl.ipynb
  tests/dialects/test_builtin.py
  tests/irdl/test_attribute_definition.py
  tests/test_pyrdl.py
  xdsl/dialects/builtin.py
  xdsl/dialects/stencil.py
  xdsl/irdl/declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format_parser.py
  xdsl/irdl/irdl.py
  xdsl/utils/hints.py
Labels: core

#2706 dialects: Add NoMemoryEffects to memref and snitch_runtime dialect ops
  tests/filecheck/mlir-conversion/with-mlir/dialects/memref/canonicalize.mlir
  xdsl/dialects/memref.py
  xdsl/dialects/snitch_runtime.py
Labels: dialects

#2707 core: (rewriter) Correctly pass safe_erase in replace_op
  xdsl/pattern_rewriter.py
Labels: core

#2710 backend: (csl) Rework printing logic for printing individual modules
  tests/filecheck/backend/csl/gaussian-end-to-end.mlir
  tests/filecheck/backend/csl/print_csl.mlir
  xdsl/backend/csl/print_csl.py
Labels: backend

#2712 dialects: (csl) set_tile_code fix traits
  xdsl/dialects/csl.py
Labels: dialects

#2714 dialect: (csl) Add signedness cast and concat struct ops
  tests/filecheck/backend/csl/print_csl.mlir
  tests/filecheck/dialects/csl/ops.mlir
  xdsl/backend/csl/print_csl.py
  xdsl/dialects/csl.py
Labels: dialects

#2718 core: Implement MemrefLayoutAttr base class and use in parser.
  xdsl/dialects/builtin.py
  xdsl/dialects/experimental/aie.py
  xdsl/dialects/memref.py
  xdsl/parser/attribute_parser.py
Labels: core

#2726 interactive: remove hard-coded list for interactive condensed passes test
  tests/interactive/test_app.py
Labels: minor, interactive

#2727 interactive: dynamically retrieve condensed_list in test_rewrites
  tests/interactive/test_app.py
Labels: minor, interactive

#2722 dependencies: move dev dependencies to pyproject.toml
  .github/workflows/ci-pyright-fails.yml
  README.md
  pyproject.toml
  requirements.txt
Labels: dependencies

#2723 dependencies: split "extras" dependencies into named subprojects
  README.md
  pyproject.toml
  requirements.txt
Labels: dependencies

#2731 misc: Remove unnecessary self type annotation
  xdsl/dialects/builtin.py
Labels: misc

#2729 misc: remove deprecated methods that have been deprecated for a while
  xdsl/dialects/arith.py
  xdsl/dialects/builtin.py
  xdsl/dialects/cf.py
  xdsl/dialects/experimental/aie.py
  xdsl/dialects/experimental/air.py
  xdsl/dialects/memref.py
  xdsl/dialects/mpi.py
  xdsl/dialects/scf.py
  xdsl/frontend/code_generation.py
  xdsl/ir/core.py
  xdsl/transforms/convert_ml_program_to_memref.py
  xdsl/transforms/experimental/Apply1DMPIToStencil.py
  xdsl/transforms/experimental/dmp/stencil_global_to_local.py
  xdsl/transforms/experimental/lower_hls.py
Labels: API

#2733 misc: irdl loading fixes
  tests/filecheck/dialects/irdl/cmath_irdl_loading.py
  xdsl/interpreters/irdl.py
  xdsl/irdl/irdl.py
Labels: misc

#2732 misc: Remove shadowing of variable in isa
  xdsl/utils/hints.py
Labels: minor, misc

#2721 dialects: (memref_stream) Add some more verification for generic op
  tests/filecheck/dialects/memref_stream/verify.mlir
  xdsl/dialects/memref_stream.py
Labels: dialects

#2741 transforms: (experimental) minor updates to stencil-tensorize-z-dim
  xdsl/transforms/experimental/stencil_tensorize_z_dimension.py
Labels: minor, transformations

#2742 dialects: (csl) adding constructors for CSL ops
  xdsl/dialects/csl.py
Labels: dialects, minor

#2745 dialects: (csl) Improve some constructor inits
  xdsl/dialects/csl.py
Labels: dialects

#2728 backend: (csl) Slightly rework printer to promote certain values to inline expressions
  tests/filecheck/backend/csl/print_csl.mlir
  xdsl/backend/csl/print_csl.py
  xdsl/dialects/csl.py
Labels: minor, backend

#2734 misc: Implement Dialect stub generation
  tests/filecheck/dialects/irdl/cmath_irdl_stub.py
  xdsl/utils/dialect_stub.py
Labels: misc

#2748 dialects: Add memref.extract_strided_metadata op
  tests/dialects/test_memref.py
  tests/filecheck/dialects/memref/memref_ops.mlir
  xdsl/dialects/memref.py
Labels: enhancement, dialects

#2746 dialects: Add qssa dialect
  tests/filecheck/dialects/qssa/ops.mlir
  xdsl/dialects/qssa.py
  xdsl/tools/command_line_tool.py
Labels: enhancement, dialects

#2751 installation: Add ruff to flake.nix
  flake.nix
Labels: misc

#2743 interpreter: (memref_stream) add interpreter support for imperfect nesting
  tests/interpreters/test_memref_stream_interpreter.py
  xdsl/dialects/memref_stream.py
  xdsl/interpreters/memref_stream.py
  xdsl/transforms/convert_memref_stream_to_loops.py
Labels: interpreter

#2744 dialects: (builtin) Fix printing and parsing of `UnitAttr`
  tests/filecheck/parser-printer/builtin_attrs.mlir
  xdsl/parser/attribute_parser.py
  xdsl/printer.py
Labels: dialects

#2752 backend: (riscv) Add prologue epilogue insertion
  tests/filecheck/backend/riscv/prologue_epilogue_insertion.mlir
  tests/interactive/test_get_all_available_passes.py
  xdsl/backend/riscv/prologue_epilogue_insertion.py
  xdsl/tools/command_line_tool.py
Labels: backend

#2735 misc: Implement Python module importing from `.irdl` files
  .github/workflows/ci-pyright-fails.yml
  .gitignore
  Makefile
  pyproject.toml
  tests/filecheck/dialects/irdl/pyrdl-to-irdl/cmath-conversion.py
  tests/test_mlcontext.py
  xdsl/__init__.py
  xdsl/dialects/__init__.py
  xdsl/dialects/cmath.irdl
  xdsl/dialects/cmath.py
  xdsl/utils/dialect_stub.py
Labels: misc

#2756 transforms: stencil-tensorize-z-dim accept stencil.field as function arg
  tests/filecheck/transforms/stencil-tensorize-z-dimension.mlir
  xdsl/transforms/experimental/stencil_tensorize_z_dimension.py
Labels: minor, transformations

#2759 ci: use venv pyright in CI action
  .github/workflows/ci-pyright-fails.yml
  pyproject.toml
Labels: CI

#2758 transformations: do not insert affine.apply ops when streaming
  tests/filecheck/transforms/convert_memref_stream_to_loops.mlir
  xdsl/transforms/convert_linalg_to_loops.py
  xdsl/transforms/convert_memref_stream_to_loops.py
  xdsl/transforms/loop_nest_lowering_utils.py
Labels: transformations

#2760 transformations: fix yielding of values in memref_stream.generic lowering
  tests/filecheck/transforms/convert_memref_stream_to_loops.mlir
  xdsl/transforms/loop_nest_lowering_utils.py
Labels: bug, transformations

#2757 testing: Ignore missing sources warning in pyright.
  pyproject.toml
Labels: testing

#2767 core: make VarOperand, VarOpResult, and VarRegion tuple instead of list
  tests/dialects/test_scf.py
  tests/irdl/test_operation_builder.py
  xdsl/ir/core.py
  xdsl/irdl/irdl.py
  xdsl/printer.py
  xdsl/traits.py
  xdsl/transforms/experimental/lower_hls.py
  xdsl/transforms/lower_affine.py
  xdsl/transforms/lower_riscv_func.py
Labels: core

#2769 dialects: Add qref dialect
  tests/filecheck/dialects/qref/ops.mlir
  xdsl/dialects/__init__.py
  xdsl/dialects/qref.py
Labels: dialects

#2774 dialects: (memref) canonicalize removes unused memref allocs
  tests/filecheck/dialects/memref/canonicalize.mlir
  xdsl/dialects/memref.py
  xdsl/transforms/canonicalization_patterns/memref.py
Labels: dialects

#2705 core: [NFC] Split irdl.py
  docs/irdl.ipynb
  pyproject.toml
  xdsl/irdl/__init__.py
  xdsl/irdl/attributes.py
  xdsl/irdl/constraints.py
  xdsl/irdl/error.py
  xdsl/irdl/operations.py
Labels: core

#2777 (minor): allow csl_stencil.access to operate on own data
  tests/filecheck/dialects/csl/csl-stencil-ops.mlir
  tests/filecheck/transforms/stencil-to-csl-stencil.mlir
  xdsl/dialects/csl/csl_stencil.py
  xdsl/transforms/stencil_to_csl_stencil.py
Labels: dialects, minor, transformations

#2770 transformations: add qref/qssa conversions
  tests/filecheck/transforms/convert_qref_to_qssa.mlir
  tests/filecheck/transforms/convert_qssa_to_qref.mlir
  xdsl/dialects/qref.py
  xdsl/dialects/qssa.py
  xdsl/tools/command_line_tool.py
  xdsl/transforms/convert_qref_to_qssa.py
  xdsl/transforms/convert_qssa_to_qref.py
Labels: transformations

#2778 backend: (riscv) riscv-prologue-epilogue-insertion
  tests/filecheck/backend/riscv/prologue_epilogue_insertion.mlir
  tests/interactive/test_get_all_available_passes.py
  xdsl/backend/riscv/prologue_epilogue_insertion.py
Labels: bug, backend

#2783 transforms: (convert-snrt-to-riscv) Convert to arith where possible
  tests/filecheck/backend/riscv/func_and_arith_to_riscv_asm_flow.mlir
  tests/filecheck/transforms/inline-snrt.mlir
  xdsl/tools/command_line_tool.py
  xdsl/transforms/inline_snrt.py
Labels: transformations

#2782 dialects: (csl) Add csl.constants op and printing
  tests/filecheck/backend/csl/print_csl.mlir
  tests/filecheck/dialects/csl/ops.mlir
  xdsl/backend/csl/print_csl.py
  xdsl/dialects/csl/csl.py
Labels: dialects, backend

#2765 transformations: memref_streamify handle constant inits [3/3]
  tests/filecheck/projects/riscv-backend-paper/bottom_up.mlir
  tests/filecheck/transforms/memref_streamify.mlir
  xdsl/transforms/memref_streamify.py
Labels: transformations

#2771 transformations: Fix bug in memref-stream-unnest-out-parameters
  tests/filecheck/transforms/memref_stream_unnest_out_parameters.mlir
  xdsl/dialects/memref_stream.py
  xdsl/transforms/memref_stream_unnest_out_parameters.py
Labels: transformations

#2775 transformations: Only stream used inputs in `memref-streamify`
  tests/filecheck/transforms/memref_streamify.mlir
  xdsl/transforms/memref_streamify.py
Labels: transformations

#2785 dialects: (riscv) Fix I, S and shift operation immediate bounds
  tests/dialects/test_riscv.py
  tests/filecheck/backend/riscv/verify.mlir
  tests/filecheck/dialects/riscv/riscv_ops.mlir
  tests/filecheck/dialects/riscv_scf/ops.mlir
  tests/filecheck/dialects/riscv_snitch/ops.mlir
  xdsl/dialects/riscv.py
Labels: dialects

#2780 dialects: (wasm) Add wasm dialect
  tests/filecheck/dialects/wasm/ops.mlir
  xdsl/dialects/__init__.py
  xdsl/dialects/wasm/__init__.py
  xdsl/dialects/wasm/ops.py
Labels: dialects

#2786 dialects: (riscv, x86) do not print empty <> for unallocated registers
  tests/dialects/test_riscv.py
  tests/filecheck/backend/convert_riscv_scf_to_riscv_cf_with_regalloc.mlir
  tests/filecheck/backend/riscv/canonicalize.mlir
  tests/filecheck/backend/riscv/convert_arith_to_riscv.mlir
  tests/filecheck/backend/riscv/convert_func_to_riscv_func.mlir
  tests/filecheck/backend/riscv/convert_riscv_scf_for_to_frep.mlir
  tests/filecheck/backend/riscv/memref_to_riscv.mlir
  tests/filecheck/backend/riscv/memref_to_riscv_opt.mlir
  tests/filecheck/backend/riscv/print_format_to_riscv_debug.mlir
  tests/filecheck/backend/riscv/register_allocation_exclude_snitch.mlir
  tests/filecheck/backend/riscv/register_allocation_frep.mlir
  tests/filecheck/backend/riscv/register_allocation_liveness_block_naive.mlir
  tests/filecheck/backend/riscv/register_allocation_liveness_block_naive_limited.mlir
  tests/filecheck/backend/riscv/register_allocation_preallocated.mlir
  tests/filecheck/backend/riscv/riscv_register_allocation.mlir
  tests/filecheck/backend/riscv/verify.mlir
  tests/filecheck/backend/rvscf_scf_lowering.mlir
  tests/filecheck/dialects/riscv/frep_verification.mlir
  tests/filecheck/dialects/riscv/riscv_assembly_emission.mlir
  tests/filecheck/dialects/riscv/riscv_ops.mlir
  tests/filecheck/dialects/riscv_cf/canonicalize.mlir
  tests/filecheck/dialects/riscv_func/lower_riscv_func.mlir
  tests/filecheck/dialects/riscv_func/riscv_func_ops.mlir
  tests/filecheck/dialects/riscv_scf/loop_range_folding.mlir
  tests/filecheck/dialects/riscv_scf/ops.mlir
  tests/filecheck/dialects/riscv_scf/verification.mlir
  tests/filecheck/dialects/riscv_snitch/ops.mlir
  tests/filecheck/dialects/snitch/snitch_ops.mlir
  tests/filecheck/dialects/snitch/snitch_to_riscv_lowering.mlir
  tests/filecheck/dialects/snitch_stream/convert_snitch_stream_to_snitch.mlir
  tests/filecheck/dialects/snitch_stream/ops.mlir
  tests/filecheck/dialects/x86/x86_assembly_emission.mlir
  tests/filecheck/dialects/x86/x86_ops.mlir
  tests/filecheck/projects/riscv-backend-paper/add_snitch_stream.mlir
  tests/filecheck/projects/riscv-backend-paper/ddot_regalloc.mlir
  tests/filecheck/projects/riscv-backend-paper/relu_snitch_stream.mlir
  tests/filecheck/runner/riscv.mlir
  tests/filecheck/runner/riscv_scf.mlir
  tests/filecheck/transforms/convert_memref_stream_to_snitch.mlir
  tests/filecheck/transforms/individual_rewrite.mlir
  tests/filecheck/transforms/inline-snrt.mlir
  tests/filecheck/transforms/riscv_cse.mlir
  tests/filecheck/transforms/snitch_register_allocation.mlir
  tests/interactive/test_app.py
  tests/interactive/test_pass_metrics.py
  tests/interpreters/test_riscv_interpreter.py
  xdsl/backend/register_type.py
  xdsl/dialects/riscv.py
  xdsl/dialects/x86/register.py
Labels: dialects

#2776 transformations: Add `memref-stream-(infer|generalize)-fill` passes
  tests/filecheck/projects/riscv-backend-paper/bottom_up.mlir
  tests/filecheck/transforms/memref_stream_generalize_fill.mlir
  tests/filecheck/transforms/memref_stream_infer_fill.mlir
  xdsl/tools/command_line_tool.py
  xdsl/transforms/memref_stream_generalize_fill.py
  xdsl/transforms/memref_stream_infer_fill.py
Labels: transformations

#2787 documentation: allow marimo notebooks as documentation
  .github/workflows/ci-notebooks.yml
  .pre-commit-config.yaml
  Makefile
  docs/marimo/IR_Chapter_1_Attributes.py
  pyproject.toml
Labels: documentation

#2789 misc: Small refactor to `PatternRewriter.replace_op`
  xdsl/pattern_rewriter.py
Labels: minor, misc, rewriting

#2685 dialects: Implement MemoryEffect on RISCV op, just reuse main CSE.
  tests/filecheck/transforms/riscv_cse.mlir
  xdsl/dialects/riscv.py
  xdsl/tools/command_line_tool.py
  xdsl/transforms/riscv_cse.py
Labels: dialects, transformations

#2792 core: replace BlockReverseOps with a Reversible conformance
  xdsl/backend/riscv/register_allocation.py
  xdsl/ir/core.py
  xdsl/transforms/experimental/hls_convert_stencil_to_ll_mlir.py
Labels: core

#2784 dialects: (riscv) Add HasInsntrait and implement trait for some operations
  tests/dialects/test_riscv_snitch.py
  xdsl/backend/riscv/traits.py
  xdsl/dialects/riscv_snitch.py
  xdsl/traits.py
Labels: dialects, backend

#2788 dialects: (wasm) Add binary encoding interface
  tests/dialects/wasm/test_wasm_encoding.py
  xdsl/dialects/wasm/encoding.py
  xdsl/dialects/wasm/ops.py
Labels: dialects

#2797 dialects: (riscv) Make riscv.get_register pure
  xdsl/dialects/riscv.py
Labels: dialects

#2798 testing: Extract linalg to snitch pipeline to test passes in bottom-up
  tests/filecheck/projects/riscv-backend-paper/bottom_up.mlir
  tests/interactive/test_get_all_available_passes.py
  xdsl/tools/command_line_tool.py
  xdsl/transforms/test_lower_memref_stream_to_snitch_stream.py
  xdsl/transforms/test_lower_snitch_stream_to_asm.py
  xdsl/transforms/test_optimise_memref_stream.py
Labels: testing

#2781 (dialects): csl_stencil apply op
  tests/dialects/test_csl_stencil.py
  tests/filecheck/dialects/csl/csl-stencil-ops.mlir
  xdsl/dialects/csl/csl_stencil.py
Labels: dialects

#2794 core: add RegionBlocks to abstract away the block storage [1/2]
  tests/irdl/test_operation_builder.py
  tests/test_builtin_traits.py
  tests/test_frontend_op_inserter.py
  tests/test_ir.py
  xdsl/backend/riscv/lowering/convert_func_to_riscv_func.py
  xdsl/dialects/func.py
  xdsl/dialects/riscv_cf.py
  xdsl/dialects/x86/ops.py
  xdsl/frontend/code_generation.py
  xdsl/frontend/op_inserter.py
  xdsl/frontend/passes/desymref.py
  xdsl/interpreter.py
  xdsl/ir/core.py
  xdsl/irdl/operations.py
  xdsl/printer.py
  xdsl/rewriter.py
  xdsl/rewriting/composable_rewriting/immutable_ir/immutable_ir.py
  xdsl/transforms/scf_for_loop_flatten.py
Labels: core

#2801 dialects: (wasm) Add wat encoding
  tests/dialects/wasm/test_wat_encoding.py
  tests/filecheck/dialects/wasm/wat.mlir
  xdsl/dialects/wasm/ops.py
  xdsl/dialects/wasm/wat.py
  xdsl/xdsl_opt_main.py
Labels: dialects

#2796 docs: add onnx demo notebook
  .github/workflows/ci-mlir.yml
  Makefile
  docs/marimo/mlir/README.md
  docs/marimo/mlir/onnx-demo.py
  pyproject.toml
Labels: documentation
