Repository xdslproject/xdsl, pull requests merged in 2024-07, with the labels that each got.

#2805 dialects: (riscv) RISCVOp -> RISCVAsmOperation subclass of IRDLOperation
  xdsl/backend/riscv/register_allocation.py
  xdsl/dialects/riscv.py
  xdsl/dialects/riscv_cf.py
  xdsl/dialects/riscv_debug.py
  xdsl/dialects/riscv_func.py
  xdsl/dialects/riscv_snitch.py
Labels: dialects

#2811 backend: (riscv) move register-allocation tests in their own directory
  tests/filecheck/backend/riscv/register-allocation/exclude_snitch.mlir
  tests/filecheck/backend/riscv/register-allocation/frep.mlir
  tests/filecheck/backend/riscv/register-allocation/generic.mlir
  tests/filecheck/backend/riscv/register-allocation/liveness_block_naive.mlir
  tests/filecheck/backend/riscv/register-allocation/liveness_block_naive_limited.mlir
  tests/filecheck/backend/riscv/register-allocation/preallocated.mlir
Labels: backend

#2806 testing: unpeel matmul in bottom-up tests
  tests/filecheck/projects/riscv-backend-paper/bottom_up.mlir
Labels: testing

#2809 core: Make print_string aware of indentation
  tests/test_printer.py
  xdsl/printer.py
Labels: enhancement, core

#2813 dialects: (memref_stream) add interleaved iterator
  tests/filecheck/dialects/memref_stream/ops.mlir
  tests/filecheck/dialects/memref_stream/verify.mlir
  tests/filecheck/transforms/convert_memref_stream_to_loops.mlir
  tests/filecheck/transforms/convert_memref_stream_to_snitch.mlir
  tests/filecheck/transforms/memref_streamify.mlir
  tests/interpreters/test_memref_stream_interpreter.py
  xdsl/dialects/memref_stream.py
  xdsl/interpreters/memref_stream.py
  xdsl/transforms/convert_memref_stream_to_loops.py
  xdsl/transforms/memref_streamify.py
Labels: dialects

#2818 bug: (snitch_stream) simplify crashes when all bounds are 1
  tests/interpreters/test_snitch_stream_interpreter.py
  xdsl/dialects/snitch_stream.py
Labels: bug

#2815 dialects: (memref_stream) print memref_stream.generic with newlines
  tests/filecheck/dialects/memref_stream/ops.mlir
  tests/filecheck/transforms/convert_linalg_to_memref_stream.mlir
  tests/filecheck/transforms/convert_memref_stream_to_loops.mlir
  tests/filecheck/transforms/memref_stream_fold_fill.mlir
  tests/filecheck/transforms/memref_stream_generalize_fill.mlir
  tests/filecheck/transforms/memref_stream_unnest_out_parameters.mlir
  tests/filecheck/transforms/memref_streamify.mlir
  xdsl/dialects/memref_stream.py
Labels: dialects

#2822 core: Add option to clone name hints
  tests/filecheck/dialects/stencil/oec-kernels/fvtp2d_qi.mlir
  tests/filecheck/transforms/function-constant-pinning.mlir
  tests/filecheck/transforms/stencil-storage-materialization.mlir
  tests/filecheck/transforms/stencil-unroll.mlir
  tests/test_ir.py
  xdsl/ir/core.py
Labels: core

#2823 transformations: add memref-stream-interleave
  tests/filecheck/transforms/memref_stream_interleave.mlir
  xdsl/tools/command_line_tool.py
  xdsl/transforms/memref_stream_interleave.py
Labels: transformations

#2803 (transform): convert to csl_stencil.apply
  tests/filecheck/transforms/stencil-to-csl-stencil.mlir
  xdsl/dialects/csl/csl_stencil.py
  xdsl/dialects/tensor.py
  xdsl/transforms/experimental/stencil_tensorize_z_dimension.py
  xdsl/transforms/stencil_to_csl_stencil.py
Labels: transformations

#2793 core: Implement EffectKind
  tests/filecheck/transforms/cse.mlir
  xdsl/dialects/riscv.py
  xdsl/dialects/test.py
  xdsl/traits.py
  xdsl/transforms/common_subexpression_elimination.py
  xdsl/transforms/dead_code_elimination.py
Labels: core

#2836 testing: don't print the output of marimo unless there was an error
  Makefile
Labels: testing

#2842 dialects: (memref) Make memref.extract_strided_metadata have NoMemoryEffect
  xdsl/dialects/memref.py
Labels: dialects

#2839 api: add printing and parsing of dynamic lists as in MLIR
  tests/test_dialect_utils.py
  xdsl/dialects/builtin.py
  xdsl/dialects/utils.py
Labels: API

#2844 dialects: (memref) Make memref.extract_strided_metadata have NoMemoryEffect
  xdsl/dialects/memref.py
Labels: dialects

#2837 dialects: (riscv) remove noisy () -> in get_(float_)register and li
  tests/filecheck/backend/convert_riscv_scf_to_riscv_cf.mlir
  tests/filecheck/backend/convert_riscv_scf_to_riscv_cf_with_regalloc.mlir
  tests/filecheck/backend/riscv/canonicalize.mlir
  tests/filecheck/backend/riscv/convert_arith_to_riscv.mlir
  tests/filecheck/backend/riscv/convert_riscv_scf_for_to_frep.mlir
  tests/filecheck/backend/riscv/memref_to_riscv.mlir
  tests/filecheck/backend/riscv/memref_to_riscv_opt.mlir
  tests/filecheck/backend/riscv/prologue_epilogue_insertion.mlir
  tests/filecheck/backend/riscv/register-allocation/frep.mlir
  tests/filecheck/backend/riscv/register-allocation/generic.mlir
  tests/filecheck/backend/riscv/register-allocation/liveness_block_naive.mlir
  tests/filecheck/backend/riscv/register-allocation/liveness_block_naive_limited.mlir
  tests/filecheck/backend/riscv/register-allocation/preallocated.mlir
  tests/filecheck/backend/riscv/verify.mlir
  tests/filecheck/backend/rvscf_lowering_labels.mlir
  tests/filecheck/dialects/riscv/riscv_assembly_emission.mlir
  tests/filecheck/dialects/riscv/riscv_ops.mlir
  tests/filecheck/dialects/riscv_cf/assembly_emission.mlir
  tests/filecheck/dialects/riscv_cf/canonicalize.mlir
  tests/filecheck/dialects/riscv_debug/riscv_debug_ops.mlir
  tests/filecheck/dialects/riscv_func/lower_riscv_func.mlir
  tests/filecheck/dialects/riscv_func/lower_riscv_func_main.mlir
  tests/filecheck/dialects/riscv_scf/loop_range_folding.mlir
  tests/filecheck/dialects/riscv_scf/ops.mlir
  tests/filecheck/dialects/riscv_snitch/assembly_emission.mlir
  tests/filecheck/dialects/riscv_snitch/ops.mlir
  tests/filecheck/dialects/snitch/snitch_to_riscv_lowering.mlir
  tests/filecheck/dialects/snitch_stream/convert_snitch_stream_to_snitch.mlir
  tests/filecheck/dialects/snitch_stream/ops.mlir
  tests/filecheck/projects/riscv-backend-paper/add_snitch_stream.mlir
  tests/filecheck/projects/riscv-backend-paper/ddot_regalloc.mlir
  tests/filecheck/projects/riscv-backend-paper/pres.mlir
  tests/filecheck/projects/riscv-backend-paper/relu_snitch_stream.mlir
  tests/filecheck/runner/riscv.mlir
  tests/filecheck/runner/riscv_scf.mlir
  tests/filecheck/transforms/individual_rewrite.mlir
  tests/filecheck/transforms/inline-snrt.mlir
  tests/filecheck/transforms/riscv_cse.mlir
  tests/filecheck/transforms/snitch_register_allocation.mlir
  tests/filecheck/with-riscemu/riscv_emulation.mlir
  tests/filecheck/with-riscemu/rvscf_lowering_emu.mlir
  tests/interactive/test_app.py
  tests/interactive/test_pass_metrics.py
  xdsl/dialects/riscv.py
Labels: dialects

#2840 dialects: (memref) add custom syntax for memref_subview
  tests/filecheck/dialects/memref/memref_ops.mlir
  tests/filecheck/dialects/stencil/oec-kernels/fvtp2d_qi.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/memref/memref_ops_custom.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/memref/memref_ops_mlir_conversion.mlir
  tests/filecheck/transforms/convert-stencil-to-ll-mlir.mlir
  xdsl/dialects/memref.py
Labels: dialects

#2846 transformations: Handle more data types in memref to riscv lowering
  tests/filecheck/backend/riscv/memref_to_riscv.mlir
  xdsl/backend/riscv/lowering/convert_memref_to_riscv.py
Labels: transformations

#2845 transformations: Handle more division sizes in memref-stream-interleave
  tests/filecheck/transforms/memref_stream_interleave.mlir
  xdsl/transforms/memref_stream_interleave.py
Labels: transformations

#2853 backend: reserve registers not preserved across function calls in RISC-V
  tests/backend/riscv/test_preallocated.py
  xdsl/backend/riscv/register_allocation.py
Labels: backend

#2855 backend: (riscv) don't print external function declaration in assembly
  tests/filecheck/dialects/riscv/riscv_assembly_emission.mlir
  xdsl/dialects/riscv_func.py
Labels: backend

#2858 backend: (riscv) preserve name hints when casting operands
  tests/filecheck/backend/riscv/memref_to_riscv.mlir
  tests/filecheck/backend/riscv/print_format_to_riscv_debug.mlir
  xdsl/backend/riscv/lowering/convert_memref_to_riscv.py
  xdsl/backend/riscv/lowering/utils.py
Labels: backend

#2859 dialects: (snitch_stream) add custom syntax to streaming region
  tests/filecheck/dialects/snitch_stream/ops.mlir
  tests/filecheck/transforms/convert_memref_stream_to_snitch.mlir
  tests/filecheck/transforms/snitch_register_allocation.mlir
  xdsl/dialects/snitch_stream.py
Labels: dialects

#2860 dialects: (transform) Define non-parametrized transform types
  tests/filecheck/dialects/transform/transform_types.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/transform/transform_types.mlir
  xdsl/dialects/__init__.py
  xdsl/dialects/transform.py
Labels: dialects

#2856 transformations: Add dealloc lowering to convert-memref-to-riscv
  tests/filecheck/backend/riscv/memref_to_riscv.mlir
  xdsl/backend/riscv/lowering/convert_memref_to_riscv.py
Labels: transformations

#2847 transformations: Add memref.subview lowering to convert-memref-to-riscv
  tests/filecheck/backend/riscv/memref_to_riscv.mlir
  xdsl/backend/riscv/lowering/convert_memref_to_riscv.py
  xdsl/dialects/builtin.py
Labels: transformations

#2848 dialects: (affine) Add custom syntax to affine.apply
  tests/filecheck/dialects/affine/affine_ops.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/affine/affine_ops.mlir
  tests/filecheck/transforms/convert_linalg_to_loops.mlir
  tests/filecheck/transforms/cse.mlir
  xdsl/dialects/affine.py
Labels: dialects

#2863 docs: (toy) remove all custom instructions from Toy
  docs/Toy/toy/__main__.py
  docs/Toy/toy/compiler.py
  docs/Toy/toy/emulator/toy_accelerator_instruction_functions.py
  docs/Toy/toy/emulator/toy_accelerator_instructions.py
  docs/Toy/toy/rewrites/lower_memref_riscv.py
  docs/Toy/toy/rewrites/setup_riscv_pass.py
  docs/Toy/toy/tests/test_add_sections.py
  docs/Toy/toy/tests/test_lower_memref_riscv.py
  xdsl/interpreters/riscv.py
  xdsl/interpreters/riscv_func.py
Labels: documentation

#2865 transformations: convert-memref-stream-to-snitch-stream fix name
  docs/marimo/mlir/onnx_demo.py
  tests/filecheck/projects/riscv-backend-paper/add.mlir
  tests/filecheck/transforms/convert_memref_stream_to_snitch_stream.mlir
  xdsl/tools/command_line_tool.py
  xdsl/transforms/convert_memref_stream_to_snitch_stream.py
  xdsl/transforms/test_lower_memref_stream_to_snitch_stream.py
Labels: transformations

#2831 transformations: Handle interleaving in convert-memref-stream-to-loops
  tests/filecheck/projects/riscv-backend-paper/bottom_up.mlir
  tests/filecheck/transforms/convert_memref_stream_to_loops.mlir
  xdsl/dialects/memref_stream.py
  xdsl/transforms/convert_linalg_to_loops.py
  xdsl/transforms/convert_memref_stream_to_loops.py
  xdsl/transforms/loop_nest_lowering_utils.py
  xdsl/transforms/memref_stream_interleave.py
Labels: transformations

#2851 dialects: (memref_stream) remove unused operands in canonicalization
  tests/filecheck/dialects/memref_stream/canonicalize.mlir
  xdsl/dialects/memref_stream.py
  xdsl/transforms/canonicalization_patterns/memref_stream.py
Labels: dialects

#2866 transformations: handle strided layout attr in memref_stream lowering
  tests/dialects/test_memref.py
  tests/filecheck/transforms/convert_memref_stream_to_snitch_stream.mlir
  tests/transforms/test_convert_memref_stream_to_snitch_stream.py
  xdsl/dialects/builtin.py
  xdsl/transforms/convert_memref_stream_to_snitch_stream.py
Labels: transformations

#2864 testing: update shapes of kernels from paper in bottom-up tests
  tests/filecheck/projects/riscv-backend-paper/bottom_up.mlir
Labels: testing

#2868 (minor): print properties on csl_stencil.apply
  tests/filecheck/dialects/csl/csl-stencil-ops.mlir
  tests/filecheck/transforms/stencil-to-csl-stencil.mlir
  xdsl/dialects/csl/csl_stencil.py
Labels: bug, minor

#2869 transformations: Add memref-stream-tile-outer-loops
  tests/filecheck/transforms/memref_stream_tile_outer_loops.mlir
  xdsl/dialects/memref.py
  xdsl/tools/command_line_tool.py
  xdsl/transforms/memref_stream_tile_outer_loops.py
Labels: transformations

#2850 testing: (memref_stream) add interleaving to test passes and express matmul as linalg
  tests/filecheck/projects/riscv-backend-paper/bottom_up.mlir
  tests/filecheck/projects/riscv-backend-paper/nsnet.mlir
  xdsl/transforms/test_optimise_memref_stream.py
Labels: testing

#2852 dialects: (linalg) Fix matmul custom syntax and custom init
  tests/dialects/test_linalg.py
  tests/filecheck/dialects/linalg/linalg_ops.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/linalg/ops.mlir
  xdsl/dialects/linalg.py
Labels: dialects

#2871 core: (rewriting) Fix recursive type conversion in block arguments for nested regions
  tests/pattern_rewriter/test_pattern_rewriter.py
  xdsl/pattern_rewriter.py
Labels: core

#2872 dialects: (riscv_snitch) Add f32 mul, add, pack from Snitch packed SIMD extension
  tests/filecheck/dialects/riscv_snitch/assembly_emission.mlir
  tests/filecheck/dialects/riscv_snitch/ops.mlir
  xdsl/dialects/riscv_snitch.py
Labels: dialects

#2867 (dialects): adding csl_wrapper dialect
  tests/dialects/test_csl_wrapper.py
  tests/filecheck/dialects/csl/csl-wrapper-ops.mlir
  xdsl/dialects/__init__.py
  xdsl/dialects/csl/csl_wrapper.py
Labels: dialects

#2886 dialects: (riscv_snitch) remove always ZERO rd in snitch config ops
  tests/filecheck/backend/riscv/canonicalize.mlir
  tests/filecheck/backend/riscv/verify.mlir
  tests/filecheck/dialects/riscv_snitch/ops.mlir
  tests/filecheck/dialects/snitch/snitch_to_riscv_lowering.mlir
  tests/filecheck/projects/riscv-backend-paper/pres.mlir
  xdsl/dialects/riscv.py
  xdsl/dialects/riscv_snitch.py
  xdsl/transforms/canonicalization_patterns/riscv.py
  xdsl/transforms/lower_snitch.py
Labels: dialects

#2878 (transform): csl-stencil to csl-wrapper pass
  tests/dialects/test_csl_wrapper.py
  tests/dialects/test_stencil.py
  tests/filecheck/transforms/csl-stencil-to-csl-wrapper.mlir
  xdsl/dialects/csl/csl_stencil.py
  xdsl/dialects/csl/csl_wrapper.py
  xdsl/dialects/stencil.py
  xdsl/tools/command_line_tool.py
  xdsl/transforms/csl_stencil_to_csl_wrapper.py
Labels: transformations

#2824 tests: Fix a bunch of filechecks
  tests/filecheck/backend/csl/print_csl.mlir
  tests/filecheck/backend/riscv/func_and_arith_to_riscv_asm_flow.mlir
  tests/filecheck/backend/riscv/prologue_epilogue_insertion.mlir
  tests/filecheck/dialects/gpu/ops.mlir
  tests/filecheck/dialects/llvm/array.mlir
  tests/filecheck/dialects/memref/memref_ops.mlir
  tests/filecheck/dialects/pdl/pdl_attribute.mlir
  tests/filecheck/dialects/pdl/pdl_operand.mlir
  tests/filecheck/dialects/pdl/pdl_replace.mlir
  tests/filecheck/dialects/pdl/pdl_result.mlir
  tests/filecheck/dialects/scf/reduce.mlir
  tests/filecheck/projects/riscv-backend-paper/conv.mlir
  tests/filecheck/projects/riscv-backend-paper/fill.mlir
  tests/filecheck/projects/riscv-backend-paper/pres.mlir
  tests/filecheck/transforms/cse.mlir
  tests/filecheck/version.mlir
Labels: testing

#2828 tests: Update filecheck to 1.0
  docs/Toy/examples/codegen.toy
  docs/Toy/examples/interpret.toy
  docs/Toy/examples/tests/inline.mlir
  docs/Toy/examples/tests/optimise_toy.mlir
  pyproject.toml
  tests/filecheck/backend/riscv/prologue_epilogue_insertion.mlir
  tests/filecheck/dialects/memref/memref_ops.mlir
  tests/filecheck/dialects/riscv/riscv_assembly_emission.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/gpu/ops.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/memref/memref_ops_custom.mlir
  tests/filecheck/parser-printer/builtin_attrs.mlir
  tests/filecheck/projects/riscv-backend-paper/add.mlir
  tests/filecheck/projects/riscv-backend-paper/add_snitch_stream.mlir
  tests/filecheck/projects/riscv-backend-paper/conv.mlir
  tests/filecheck/projects/riscv-backend-paper/matmul.mlir
  tests/filecheck/projects/riscv-backend-paper/relu.mlir
  tests/filecheck/projects/riscv-backend-paper/relu_snitch_stream.mlir
  tests/filecheck/runner/with-wgpu/global_id_inc.mlir
Labels: dependencies, testing

#2888 (dialect): minor changes to csl and csl_wrapper
  tests/filecheck/dialects/csl/csl-wrapper-ops.mlir
  tests/filecheck/transforms/csl-stencil-to-csl-wrapper.mlir
  xdsl/dialects/csl/csl.py
  xdsl/dialects/csl/csl_wrapper.py
  xdsl/transforms/csl_stencil_to_csl_wrapper.py
Labels: dialects, minor

#2821 dialects: add parametrised rz gate
  tests/filecheck/dialects/qref/ops.mlir
  tests/filecheck/dialects/qssa/ops.mlir
  tests/filecheck/dialects/quantum/attrs.mlir
  tests/filecheck/transforms/convert_qref_to_qssa.mlir
  tests/filecheck/transforms/convert_qssa_to_qref.mlir
  xdsl/dialects/__init__.py
  xdsl/dialects/qref.py
  xdsl/dialects/qssa.py
  xdsl/dialects/quantum.py
Labels: enhancement, dialects

#2889 api: add generic parameter to attribute constraint
  tests/test_is_satisfying_hint.py
  xdsl/irdl/attributes.py
  xdsl/irdl/constraints.py
  xdsl/utils/isa.py
Labels: API

#2890 api: use constraints to carry type information in pyrdl
  docs/Toy/toy/dialects/toy.py
  tests/irdl/test_attr_constraint.py
  tests/irdl/test_operation_definition.py
  tests/test_is_satisfying_hint.py
  tests/test_pyrdl.py
  xdsl/dialects/arith.py
  xdsl/dialects/builtin.py
  xdsl/dialects/csl/csl.py
  xdsl/dialects/experimental/aie.py
  xdsl/dialects/fsm.py
  xdsl/dialects/hw.py
  xdsl/dialects/irdl/pyrdl_to_irdl.py
  xdsl/dialects/pdl.py
  xdsl/dialects/riscv.py
  xdsl/dialects/stencil.py
  xdsl/interpreters/irdl.py
  xdsl/interpreters/memref.py
  xdsl/interpreters/ml_program.py
  xdsl/interpreters/tensor.py
  xdsl/irdl/attributes.py
  xdsl/irdl/constraints.py
  xdsl/irdl/operations.py
  xdsl/parser/attribute_parser.py
  xdsl/utils/isattr.py
Labels: API

#2880 docs: (marimo) prettify onnx notebook
  docs/marimo/mlir/onnx_demo.py
  xdsl/dialects/riscv.py
Labels: documentation

#2892 testing: fix irdl-to-pyrdl filecheck
  tests/filecheck/dialects/irdl/irdl-to-pyrdl/testd.irdl.mlir
Labels: testing

#2893 api: use new base helper in more operation definitions
  xdsl/dialects/builtin.py
  xdsl/dialects/csl/csl_stencil.py
  xdsl/dialects/experimental/dmp.py
  xdsl/dialects/linalg.py
  xdsl/dialects/llvm.py
  xdsl/dialects/memref.py
  xdsl/dialects/memref_stream.py
  xdsl/dialects/mpi.py
  xdsl/dialects/omp.py
  xdsl/dialects/onnx.py
  xdsl/dialects/riscv.py
  xdsl/dialects/stencil.py
  xdsl/dialects/stream.py
  xdsl/interpreters/arith.py
  xdsl/transforms/stencil_to_csl_stencil.py
Labels: API

#2895 ci: ignore more pyright errors in the frontend
  tests/filecheck/frontend/dialects/affine.py
  tests/test_traits.py
  xdsl/frontend/dialects/builtin.py
  xdsl/frontend/type_conversion.py
Labels: CI, frontend

#2899 dialects: (Qref) fix bug in cnot initialiser
  xdsl/dialects/qref.py
Labels: bug, dialects, minor

#2908 (transform): csl_stencil erase merged prefetch op
  tests/filecheck/transforms/stencil-to-csl-stencil.mlir
  xdsl/transforms/stencil_to_csl_stencil.py
Labels: minor, transformations

#2905 bug: ship cmath.irdl file in pypi
  pyproject.toml
Labels: bug

#2906 bug: wrong dataclass imported in stencil_tensorize_z_dimension
  xdsl/transforms/experimental/stencil_tensorize_z_dimension.py
Labels: bug

#2912 testing: add ssum testcase to bottom-up tests
  tests/filecheck/projects/riscv-backend-paper/bottom_up.mlir
Labels: testing

#2913 dialects: (riscv_snitch) add fastmath flags in vector ops
  tests/filecheck/dialects/riscv_snitch/ops.mlir
  xdsl/dialects/riscv_snitch.py
Labels: dialects

#2914 transformations: add convert-arith-to-riscv-snitch pass
  tests/filecheck/backend/riscv/convert_arith_to_riscv_snitch.mlir
  xdsl/backend/riscv/lowering/convert_arith_to_riscv_snitch.py
  xdsl/tools/command_line_tool.py
  xdsl/transforms/test_lower_memref_stream_to_snitch_stream.py
Labels: transformations

#2923 backend: (riscv) add a reserve_registers helper to register queue
  xdsl/backend/riscv/register_allocation.py
  xdsl/backend/riscv/register_queue.py
Labels: backend

#2915 transformations: handle packed simd vectors in stream op lowering
  tests/filecheck/transforms/convert_memref_stream_to_snitch_stream.mlir
  xdsl/transforms/convert_memref_stream_to_snitch_stream.py
Labels: transformations

#2925 transformations: (snitch) add comments when lowering snitch config ops
  tests/filecheck/dialects/snitch/snitch_to_riscv_lowering.mlir
  tests/filecheck/projects/riscv-backend-paper/bottom_up.mlir
  xdsl/dialects/riscv.py
  xdsl/transforms/lower_snitch.py
Labels: transformations

#2924 backend: (riscv) add allocate_same method to register allocator
  tests/backend/riscv/test_register_allocation.py
  xdsl/backend/riscv/register_allocation.py
Labels: backend

#2916 transformations: don't check element type of memref_stream operands
  tests/filecheck/projects/riscv-backend-paper/bottom_up.mlir
  tests/filecheck/transforms/convert_memref_stream_to_snitch_stream.mlir
  xdsl/transforms/convert_memref_stream_to_snitch_stream.py
Labels: testing

#2920 transformations: use block argument types when streamifying
  tests/filecheck/projects/riscv-backend-paper/bottom_up.mlir
  tests/filecheck/transforms/memref_streamify.mlir
  xdsl/transforms/memref_streamify.py
Labels: transformations

#2927 dialects: (snitch_stream) add repetition to stride pattern
  tests/filecheck/dialects/snitch_stream/convert_snitch_stream_to_snitch.mlir
  tests/filecheck/projects/riscv-backend-paper/bottom_up.mlir
  tests/filecheck/projects/riscv-backend-paper/nsnet.mlir
  tests/filecheck/transforms/convert_memref_stream_to_snitch_stream.mlir
  tests/interpreters/test_snitch_stream_interpreter.py
  xdsl/backend/riscv/lowering/convert_snitch_stream_to_snitch.py
  xdsl/dialects/snitch_stream.py
Labels: dialects

#2922 core: Implement getAffine for MemrefLayout attributes
  tests/dialects/test_memref.py
  tests/filecheck/parser-printer/affine_map.mlir
  tests/filecheck/transforms/memref_stream_tile_outer_loops.mlir
  tests/transforms/test_convert_memref_stream_to_snitch_stream.py
  xdsl/dialects/builtin.py
  xdsl/ir/affine/affine_expr.py
  xdsl/ir/affine/affine_map.py
  xdsl/transforms/convert_memref_stream_to_snitch_stream.py
  xdsl/transforms/memref_stream_tile_outer_loops.py
Labels: core

#2903 docs: (marimo) move non-onnx part of notebook to main marimo folder
  docs/marimo/IR_Chapter_1_Attributes.py
  docs/marimo/linalg_snitch.py
  docs/marimo/mlir/onnx_demo.py
Labels: documentation

#2910 core: clone block argument name hints
  tests/filecheck/dialects/stencil/oec-kernels/fvtp2d_qi.mlir
  tests/filecheck/transforms/function-constant-pinning.mlir
  tests/filecheck/transforms/loop-hoist-memref/loop-nest.mlir
  tests/filecheck/transforms/loop-hoist-memref/single-loop.mlir
  tests/filecheck/transforms/stencil-storage-materialization.mlir
  tests/filecheck/transforms/stencil-unroll.mlir
  tests/test_ir.py
  xdsl/ir/core.py
Labels: core

#2930 backend: add RegisterConstraints and use in riscv backend
  tests/backend/riscv/test_register_allocation.py
  xdsl/backend/register_allocatable.py
  xdsl/backend/riscv/register_allocation.py
  xdsl/dialects/riscv.py
  xdsl/transforms/canonicalization_patterns/riscv.py
Labels: backend

#2921 interpreter: support callable operation impls
  docs/Toy/toy/interpreter.py
  tests/interpreters/test_riscv_func_interpreter.py
  tests/interpreters/test_wgpu.py
  tests/test_interpreter.py
  xdsl/interpreter.py
  xdsl/interpreters/func.py
  xdsl/interpreters/riscv.py
  xdsl/interpreters/riscv_func.py
Labels: interpreter

#2931 docs: (marimo) add interpreter trace to linalg snitch notebook
  docs/marimo/linalg_snitch.py
Labels: documentation

#2932 dialects: (riscv_snitch) add vfmac.s and vfsum.s
  tests/filecheck/dialects/riscv_snitch/assembly_emission.mlir
  tests/filecheck/dialects/riscv_snitch/ops.mlir
  xdsl/dialects/riscv_snitch.py
Labels: dialects

#2909 ci: use uppercase I64, I32 etc as constraints in operation definitions
  tests/irdl/test_declarative_assembly_format.py
  xdsl/dialects/builtin.py
  xdsl/dialects/comb.py
  xdsl/dialects/experimental/aie.py
  xdsl/dialects/memref.py
  xdsl/dialects/pdl.py
  xdsl/dialects/snitch_runtime.py
Labels: CI

#2933 docs: (marimo) use carousel in linalg snitch notebook
  docs/marimo/linalg_snitch.py
Labels: documentation

#2934 dialects: (riscv_snitch) lower arith.addf on vector<4xf16> to vfadd.h
  tests/filecheck/backend/riscv/convert_arith_to_riscv_snitch.mlir
  tests/filecheck/dialects/riscv_snitch/assembly_emission.mlir
  tests/filecheck/dialects/riscv_snitch/ops.mlir
  xdsl/backend/riscv/lowering/convert_arith_to_riscv_snitch.py
  xdsl/dialects/riscv_snitch.py
Labels: backend

#2929 transformations: (memref_stream) add memref_stream.generic legalization pass
  tests/filecheck/projects/riscv-backend-paper/bottom_up.mlir
  tests/filecheck/transforms/memref_stream_legalize.mlir
  xdsl/tools/command_line_tool.py
  xdsl/transforms/memref_stream_legalize.py
  xdsl/transforms/test_optimise_memref_stream.py
Labels: transformations

#2939 misc: use constraints in more operation definitions
  xdsl/dialects/accfg.py
  xdsl/dialects/csl/csl_wrapper.py
  xdsl/dialects/experimental/air.py
  xdsl/dialects/experimental/math.py
  xdsl/dialects/func.py
Labels: misc

#2948 misc: move print_csl import away from top level
  xdsl/xdsl_opt_main.py
Labels: minor

#2814 (transform): csl_stencil canonicalization pass
  tests/filecheck/dialects/csl/csl-stencil-canonicalize.mlir
  xdsl/dialects/csl/csl_stencil.py
  xdsl/transforms/canonicalization_patterns/csl_stencil.py
Labels: minor, transformations

#2891 (transform): csl_wrapper program module init
  tests/filecheck/transforms/csl-stencil-to-csl-wrapper.mlir
  xdsl/dialects/csl/csl_stencil.py
  xdsl/dialects/csl/csl_wrapper.py
  xdsl/transforms/csl_stencil_to_csl_wrapper.py
Labels: transformations

#2949 (bug): fix csl_stencil canonicalise
  tests/filecheck/dialects/csl/csl-stencil-canonicalize.mlir
Labels: bug

#2953 misc: remove some pylance errors throughout the project [NFC]
  tests/test_printer.py
  xdsl/dialects/builtin.py
  xdsl/dialects/fsm.py
  xdsl/dialects/hw.py
  xdsl/interpreters/ptr.py
  xdsl/rewriting/composable_rewriting/immutable_ir/immutable_ir.py
  xdsl/transforms/experimental/function_constant_pinning.py
  xdsl/transforms/experimental/hls_convert_stencil_to_ll_mlir.py
Labels: misc

#2950 misc: make version lazy
  xdsl/__init__.py
Labels: minor, misc

#2952 misc: use more isattr checks
  tests/dialects/test_arith.py
  xdsl/dialects/builtin.py
  xdsl/transforms/lower_mpi.py
Labels: minor, misc

#2940 api: remove parameters field from Trait
  tests/test_traits.py
  xdsl/dialects/csl/csl.py
  xdsl/dialects/csl/csl_stencil.py
  xdsl/dialects/stencil.py
  xdsl/ir/core.py
  xdsl/traits.py
Labels: API

#2946 misc: move IRDLDialectLoader to own file and remove circular dependency
  xdsl/__init__.py
  xdsl/dialects/__init__.py
  xdsl/utils/dialect_loader.py
  xdsl/utils/dialect_stub.py
Labels: misc

#2956 backend: (snitch) add an optimization-level option to linalg-snitch pass
  tests/filecheck/projects/riscv-backend-paper/nsnet.mlir
  tests/transforms/test_test_lower_linalg_to_snitch.py
  xdsl/transforms/test_lower_linalg_to_snitch.py
Labels: backend

#2947 (dialects): improving stencil attr syntax mlir compatibility
  tests/dialects/test_stencil.py
  tests/filecheck/dialects/csl/csl-stencil-canonicalize.mlir
  tests/filecheck/dialects/csl/csl-stencil-ops.mlir
  tests/filecheck/dialects/stencil/canonicalize.mlir
  tests/filecheck/dialects/stencil/invalid.mlir
  tests/filecheck/dialects/stencil/oec-kernels/fvtp2d_qi.mlir
  tests/filecheck/dialects/stencil/stencil_ops.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/stencil/hdiff.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/stencil/ops.mlir
  tests/filecheck/transforms/convert-stencil-to-ll-mlir.mlir
  tests/filecheck/transforms/csl-stencil-to-csl-wrapper.mlir
  tests/filecheck/transforms/distribute-stencil.mlir
  tests/filecheck/transforms/stencil-shape-inference.mlir
  tests/filecheck/transforms/stencil-storage-materialization.mlir
  tests/filecheck/transforms/stencil-tensorize-z-dimension.mlir
  tests/filecheck/transforms/stencil-to-csl-stencil.mlir
  tests/filecheck/transforms/stencil-unroll.mlir
  xdsl/dialects/stencil.py
Labels: invalid, dialects

#2957 (bug): linalg named ops to include hidden regions in generic print
  tests/filecheck/dialects/linalg/linalg_ops.mlir
  xdsl/dialects/linalg.py
Labels: bug, help wanted, dialects

#2961 backend: (riscv) fix register allocation stats
  tests/backend/riscv/test_register_allocation.py
  tests/filecheck/backend/riscv/register-allocation/preallocated.mlir
  tests/filecheck/projects/riscv-backend-paper/bottom_up.mlir
  tests/filecheck/projects/riscv-backend-paper/nsnet.mlir
  xdsl/backend/riscv/register_allocation.py
Labels: bug, backend

#2951 api: deprecate `print_string_raw` in favor of indent=0
  tests/test_printer.py
  xdsl/dialects/affine.py
  xdsl/dialects/memref.py
  xdsl/dialects/snitch_stream.py
  xdsl/dialects/utils.py
  xdsl/printer.py
Labels: API

#2967 misc: don't import riscv and x86 in xdsl-opt
  xdsl/xdsl_opt_main.py
Labels: misc
