Repository xdslproject/xdsl, pull requests merged in 2024-12, with the labels that each got.

#3528 tool: (irdl-to-pyrdl) Generate better class name
  tests/dialects/test_irdl.py
  tests/filecheck/dialects/irdl/irdl-to-pyrdl/testd.irdl.mlir
  xdsl/dialects/irdl/irdl.py
  xdsl/dialects/irdl/irdl_to_pyrdl.py
Labels: tool

#3551 core: fix (and test) operands/results directives with no variadics
  tests/irdl/test_declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format.py
Labels: bug, minor, core

#3517 core: add functional-type directive
  tests/irdl/test_declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format_parser.py
Labels: core

#3550 dialects: (builtin) move value range helper definitions to utils
  xdsl/dialects/builtin.py
  xdsl/utils/comparisons.py
Labels: dialects

#3552 core: fix bitwidth 0 value range
  tests/utils/test_comparisons.py
  xdsl/utils/comparisons.py
Labels: core

#3557 dialects: (arith) add muli canonicalization
  tests/filecheck/dialects/arith/canonicalize.mlir
  tests/interactive/test_app.py
  xdsl/dialects/arith.py
  xdsl/transforms/canonicalization_patterns/arith.py
Labels: dialects

#3562 minor: (csl-wrapper-hoist-buffers) Always use good name hints
  tests/filecheck/transforms/csl-wrapper-hoist-buffers.mlir
  xdsl/transforms/csl_wrapper_hoist_buffers.py
Labels: minor, hackathon

#3559 core: allow result variadic inference
  tests/irdl/test_declarative_assembly_format.py
  xdsl/irdl/constraints.py
  xdsl/irdl/declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format_parser.py
Labels: core

#3546 dialects (arm): add func op
  tests/dialects/test_arm_func.py
  tests/filecheck/dialects/arm_func/arm_func_ops.mlir
  tests/filecheck/dialects/arm_func/test_ops.mlir
  xdsl/dialects/arm_func.py
Labels: dialects

#3564 dialects: (arith) add Cmpi canonicalization
  tests/filecheck/dialects/arith/canonicalize.mlir
  xdsl/dialects/arith.py
  xdsl/transforms/canonicalization_patterns/arith.py
Labels: dialects

#3558 dialects: (csl) handle negative-valued task ID representation
  tests/filecheck/backend/csl/print_csl.mlir
  tests/filecheck/dialects/csl/ops.mlir
  tests/filecheck/transforms/csl-stencil-handle-async-flow.mlir
  tests/filecheck/transforms/lower-csl-stencil.mlir
  xdsl/backend/csl/print_csl.py
  xdsl/dialects/csl/csl.py
Labels: bug, dialects

#3450 misc: use experimental TypeForm feature of Pyright
  pyproject.toml
  tests/pattern_rewriter/test_pattern_rewriter.py
  tests/test_is_satisfying_hint.py
  xdsl/transforms/csl_stencil_bufferize.py
  xdsl/transforms/shape_inference_patterns/stencil.py
  xdsl/transforms/varith_transformations.py
  xdsl/utils/hints.py
  xdsl/utils/isattr.py
Labels: misc

#3567 documentation: add experimental features flag guide to README
  README.md
Labels: documentation

#3563 dialects: (arith) add addi constant propagation
  tests/filecheck/dialects/arith/canonicalize.mlir
  tests/filecheck/dialects/csl/csl-canonicalize.mlir
  tests/interactive/test_app.py
  xdsl/dialects/arith.py
  xdsl/transforms/canonicalization_patterns/arith.py
Labels: dialects

#3568 bug: add __init__.py
  xdsl/interpreters/utils/__init__.py
Labels: bug

#3495 dialects: (bufferization) fix materialize_in_destination
  tests/filecheck/dialects/bufferization/bufferization_ops.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/bufferization/ops.mlir
  xdsl/dialects/bufferization.py
Labels: bug, dialects

#3556 dialects: (builtin) use truthiness in of constant IntegerAttr values
  tests/irdl/test_operation_definition.py
  xdsl/dialects/builtin.py
  xdsl/transforms/canonicalization_patterns/arith.py
  xdsl/transforms/canonicalization_patterns/cf.py
  xdsl/transforms/scf_for_loop_flatten.py
Labels: dialects

#3537 transforms: use Rewriter instead of PatternRewriter in mlir-opt
  xdsl/transforms/mlir_opt.py
Labels: transformations

#3538 transforms: use rewriter and listener in convert-stencil-to-csl-stencil
  tests/filecheck/transforms/convert-stencil-to-csl-stencil.mlir
  xdsl/transforms/convert_stencil_to_csl_stencil.py
Labels: transformations

#3574 interpreter: (pdl) add an initial version of EqSat PDLMatcher
  tests/interpreters/test_eqsat_pdl_interpreter.py
  xdsl/interpreters/eqsat_pdl.py
Labels: interpreter

#3554 dialects: (builtin) normalize signless values on init
  tests/dialects/test_builtin.py
  tests/filecheck/dialects/builtin/attrs.mlir
  tests/filecheck/transforms/inline-snrt.mlir
  xdsl/dialects/builtin.py
Labels: dialects

#3582 interactive: fix dark mode
  tests/interactive/test_app.py
  xdsl/interactive/app.py
Labels: bug, minor, interactive

#3575 transformations: (convert-stencil-to-csl-stencil) Support multiple input buffers
  tests/filecheck/transforms/convert-stencil-to-csl-stencil.mlir
  xdsl/transforms/convert_stencil_to_csl_stencil.py
Labels: bug, hackathon, transformations

#3581 dialects: (builtin) add PackableType and StructPackableType
  tests/dialects/test_builtin.py
  xdsl/dialects/builtin.py
Labels: dialects

#3586 interpreter: replace XType with FixedBitwidthPyBackedType
  xdsl/interpreters/builtin.py
  xdsl/interpreters/onnx.py
  xdsl/interpreters/utils/ptr.py
Labels: interpreter

#3587 dialects: (builtin) replace DenseArrayBase's data array with bytes
  tests/dialects/test_builtin.py
  tests/filecheck/dialects/builtin/attrs.mlir
  tests/test_printer.py
  xdsl/dialects/builtin.py
Labels: dialects

#3589 misc: remove with_context helper on ParseError [NFC]
  xdsl/tools/command_line_tool.py
  xdsl/utils/exceptions.py
Labels: minor, misc

#3590 CI: set maxIndividualTestTime in lit cfg
  tests/filecheck/lit.cfg
Labels: CI

#3601 interactive: small refactor
  tests/interactive/test_rewrites.py
  xdsl/interactive/rewrites.py
Labels: minor, interactive

#3602 transformations: (apply-individual-rewrite) give more context in error message [NFC]
  xdsl/transforms/individual_rewrite.py
Labels: misc

#3600 core: split print_float into print_float and print_float_attr
  tests/test_printer.py
  xdsl/dialects/builtin.py
  xdsl/printer.py
Labels: core

#3604 core (traits): Fix implicit terminator when last op is unregistered
  tests/filecheck/dialects/scf/unregistered.mlir
  xdsl/traits.py
Labels: core

#3603 transformations: (apply-individual-rewrite) improve error message
  xdsl/transforms/individual_rewrite.py
Labels: minor, transformations

#3591 core: move logic specific to the MLIR grammar from lexer to mlir_lexer
  bench/parser/bench_lexer.py
  tests/test_lexer.py
  tests/test_parser.py
  xdsl/ir/core.py
  xdsl/irdl/declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format_parser.py
  xdsl/parser/affine_parser.py
  xdsl/parser/attribute_parser.py
  xdsl/parser/base_parser.py
  xdsl/parser/core.py
  xdsl/printer.py
  xdsl/utils/lexer.py
  xdsl/utils/mlir_lexer.py
  xdsl/utils/parse_pipeline.py
Labels: core

#3592 core: rename MLIR-specific lexing constructs
  bench/parser/bench_lexer.py
  tests/test_lexer.py
  tests/test_parser.py
  xdsl/ir/core.py
  xdsl/irdl/declarative_assembly_format_parser.py
  xdsl/parser/affine_parser.py
  xdsl/parser/attribute_parser.py
  xdsl/parser/base_parser.py
  xdsl/parser/core.py
  xdsl/printer.py
  xdsl/utils/lexer.py
  xdsl/utils/mlir_lexer.py
Labels: core

#3593 documentation: use generic lexer infrastructure in Toy parser
  docs/Toy/toy/frontend/lexer.py
  docs/Toy/toy/frontend/location.py
  docs/Toy/toy/frontend/parser.py
  docs/Toy/toy/tests/test_parser.py
Labels: documentation

#3594 misc: hide base_parser, and avoid circular imports in parser files
  pyproject.toml
  xdsl/parser/affine_parser.py
  xdsl/parser/attribute_parser.py
  xdsl/parser/core.py
Labels: minor, misc

#3606 interactive: do not auto_expand passes_list
  tests/interactive/test_app.py
  xdsl/interactive/app.py
Labels: bug, interactive

#3595 core: split out non-MLIR-specific parser functionality to GenericParser
  pyproject.toml
  tests/filecheck/parser-printer/aliases.mlir
  tests/test_parser.py
  xdsl/parser/__init__.py
  xdsl/parser/affine_parser.py
  xdsl/parser/base_parser.py
  xdsl/parser/core.py
  xdsl/parser/generic_parser.py
Labels: core

#2615 transformations: Implement stencil inlining.
  tests/filecheck/transforms/stencil-inlining.mlir
  xdsl/transforms/__init__.py
  xdsl/transforms/stencil_inlining.py
  xdsl/transforms/stencil_unroll.py
Labels: transformations

#3599 dialects: (builtin) add CompileTimeFixedBitwidthType
  tests/dialects/test_builtin.py
  xdsl/dialects/builtin.py
  xdsl/interpreters/utils/ptr.py
Labels: dialects

#3616 minor: (convert-stencil-to-csl-stencil) Adding accidentally removed filecheck back in
  tests/filecheck/transforms/convert-stencil-to-csl-stencil.mlir
Labels: minor

#3618 dialects (func): Use assembly format in `func.call` operation
  xdsl/dialects/func.py
Labels: dialects

#3617 misc (Makefile): Update coverage handling in Makefile
  .coveragerc
  Makefile
Labels: misc

#3622 dialects (riscv_func): Use assembly format for `riscv_func.call` operation
  xdsl/dialects/riscv_func.py
  xdsl/dialects/utils/format.py
Labels: dialects

#3625 dialects: (builtin) apply normalization on ints, not IntAttrs
  tests/dialects/test_builtin.py
  xdsl/dialects/builtin.py
Labels: dialects

#3624 CI: exclude frontend filecheck tests from coverage
  .coveragerc
Labels: CI

#3615 misc: add wgsl target and move module printing test case to filecheck
  tests/backend/wgsl/test_wgsl_printer.py
  tests/filecheck/backend/wgsl/2d5pt.mlir
  tests/interpreters/test_wgsl_printer.py
  xdsl/backend/wgsl/wgsl_printer.py
  xdsl/interpreters/wgpu.py
  xdsl/xdsl_opt_main.py
Labels: misc

#3294 installation: Switch to UV for dependency management
  .github/workflows/ci-core.yml
  .github/workflows/ci-mlir.yml
  .github/workflows/ci-notebooks.yml
  .github/workflows/ci-pyright-fails.yml
  .github/workflows/code-formatting.yml
  .github/workflows/jupyterlite.yml
  .github/workflows/pythonpublish.yml
  .github/workflows/update-bot.yml
  Makefile
  README.md
  flake.nix
  pyproject.toml
  requirements.txt
  tests/dialects/test_builtin.py
  uv.lock
Labels: installation

#3613 API: split out MLIR-independent printing into BasePrinter and use in STIM [NFC]
  tests/test_printer.py
  tests/utils/test_base_printer.py
  xdsl/dialects/stim/stim_printer_parser.py
  xdsl/printer.py
  xdsl/utils/base_printer.py
Labels: API

#3607 dialects: (builtin) mimic mlir floating point precision for printing and parsing
  tests/filecheck/backend/csl/print_csl.mlir
  tests/filecheck/dialects/arith/canonicalize.mlir
  tests/filecheck/dialects/csl/ops.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/builtin/builtin_fp_types.mlir
  tests/filecheck/parser-printer/builtin_attrs.mlir
  tests/filecheck/parser-printer/float_parsing.mlir
  tests/filecheck/transforms/convert-stencil-to-csl-stencil.mlir
  tests/filecheck/transforms/csl-stencil-handle-async-flow.mlir
  tests/filecheck/transforms/linalg-fuse-multiply-add.mlir
  tests/filecheck/transforms/linalg-to-csl.mlir
  tests/filecheck/transforms/lower-csl-stencil.mlir
  tests/test_printer.py
  xdsl/dialects/builtin.py
  xdsl/printer.py
Labels: dialects

#3626 misc (Makefile): Fix custom `venv` treatment in Makefile
  Makefile
Labels: bug, misc

#3629 misc: use .venv by default instead of venv
  .github/workflows/ci-core.yml
  .github/workflows/ci-mlir.yml
  .github/workflows/ci-notebooks.yml
  .github/workflows/ci-pyright-fails.yml
  Makefile
Labels: misc

#3628 CI: install wgpu and onnx in mlir ci
  .github/workflows/ci-mlir.yml
Labels: CI

#3585 dialects: (builtin) add IntegerAttr truncation and use in individual rewrite
  tests/dialects/test_builtin.py
  tests/filecheck/transforms/individual_rewrite/add-same.mlir
  tests/filecheck/transforms/individual_rewrite/riscv.mlir
  xdsl/dialects/builtin.py
  xdsl/transforms/individual_rewrite.py
Labels: bug, minor, transformations

#3636 dependencies: update textual lockfile
  uv.lock
Labels: dependencies

#3635 dialects: (arith) add truncation option to ConstantOp
  tests/dialects/test_arith.py
  xdsl/dialects/arith.py
Labels: dialects, minor

#3637 dialects: (builtin) constrain DensIntOrFPElementsattr to the correct nb of elements
  tests/dialects/test_builtin.py
  tests/interpreters/test_ml_program_interpreter.py
  xdsl/dialects/builtin.py
Labels: dialects

#3638 dependencies: update ruff
  uv.lock
Labels: dependencies

#3631 transformations: (apply-individual-rewrite) lazily find canonicalization patterns
  tests/interactive/test_app.py
  tests/interactive/test_rewrites.py
  xdsl/interactive/app.py
  xdsl/interactive/rewrites.py
  xdsl/transforms/individual_rewrite.py
Labels: transformations

#3639 CI: fail CI if lockfile is out of sync with project
  .github/workflows/ci-lockfile.yml
  Makefile
  setup.py
  uv.lock
Labels: CI

#3642 interactive: use individual rewrite pass directly instead of helpers
  tests/interactive/test_app.py
  tests/interactive/test_rewrites.py
  xdsl/interactive/get_all_available_passes.py
  xdsl/interactive/rewrites.py
Labels: interactive

#3621 misc: add a DisjointSet data structure
  tests/utils/test_disjoint_set.py
  xdsl/utils/disjoint_set.py
Labels: misc

#3630 misc: use activated venv dir if any, and add back project venv export
  Makefile
Labels: misc

#3647 CI: add lockfile update action to manually trigger for dependabot PRs
  .github/workflows/update-bot.yml
  .github/workflows/update-lockfile-bot.yml
Labels: CI

#3583 dialects: (arith) add SignlessIntegerBinaryOperation canonicalization
  tests/filecheck/dialects/arith/canonicalize.mlir
  tests/interactive/test_app.py
  xdsl/dialects/arith.py
  xdsl/traits.py
  xdsl/transforms/canonicalization_patterns/arith.py
  xdsl/transforms/canonicalization_patterns/cf.py
  xdsl/transforms/canonicalization_patterns/scf.py
  xdsl/transforms/canonicalization_patterns/utils.py
Labels: dialects

#3539 transforms: Allow to pass a pattern rewriter in CSE
  xdsl/transforms/canonicalization_patterns/stencil.py
  xdsl/transforms/common_subexpression_elimination.py
  xdsl/transforms/control_flow_hoist.py
Labels: transformations

#3652 dialects (func): Add SymbolUserOpInterface implementation for `func.call` operation
  tests/dialects/test_func.py
  tests/filecheck/dialects/func/func_invalid.mlir
  xdsl/dialects/func.py
  xdsl/traits.py
Labels: dialects, core

#3614 bug: (csl-lowering) Make multi-apply lowering work
  tests/filecheck/transforms/convert-stencil-to-csl-stencil.mlir
  xdsl/transforms/convert_stencil_to_csl_stencil.py
  xdsl/transforms/csl_stencil_bufferize.py
  xdsl/transforms/experimental/stencil_tensorize_z_dimension.py
  xdsl/transforms/memref_to_dsd.py
Labels: bug, minor

#3649 dialects: (vector) Add vector.insertelement and vector.extractelement
  tests/dialects/test_vector.py
  tests/filecheck/dialects/vector/vector_extractelement_verify.mlir
  tests/filecheck/dialects/vector/vector_insertelement_verify.mlir
  tests/filecheck/dialects/vector/vector_pure_ops.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/vector/ops.mlir
  xdsl/dialects/vector.py
Labels: dialects

#3657 dialects: (csl) Switch dsds to use affine maps
  tests/filecheck/backend/csl/print_csl.mlir
  tests/filecheck/dialects/csl/csl-canonicalize.mlir
  tests/filecheck/dialects/csl/ops.mlir
  tests/filecheck/transforms/lower-csl-stencil.mlir
  xdsl/backend/csl/print_csl.py
  xdsl/dialects/csl/csl.py
  xdsl/transforms/canonicalization_patterns/csl.py
  xdsl/transforms/lower_csl_stencil.py
Labels: dialects

#3658 interactive: add mlir-opt pass to condensed list
  xdsl/interactive/passes.py
Labels: interactive

#3663 transformations: (csl-stencil-bufferize) AccessOp to read to_tensor's underlying memref
  xdsl/transforms/csl_stencil_bufferize.py
Labels: dialects, minor

#3661 core: Add attributes to func outputs
  tests/filecheck/dialects/func/func_ops.mlir
  tests/filecheck/dialects/func/func_ops_generic.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/func/func_ops.mlir
  xdsl/dialects/arm_func.py
  xdsl/dialects/csl/csl.py
  xdsl/dialects/func.py
  xdsl/dialects/riscv_func.py
  xdsl/dialects/utils/format.py
Labels: core

#3665 interactive: remove unused spec variable from `get_pass_arguments` function
  xdsl/interactive/app.py
Labels: interactive

#3669 core: Parse `module` correctly when `allow-unregistered-dialect` is set
  tests/filecheck/dialects/builtin/module.mlir
  tests/test_mlcontext.py
  tests/test_printer.py
  xdsl/context.py
  xdsl/parser/core.py
Labels: bug, core

#3673 misc: remove unnecessary debug print statement
  tests/test_mlcontext.py
Labels: minor, misc

#3660 installation: add mechanism for symlinking mlir-opt when creating venv
  Makefile
  README.md
Labels: installation

#3664 dialects: (builtin) Parse @ module names
  tests/filecheck/dialects/builtin/module.mlir
  xdsl/dialects/builtin.py
Labels: dialects

#3675 core: fix attributes to func outputs
  tests/filecheck/dialects/func/func_ops.mlir
  xdsl/dialects/utils/format.py
Labels: core

#3676 testing: split bottom_up into f32 and f64 kernels
  tests/filecheck/projects/riscv-backend-paper/bottom_up_f32.mlir
  tests/filecheck/projects/riscv-backend-paper/bottom_up_f64.mlir
Labels: testing

#3678 testing: raise ddot bottom_up test to linalg.generic
  tests/filecheck/projects/riscv-backend-paper/bottom_up_f64.mlir
Labels: testing
