Repository xdslproject/xdsl, pull requests merged in 2024-11, with the labels that each got.

#3356 dialects: (llvm) Registering llvm.icmp
  tests/filecheck/dialects/llvm/arithmetic.mlir
  xdsl/dialects/llvm.py
Labels: dialects

#3373 transformations: (csl-stencil-bufferize) Reselect linalg outs
  tests/filecheck/transforms/csl_stencil_bufferize.mlir
  xdsl/transforms/csl_stencil_bufferize.py
Labels: transformations

#3371 misc: move `get_all_passes` to xdsl.transforms
  tests/test_cli.py
  tests/xdsl_opt/test_xdsl_opt.py
  xdsl/interactive/app.py
  xdsl/interactive/passes.py
  xdsl/tools/command_line_tool.py
  xdsl/transforms/__init__.py
  xdsl/xdsl_opt_main.py
Labels: misc

#3376 canonicalisation: (arith) Zero division result fix
  xdsl/transforms/canonicalization_patterns/arith.py
Labels: bug, minor

#3375 dialects: (llvm) fixed generic printing of llvm.icmp
  tests/filecheck/dialects/llvm/icmp.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/llvm/icmp.mlir
  xdsl/dialects/llvm.py
Labels: dialects

#3361 misc: fix tests that secretly rely on optional dependencies
  .github/workflows/ci-core.yml
  .github/workflows/ci-mlir.yml
  Makefile
  docs/marimo/linalg_snitch.py
  docs/marimo/mlir/README.md
  docs/marimo/onnx/README.md
  docs/marimo/onnx/onnx_demo.py
  tests/backend/test_jax_executable.py
  tests/frontend/jaxpr/test_build_jaxpr_ir.py
  tests/interactive/test_app.py
  xdsl/interactive/_pasteboard.py
Labels: misc

#3363 API: use OpTraits to define traits on operations
  docs/Toy/toy/dialects/toy.py
  docs/irdl.ipynb
  docs/xdsl-introduction.ipynb
  tests/backend/test_jax_executable.py
  tests/dialects/test_hw.py
  tests/dialects/test_pdl.py
  tests/irdl/test_operation_builder.py
  tests/irdl/test_operation_definition.py
  tests/test_builtin_traits.py
  tests/test_traits.py
  xdsl/dialects/accfg.py
  xdsl/dialects/affine.py
  xdsl/dialects/arith.py
  xdsl/dialects/builtin.py
  xdsl/dialects/cf.py
  xdsl/dialects/csl/csl.py
  xdsl/dialects/csl/csl_stencil.py
  xdsl/dialects/csl/csl_wrapper.py
  xdsl/dialects/experimental/aie.py
  xdsl/dialects/experimental/air.py
  xdsl/dialects/experimental/dmp.py
  xdsl/dialects/experimental/fir.py
  xdsl/dialects/experimental/hls.py
  xdsl/dialects/experimental/math.py
  xdsl/dialects/fsm.py
  xdsl/dialects/func.py
  xdsl/dialects/gpu.py
  xdsl/dialects/hw.py
  xdsl/dialects/irdl/irdl.py
  xdsl/dialects/linalg.py
  xdsl/dialects/llvm.py
  xdsl/dialects/memref.py
  xdsl/dialects/memref_stream.py
  xdsl/dialects/ml_program.py
  xdsl/dialects/mod_arith.py
  xdsl/dialects/omp.py
  xdsl/dialects/pdl.py
  xdsl/dialects/riscv.py
  xdsl/dialects/riscv_cf.py
  xdsl/dialects/riscv_func.py
  xdsl/dialects/riscv_scf.py
  xdsl/dialects/riscv_snitch.py
  xdsl/dialects/scf.py
  xdsl/dialects/snitch_runtime.py
  xdsl/dialects/snitch_stream.py
  xdsl/dialects/stablehlo.py
  xdsl/dialects/stencil.py
  xdsl/dialects/tensor.py
  xdsl/dialects/test.py
  xdsl/dialects/transform.py
  xdsl/dialects/varith.py
  xdsl/dialects/vector.py
  xdsl/dialects/x86/ops.py
  xdsl/ir/core.py
  xdsl/irdl/operations.py
Labels: API

#3382 API: add back traits_def, and also lazy_traits_def
  docs/Toy/toy/dialects/toy.py
  docs/irdl.ipynb
  docs/xdsl-introduction.ipynb
  tests/backend/test_jax_executable.py
  tests/dialects/test_hw.py
  tests/dialects/test_pdl.py
  tests/irdl/test_operation_builder.py
  tests/irdl/test_operation_definition.py
  tests/test_builtin_traits.py
  tests/test_traits.py
  xdsl/dialects/accfg.py
  xdsl/dialects/affine.py
  xdsl/dialects/arith.py
  xdsl/dialects/builtin.py
  xdsl/dialects/cf.py
  xdsl/dialects/csl/csl.py
  xdsl/dialects/csl/csl_stencil.py
  xdsl/dialects/csl/csl_wrapper.py
  xdsl/dialects/experimental/aie.py
  xdsl/dialects/experimental/air.py
  xdsl/dialects/experimental/dmp.py
  xdsl/dialects/experimental/fir.py
  xdsl/dialects/experimental/hls.py
  xdsl/dialects/experimental/math.py
  xdsl/dialects/fsm.py
  xdsl/dialects/func.py
  xdsl/dialects/gpu.py
  xdsl/dialects/hw.py
  xdsl/dialects/irdl/irdl.py
  xdsl/dialects/linalg.py
  xdsl/dialects/llvm.py
  xdsl/dialects/memref.py
  xdsl/dialects/memref_stream.py
  xdsl/dialects/ml_program.py
  xdsl/dialects/mod_arith.py
  xdsl/dialects/omp.py
  xdsl/dialects/pdl.py
  xdsl/dialects/riscv.py
  xdsl/dialects/riscv_cf.py
  xdsl/dialects/riscv_func.py
  xdsl/dialects/riscv_scf.py
  xdsl/dialects/riscv_snitch.py
  xdsl/dialects/scf.py
  xdsl/dialects/snitch_runtime.py
  xdsl/dialects/snitch_stream.py
  xdsl/dialects/stablehlo.py
  xdsl/dialects/stencil.py
  xdsl/dialects/tensor.py
  xdsl/dialects/test.py
  xdsl/dialects/transform.py
  xdsl/dialects/varith.py
  xdsl/dialects/vector.py
  xdsl/dialects/x86/ops.py
  xdsl/ir/core.py
  xdsl/irdl/operations.py
Labels: API

#3369 dialects: llvm fixed parsing of nested structs
  tests/filecheck/dialects/llvm/example.mlir
  xdsl/dialects/llvm.py
Labels: dialects

#3122 dialects: (stim) Add parser for .stim formatted strings
  tests/dialects/stim/test_stim_printer_parser.py
  xdsl/dialects/stim/ops.py
  xdsl/dialects/stim/stim_parser.py
  xdsl/dialects/stim/stim_printer_parser.py
Labels: dialects

#3385 backend: (riscv) remove optimization level from test-lower-linalg-to-snitch
  tests/filecheck/projects/riscv-backend-paper/nsnet.mlir
  tests/transforms/test_test_lower_linalg_to_snitch.py
  xdsl/transforms/test_lower_linalg_to_snitch.py
Labels: backend

#3381 core: Adding option to print full precision fp
  tests/filecheck/dialects/arith/canonicalize.mlir
  tests/filecheck/parser-printer/builtin_attrs.mlir
  tests/filecheck/parser-printer/float_parsing.mlir
  tests/filecheck/transforms/linalg-to-csl.mlir
  xdsl/printer.py
Labels: enhancement, core

#3377 core: Print FloatAttr special values
  tests/test_printer.py
  xdsl/printer.py
  xdsl/utils/bitwise_casts.py
Labels: bug, core

#3384 misc: move pdl, sgpu, and wgsl_printer out of experimental
  tests/interpreters/test_pdl_interpreter.py
  tests/interpreters/test_wgpu.py
  tests/interpreters/test_wgsl_printer.py
  xdsl/interpreters/__init__.py
  xdsl/interpreters/experimental/__init__.py
  xdsl/interpreters/pdl.py
  xdsl/interpreters/wgpu.py
  xdsl/interpreters/wgsl_printer.py
Labels: misc

#3392 transformations: check invalid cases in `memref` -> `ptr` conversion
  tests/filecheck/transforms/convert_memref_to_ptr.mlir
Labels: transformations

#3390 dialects: (llvm) added the 'exact' keyword to the corresponding operations
  tests/dialects/test_llvm.py
  tests/filecheck/dialects/llvm/arithmetic.mlir
  xdsl/dialects/llvm.py
Labels: dialects

#3396 bug: Fix cse for FloatData
  tests/filecheck/transforms/cse.mlir
  xdsl/dialects/builtin.py
Labels: bug

#3395 transformations: Persist func arg names as arg_attr
  tests/filecheck/transforms/function-persist-arg-names.mlir
  tests/interactive/test_app.py
  xdsl/transforms/__init__.py
  xdsl/transforms/function_transformations.py
Labels: transformations

#3379 interactive: refactor to one use of get_all_passes/get_all_dialects
  tests/interactive/test_app.py
  tests/interactive/test_get_all_available_passes.py
  xdsl/interactive/app.py
  xdsl/interactive/get_all_available_passes.py
  xdsl/interactive/passes.py
Labels: interactive

#3398 misc: reorder imports in `tests/interactive/test_app.py`
  tests/interactive/test_app.py
Labels: misc

#3397 transformations: Support declarations in func persist arg names
  tests/filecheck/transforms/function-persist-arg-names.mlir
  xdsl/transforms/function_transformations.py
Labels: minor, transformations

#3391 transformations: (pdl) Apply PDL patterns from source
  tests/filecheck/interpreters/extra_file.mlir
  tests/filecheck/interpreters/test_pdl_interpreter_extra_file.mlir
  tests/filecheck/interpreters/test_pdl_interpreter_simple.mlir
  xdsl/transforms/__init__.py
  xdsl/transforms/apply_pdl.py
Labels: transformations

#3393 transformations: `ptr` -> `riscv` conversion
  tests/filecheck/backend/riscv/convert_ptr_to_riscv.mlir
  xdsl/transforms/__init__.py
  xdsl/transforms/convert_ptr_to_riscv.py
Labels: transformations, backend

#3403 transformations: Materialise stores before bufferization
  tests/filecheck/transforms/csl_stencil_bufferize.mlir
  xdsl/transforms/csl_stencil_bufferize.py
Labels: transformations

#3408 dialects: (llvm) changed the exact attribute to a UnitAttr
  tests/dialects/test_llvm.py
  xdsl/dialects/llvm.py
Labels: dialects

#3410 testing: use test dialect and custom passes for test_get_all_available_passes
  tests/interactive/test_get_all_available_passes.py
Labels: testing

#3407 transformations: New test-add-timers-to-top-level-funcs pass
  tests/filecheck/transforms/test-add-timers-to-top-level-funcs.mlir
  xdsl/transforms/__init__.py
  xdsl/transforms/csl_stencil_to_csl_wrapper.py
  xdsl/transforms/function_transformations.py
Labels: transformations

#3420 dialects: (llvm) added the 'nneg' keyword to zext
  tests/filecheck/dialects/llvm/arithmetic.mlir
  xdsl/dialects/llvm.py
Labels: dialects

#3422 dialects: (llvm) added overflow flags to trunc
  tests/filecheck/dialects/llvm/arithmetic.mlir
  xdsl/dialects/llvm.py
Labels: dialects

#3417 transformations: (scf) loop range folding
  tests/filecheck/transforms/scf_for_loop_range_folding.mlir
  xdsl/transforms/__init__.py
  xdsl/transforms/scf_for_loop_range_folding.py
Labels: transformations

#3416 misc: raise error if variadic results types aren't referenced in assembly format
  tests/irdl/test_declarative_assembly_format.py
  xdsl/dialects/experimental/air.py
  xdsl/irdl/declarative_assembly_format.py
Labels: core, misc

#3425 misc: remove casts in assembly format implementation [NFC]
  xdsl/irdl/declarative_assembly_format.py
Labels: misc

#3414 misc: make FormatProgram truly frozen
  xdsl/irdl/declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format_parser.py
Labels: minor, misc

#3413 dialects: (scf) add assembly format to `scf.condition`
  xdsl/dialects/scf.py
Labels: dialects, minor

#3426 misc: clean up passes getters [NFC]
  tests/interactive/test_app.py
  tests/interactive/test_get_all_available_passes.py
  tests/interactive/test_rewrites.py
  xdsl/backend/riscv/riscv_scf_to_asm.py
  xdsl/frontend/passes/desymref.py
  xdsl/interactive/rewrites.py
  xdsl/transforms/__init__.py
  xdsl/transforms/eqsat_create_eclasses.py
  xdsl/transforms/experimental/dmp/stencil_global_to_local.py
  xdsl/transforms/function_transformations.py
  xdsl/transforms/individual_rewrite.py
  xdsl/transforms/inline_snrt.py
Labels: misc

#3405 transformations: (pdl) Different type matching between polymorphic and fixed case
  tests/filecheck/interpreters/test_pdl_match_type.mlir
  tests/filecheck/interpreters/test_pdl_polymorphic.mlir
  tests/interpreters/test_pdl_interpreter.py
  xdsl/interpreters/pdl.py
Labels: transformations, interpreter

#3315 transformations: add eqsat-add-costs
  tests/filecheck/transforms/eqsat-add-costs.mlir
  xdsl/transforms/__init__.py
  xdsl/transforms/eqsat_add_costs.py
Labels: transformations

#3427 testing: add one more op to eqsat-create-eclasses test
  tests/filecheck/transforms/eqsat-create-eclasses.mlir
Labels: testing, minor

#3423 transformations: (stencil-tensorize-z-dimension) Minor pipeline fixes
  xdsl/dialects/stencil.py
  xdsl/transforms/convert_stencil_to_csl_stencil.py
  xdsl/transforms/experimental/stencil_tensorize_z_dimension.py
Labels: bug

#3428 dialects: (llvm) added disjoint flag
  tests/dialects/test_llvm.py
  tests/filecheck/dialects/llvm/arithmetic.mlir
  xdsl/dialects/llvm.py
Labels: dialects

#3411 transforms: add restrict flag to StencilShapeMinimize pass
  tests/filecheck/transforms/stencil-shape-minimize.mlir
  xdsl/transforms/shape_inference.py
  xdsl/transforms/stencil_shape_minimize.py
Labels: transformations

#2468 transformations: (convert-riscv-to-llvm)
  tests/filecheck/transforms/convert_riscv_to_llvm.mlir
  xdsl/transforms/__init__.py
  xdsl/transforms/convert_riscv_to_llvm.py
Labels: enhancement, transformations, backend

#3431 misc: use preferred style for pytest parametrized tests
  pyproject.toml
  tests/dialects/test_builtin.py
  tests/dialects/test_printf.py
  tests/dialects/test_riscv_snitch.py
  tests/dialects/test_stencil.py
  tests/interpreters/test_cf_interpreter.py
  tests/interpreters/test_riscv_func_interpreter.py
  tests/interpreters/test_riscv_scf_interpreter.py
  tests/interpreters/test_scf_interpreter.py
  tests/irdl/test_declarative_assembly_format.py
  tests/riscv/test_abi_spec.py
  tests/test_dominance.py
  tests/test_pass_from_spec.py
  tests/test_pass_lexer.py
  tests/test_pass_to_arg_and_types_str.py
  tests/test_pass_to_spec.py
  tests/test_traits.py
Labels: minor, misc

#3432 dialects: (eqsat) verify that operands of eclass ops are not produced by eclass
  tests/filecheck/dialects/eqsat/eqsat_invalid.mlir
  tests/filecheck/transforms/eqsat-add-costs.mlir
  xdsl/dialects/eqsat.py
Labels: dialects

#3433 dialects: (eqsat) add min_cost_index optional attribute to eclass
  tests/filecheck/transforms/eqsat-add-costs.mlir
  xdsl/dialects/eqsat.py
  xdsl/transforms/eqsat_add_costs.py
Labels: dialects

#3430 misc: use assert_never to enforce exhaustive matches
  pyproject.toml
  tests/filecheck/backend/riscv/convert_ptr_to_riscv.mlir
  tests/test_printer.py
  xdsl/backend/riscv/lowering/convert_arith_to_riscv.py
  xdsl/backend/riscv/lowering/convert_arith_to_riscv_snitch.py
  xdsl/backend/riscv/lowering/convert_memref_to_riscv.py
  xdsl/dialects/onnx.py
  xdsl/dialects/riscv.py
  xdsl/dialects/tensor.py
  xdsl/dialects/x86/assembly.py
  xdsl/interpreters/pdl.py
  xdsl/ir/core.py
  xdsl/irdl/constraints.py
  xdsl/irdl/operations.py
  xdsl/parser/core.py
  xdsl/transforms/convert_ptr_to_riscv.py
  xdsl/transforms/lower_affine.py
  xdsl/utils/test_value.py
Labels: minor, misc

#3436 dialects: (riscv) split out the base classes for custom format and assembly printing
  xdsl/dialects/riscv.py
  xdsl/dialects/riscv_debug.py
  xdsl/dialects/riscv_snitch.py
Labels: dialects

#3412 dialects: move FastMathFlag and FastMathAttrBase to xdsl.dialects.utils
  xdsl/dialects/arith.py
  xdsl/dialects/llvm.py
  xdsl/dialects/riscv.py
  xdsl/dialects/utils.py
  xdsl/transforms/arith_add_fastmath.py
  xdsl/transforms/canonicalization_patterns/riscv.py
Labels: dialects

#3438 misc: replace return_op_like format helpers with assembly_format
  xdsl/dialects/func.py
  xdsl/dialects/riscv_func.py
  xdsl/dialects/utils.py
Labels: misc

#3437 misc: cleanup leftover ConstraintVar
  xdsl/dialects/stencil.py
  xdsl/dialects/x86/ops.py
Labels: minor, misc

#3434 transformations: add eqsat-extract
  tests/filecheck/transforms/eqsat-extract.mlir
  xdsl/dialects/eqsat.py
  xdsl/transforms/__init__.py
  xdsl/transforms/eqsat_add_costs.py
  xdsl/transforms/eqsat_extract.py
Labels: transformations

#3439 rewriting: add attr_constr_rewrite_pattern
  tests/pattern_rewriter/test_pattern_rewriter.py
  xdsl/pattern_rewriter.py
Labels: rewriting

#3440 dialects: (stream) add constr to StreamType base class
  xdsl/dialects/memref_stream.py
  xdsl/dialects/stream.py
Labels: dialects

#3429 dialects: (accfg) Update ACCFG dialect to match version in snax-mlir
  tests/filecheck/dialects/accfg/accfg_ops.mlir
  xdsl/dialects/accfg.py
Labels: dialects

#3441 core: use & for AllOf constraint
  xdsl/dialects/builtin.py
  xdsl/irdl/constraints.py
Labels: minor, core

#3442 misc: Stencil and csl lowering fixes
  tests/filecheck/transforms/test-add-timers-to-top-level-funcs.mlir
  xdsl/dialects/stencil.py
  xdsl/transforms/canonicalization_patterns/stencil.py
  xdsl/transforms/csl_stencil_handle_async_flow.py
  xdsl/transforms/function_transformations.py
Labels: bug, misc

#3451 dialects: (bufferization) add custom syntax to alloc_tensor
  tests/filecheck/dialects/bufferization/bufferization_ops.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/bufferization/ops.mlir
  xdsl/dialects/bufferization.py
Labels: dialects

#3463 dialects (arm): add custom syntax
  tests/filecheck/dialects/arm/test_ops.mlir
  xdsl/dialects/arm/ops.py
Labels: dialects

#3457 interpreter: (pdl) fix match_operand matching for already matched value
  tests/interpreters/test_pdl_interpreter.py
  xdsl/interpreters/pdl.py
Labels: interpreter

#3465 interpreter: (pdl) add test for result matching
  tests/interpreters/test_pdl_interpreter.py
Labels: interpreter

#3466 interpreter: (pdl) add test for operation matching
  tests/interpreters/test_pdl_interpreter.py
Labels: interpreter

#3467 interpreter: (pdl) add test for attribute matching
  tests/interpreters/test_pdl_interpreter.py
Labels: interpreter

#3470 dialects: (stream) remove unused stream.read and stream.write ops
  tests/filecheck/dialects/stream/ops.mlir
  tests/interpreters/test_riscv_snitch_interpreter.py
  tests/interpreters/test_stream_interpreter.py
  xdsl/dialects/stream.py
  xdsl/interpreters/snitch_stream.py
  xdsl/interpreters/stream.py
  xdsl/interpreters/utils/stream.py
Labels: dialects

#3471 interpreter: move ptr.py to utils folder
  docs/Toy/toy/interpreter.py
  docs/marimo/linalg_snitch.py
  tests/interpreters/test_affine_interpreter.py
  tests/interpreters/test_builtin_interpreter.py
  tests/interpreters/test_linalg_interpreter.py
  tests/interpreters/test_memref_interpreter.py
  tests/interpreters/test_memref_stream_interpreter.py
  tests/interpreters/test_ml_program_interpreter.py
  tests/interpreters/test_onnx_interpreter.py
  tests/interpreters/test_ptr.py
  tests/interpreters/test_riscv_interpreter.py
  tests/interpreters/test_shaped_array.py
  tests/interpreters/test_snitch_stream_interpreter.py
  tests/interpreters/test_tensor_interpreter.py
  xdsl/backend/riscv/lowering/convert_memref_to_riscv.py
  xdsl/interpreters/builtin.py
  xdsl/interpreters/memref.py
  xdsl/interpreters/ml_program.py
  xdsl/interpreters/onnx.py
  xdsl/interpreters/riscv.py
  xdsl/interpreters/riscv_libc.py
  xdsl/interpreters/shaped_array.py
  xdsl/interpreters/snitch_stream.py
  xdsl/interpreters/tensor.py
  xdsl/interpreters/utils/ptr.py
Labels: interpreter

#3462 dialects (arm): add first operation
  tests/filecheck/dialects/arm/test_ops.mlir
  xdsl/dialects/arm/__init__.py
  xdsl/dialects/arm/ops.py
  xdsl/dialects/riscv.py
  xdsl/dialects/x86/ops.py
Labels: dialects

#3475 dialects: (bufferization) Simplify tensor/memref constraint
  tests/dialects/test_bufferization.py
  xdsl/dialects/bufferization.py
Labels: dialects

#3479 testing: update path to wgpu interpreter for pyright exclusion
  pyproject.toml
Labels: testing

#3477 core: (irdl) ParamAttrConstraint can infer recursively
  tests/irdl/test_attr_constraint.py
  xdsl/irdl/constraints.py
Labels: core

#3480 dialects: (tensor) add insertop and extractop
  tests/filecheck/dialects/tensor/ops.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/tensor/ops.mlir
  xdsl/dialects/tensor.py
Labels: dialects

#3456 core: new inference system for constraints
  tests/dialects/test_bufferization.py
  tests/dialects/test_builtin.py
  tests/filecheck/dialects/onnx/onnx_invalid.mlir
  tests/irdl/test_attr_constraint.py
  tests/irdl/test_attribute_definition.py
  tests/irdl/test_declarative_assembly_format.py
  tests/test_pyrdl.py
  xdsl/dialects/bufferization.py
  xdsl/dialects/builtin.py
  xdsl/dialects/linalg.py
  xdsl/dialects/onnx.py
  xdsl/dialects/stencil.py
  xdsl/irdl/constraints.py
  xdsl/irdl/declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format_parser.py
  xdsl/irdl/operations.py
Labels: core

#3487 core: simplify TypedAttribute
  xdsl/dialects/builtin.py
  xdsl/ir/core.py
  xdsl/irdl/declarative_assembly_format.py
Labels: minor, core

#3490 core: make TypedAttribute printing generic
  xdsl/ir/core.py
  xdsl/irdl/attributes.py
  xdsl/printer.py
Labels: core

#3491 core: make BaseAttr inferrable
  tests/irdl/test_attr_constraint.py
  xdsl/irdl/constraints.py
Labels: core

#3472 misc: split dialects.utils into multiple files
  pyproject.toml
  xdsl/dialects/utils/__init__.py
  xdsl/dialects/utils/fast_math.py
  xdsl/dialects/utils/format.py
Labels: misc

#3488 dialects: (builtin) make FloatAttr a TypedAttribute
  tests/irdl/test_declarative_assembly_format.py
  xdsl/dialects/builtin.py
  xdsl/parser/base_parser.py
  xdsl/printer.py
Labels: dialects

#3494 dialects: (stream) simplify constr helper on stream attributes
  xdsl/dialects/memref_stream.py
  xdsl/dialects/stream.py
Labels: dialects

#3484 dialects: (stream) use assembly format for stream read and write ops
  xdsl/dialects/stream.py
Labels: dialects

#3486 dialects: (stream) remove abstract stream read and write operations
  xdsl/dialects/memref_stream.py
  xdsl/dialects/riscv_snitch.py
  xdsl/dialects/stream.py
Labels: dialects

#3499 misc: add get helper to ScopedDict
  tests/utils/test_scoped_dict.py
  xdsl/utils/scoped_dict.py
Labels: minor, misc

#3500 API: add InferenceContext
  tests/dialects/test_bufferization.py
  tests/irdl/test_attr_constraint.py
  xdsl/dialects/bufferization.py
  xdsl/irdl/constraints.py
  xdsl/irdl/declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format_parser.py
Labels: API

#3501 core: refactor assembly format directives
  tests/irdl/test_declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format_parser.py
Labels: core

#3496 dialects: (linalg) linalg.fill attribute positioning
  tests/filecheck/mlir-conversion/with-mlir/dialects/linalg/ops.mlir
  xdsl/dialects/linalg.py
Labels: dialects

#3498 interpreter: (pdl) add the implementation of type interpretation
  tests/filecheck/transforms/apply-pdl/apply_pdl_build_type.mlir
  xdsl/interpreters/pdl.py
Labels: interpreter

#3504 core: remove generic and generic check from TypedAttribute
  tests/irdl/test_attribute_definition.py
  xdsl/dialects/builtin.py
  xdsl/ir/core.py
  xdsl/irdl/attributes.py
Labels: core

#3503 misc: use nullable getters in ConstraintContext
  xdsl/dialects/stencil.py
  xdsl/irdl/constraints.py
Labels: misc

#3509 dialects: (builtin) make DenseIntOrFPElementsAttr a TypedAttribute
  xdsl/dialects/builtin.py
  xdsl/parser/attribute_parser.py
  xdsl/printer.py
Labels: dialects, core

#3510 dialects: (stream) remove stream dialect and move types to memref_stream and snitch
  tests/filecheck/backend/riscv/convert_riscv_scf_for_to_frep.mlir
  tests/filecheck/backend/riscv/register-allocation/exclude_snitch.mlir
  tests/filecheck/dialects/memref_stream/ops.mlir
  tests/filecheck/dialects/riscv_snitch/assembly_emission.mlir
  tests/filecheck/dialects/riscv_snitch/ops.mlir
  tests/filecheck/dialects/snitch_stream/convert_snitch_stream_to_snitch.mlir
  tests/filecheck/dialects/snitch_stream/ops.mlir
  tests/filecheck/projects/riscv-backend-paper/add_snitch_stream.mlir
  tests/filecheck/projects/riscv-backend-paper/bottom_up.mlir
  tests/filecheck/projects/riscv-backend-paper/relu_snitch_stream.mlir
  tests/filecheck/projects/riscv-backend-paper/source.mlir
  tests/filecheck/transforms/convert_memref_stream_to_loops.mlir
  tests/filecheck/transforms/convert_memref_stream_to_snitch_stream.mlir
  tests/filecheck/transforms/memref_streamify.mlir
  tests/filecheck/transforms/riscv_cse.mlir
  tests/filecheck/transforms/snitch_register_allocation.mlir
  tests/interpreters/test_riscv_snitch_interpreter.py
  tests/interpreters/test_snitch_stream_interpreter.py
  xdsl/dialects/__init__.py
  xdsl/dialects/memref_stream.py
  xdsl/dialects/riscv_snitch.py
  xdsl/dialects/snitch.py
  xdsl/dialects/stream.py
  xdsl/transforms/convert_memref_stream_to_loops.py
  xdsl/transforms/convert_memref_stream_to_snitch_stream.py
  xdsl/transforms/convert_riscv_scf_for_to_frep.py
  xdsl/transforms/memref_streamify.py
  xdsl/transforms/snitch_register_allocation.py
Labels: dialects

#3476 dialects (arm): add mov op
  tests/filecheck/dialects/arm/test_ops.mlir
  xdsl/dialects/arm/__init__.py
  xdsl/dialects/arm/assembly.py
  xdsl/dialects/arm/ops.py
  xdsl/xdsl_opt_main.py
Labels: dialects

#3514 installation: (nix) Update flake and remove ruff
  flake.lock
  flake.nix
Labels: installation

#3506 core: Walk regions for rewritings instead of ops
  docs/database_example.ipynb
  docs/xdsl-introduction.ipynb
  tests/pattern_rewriter/test_pattern_rewriter.py
  xdsl/pattern_rewriter.py
  xdsl/transforms/apply_pdl.py
  xdsl/transforms/canonicalize.py
  xdsl/transforms/convert_qref_to_qssa.py
  xdsl/transforms/convert_qssa_to_qref.py
  xdsl/transforms/convert_scf_to_cf.py
  xdsl/transforms/convert_stencil_to_csl_stencil.py
  xdsl/transforms/dead_code_elimination.py
  xdsl/transforms/lower_mpi.py
  xdsl/transforms/varith_transformations.py
Labels: core

#3515 dialects (arm): add mul instruction with 2 source registers
  tests/filecheck/dialects/arm/test_ops.mlir
  xdsl/dialects/arm/__init__.py
  xdsl/dialects/arm/ops.py
Labels: dialects

#3520 bug: (lower-csl-stencil) Zero-out accumulator for full reduction access
  tests/filecheck/transforms/lower-csl-stencil.mlir
  xdsl/transforms/lower_csl_stencil.py
Labels: bug, transformations

#3524 core: Remove ParsingContext
  xdsl/irdl/declarative_assembly_format_parser.py
Labels: minor, core

#3526 misc: add test to check for Op suffix in operation class names
  tests/dialects/test_dialects.py
  tests/xdsl_opt/test_xdsl_opt.py
  xdsl/dialects/experimental/aie.py
  xdsl/dialects/experimental/fir.py
  xdsl/dialects/experimental/hls.py
  xdsl/transforms/experimental/hls_convert_stencil_to_ll_mlir.py
  xdsl/transforms/experimental/lower_hls.py
Labels: misc

#3516 core: Move assembly format type parsing to directives
  xdsl/irdl/declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format_parser.py
Labels: core

#3507 core: Add operands directive
  tests/irdl/test_declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format_parser.py
Labels: core

#3518 core: Add results directive
  tests/irdl/test_declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format_parser.py
Labels: core

#3521 dialects (arm): add return instruction (bx lr)
  tests/filecheck/dialects/arm_func/test_ops.mlir
  xdsl/dialects/__init__.py
  xdsl/dialects/arm_func.py
Labels: dialects

#3525 core: Fix extractor logic for optional and default-valued properties
  tests/irdl/test_declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format_parser.py
Labels: bug, core

#3530 core: remove unnecessary whitespace printing in assembly format
  tests/irdl/test_declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format.py
Labels: minor, core

#3535 dialects: (builtin) DenseIntOrFPElementsAttr: make data private and use getters instead
  docs/Toy/Toy_Ch3.ipynb
  docs/Toy/toy/dialects/toy.py
  docs/Toy/toy/rewrites/lower_toy_affine.py
  docs/Toy/toy/rewrites/optimise_toy.py
  tests/dialects/test_builtin.py
  xdsl/backend/csl/print_csl.py
  xdsl/backend/riscv/lowering/convert_memref_to_riscv.py
  xdsl/dialects/affine.py
  xdsl/dialects/builtin.py
  xdsl/dialects/cf.py
  xdsl/dialects/varith.py
  xdsl/interpreters/builtin.py
  xdsl/interpreters/linalg.py
  xdsl/interpreters/memref.py
  xdsl/interpreters/ml_program.py
  xdsl/interpreters/onnx.py
  xdsl/interpreters/riscv.py
  xdsl/transforms/canonicalization_patterns/cf.py
  xdsl/transforms/convert_stencil_to_csl_stencil.py
  xdsl/transforms/linalg_to_csl.py
  xdsl/transforms/linalg_transformations.py
Labels: dialects

#3544 dialects: (builtin) verify that the elements of dense satisfy type
  tests/dialects/test_builtin.py
  tests/filecheck/dialects/builtin/dense_array_invalid.mlir
  tests/filecheck/dialects/builtin/dense_array_invalid_dims.mlir
  tests/filecheck/dialects/builtin/dense_array_invalid_element.mlir
  xdsl/dialects/builtin.py
  xdsl/parser/attribute_parser.py
Labels: dialects

#3542 dialects: (builtin) don't use data in DenseArrayBase
  tests/dialects/test_builtin.py
  tests/dialects/test_gpu.py
  tests/dialects/test_llvm.py
  xdsl/backend/riscv/lowering/convert_memref_to_riscv.py
  xdsl/dialects/builtin.py
  xdsl/dialects/cf.py
  xdsl/dialects/csl/csl_stencil.py
  xdsl/dialects/experimental/dmp.py
  xdsl/dialects/gpu.py
  xdsl/dialects/linalg.py
  xdsl/dialects/memref.py
  xdsl/dialects/scf.py
  xdsl/dialects/stablehlo.py
  xdsl/dialects/transform.py
  xdsl/interpreters/wgsl_printer.py
  xdsl/irdl/operations.py
  xdsl/printer.py
  xdsl/transforms/canonicalization_patterns/memref.py
  xdsl/transforms/convert_scf_to_cf.py
  xdsl/transforms/convert_stencil_to_csl_stencil.py
  xdsl/transforms/csl_stencil_to_csl_wrapper.py
  xdsl/transforms/experimental/lower_hls.py
  xdsl/transforms/experimental/stencil_tensorize_z_dimension.py
  xdsl/transforms/memref_to_dsd.py
Labels: dialects

#3545 misc: remove unused name argument from builtin attribute parsing
  xdsl/parser/attribute_parser.py
Labels: minor, misc
