Repository xdslproject/xdsl, pull requests merged in 2025-08, with the labels that each got.

#4944 dialects: (x86) print `.intel_syntax noprefix` in assembly
  tests/filecheck/dialects/x86/x86_assembly_emission.mlir
  xdsl/dialects/x86/ops.py
Labels: dialects

#4943 dialects: (x86_func) print visibility and .text directive
  tests/filecheck/dialects/riscv_func/riscv_func_asm.mlir
  tests/filecheck/dialects/x86_func/x86_func_asm.mlir
  tests/filecheck/dialects/x86_func/x86_func_ops.mlir
  xdsl/dialects/x86_func.py
Labels: dialects

#4942 core: speed up checking for uses
  xdsl/interpreters/eqsat_pdl_interp.py
  xdsl/ir/core.py
  xdsl/transforms/dead_code_elimination.py
Labels: core

#4959 interactive: display pass spec in gui always
  tests/interactive/test_app.py
  tests/interactive/test_get_all_available_passes.py
  tests/interactive/test_rewrites.py
  xdsl/interactive/app.py
  xdsl/interactive/get_all_available_passes.py
  xdsl/interactive/passes.py
  xdsl/interactive/rewrites.py
Labels: interactive

#4956 interactive: only show individual rewrites in "condense" mode
  tests/interactive/test_app.py
  xdsl/interactive/get_all_available_passes.py
Labels: interactive

#4962 core: unify VarOperand and VarOpResult in to SSAValues
  docs/marimo/irdl.py
  xdsl/ir/core.py
  xdsl/irdl/operations.py
Labels: core

#4960 dialects: (vector) vector broadcast from vector
  tests/filecheck/dialects/vector/vector_ops.mlir
  xdsl/dialects/vector.py
Labels: dialects

#4952 dialects: (dlti) Add initialisation convenience from dictionary and python types
  tests/dialects/test_dlti.py
  xdsl/dialects/dlti.py
Labels: dialects

#4966 transformations: add split-load-extract for manual optimization
  tests/filecheck/transforms/vector-split-load-extract.mlir
  xdsl/transforms/__init__.py
  xdsl/transforms/vector_split_load_extract.py
Labels: transformations

#4970 interactive: remove individual rewrites from GUI
  tests/filecheck/transforms/arith-individual-rewrite-pattern-AdditionOfSameVariablesToMultiplyByTwo.mlir
  tests/filecheck/transforms/arith-individual-rewrite-patterns-DivisionOfSameVariableToOne.mlir
  tests/filecheck/transforms/individual_rewrite/add-same.mlir
  tests/interactive/test_app.py
  tests/interactive/test_get_all_available_passes.py
  tests/interactive/test_rewrites.py
  xdsl/interactive/app.py
  xdsl/interactive/get_all_available_passes.py
  xdsl/interactive/rewrites.py
  xdsl/transforms/individual_rewrite.py
Labels: interactive

#4963 core: Operation operands and results are SSAValues
  xdsl/ir/core.py
  xdsl/irdl/operations.py
  xdsl/rewriter.py
  xdsl/transforms/test_constant_folding.py
Labels: core

#4954 transformations: (memref-stream-interleave) extract factor helpers
  tests/transforms/test_memref_stream_interleave.py
  xdsl/transforms/memref_stream_interleave.py
Labels: transformations

#4933 core: (Operation) optimise accessors
  xdsl/irdl/operations.py
Labels: core

#4972 core: move out KIND_BY_PUNCTUATION_SPELLING in MLIR lexer
  tests/test_parser.py
  xdsl/utils/mlir_lexer.py
Labels: core

#4851 interpreter: (eqsat) Full rebuilding
  tests/interpreters/test_eqsat_pdl_interp_interpreter.py
  xdsl/interpreters/eqsat_pdl_interp.py
  xdsl/transforms/apply_eqsat_pdl.py
  xdsl/transforms/apply_eqsat_pdl_interp.py
Labels: interpreter

#4973 core: add OpSelector for easier matching
  tests/ir/test_op_selector.py
  xdsl/interactive/rewrites.py
  xdsl/transforms/individual_rewrite.py
  xdsl/utils/op_selector.py
Labels: core

#4994 documentation: add back autogenerated documentation to nav
  mkdocs.yml
Labels: documentation

#4993 tool: (xdsl-opt) Disable attribute verify on `--disable-verify`
  xdsl/xdsl_opt_main.py
Labels: tool

#4996 documentation: modify navbar and align homepage content
  docs/.nav.yml
  docs/index.md
Labels: documentation

#4786 x86: integration test vector -> x86
  tests/filecheck/projects/libxsmm/integration_test_matmul.mlir
  tests/filecheck/projects/libxsmm/x86_matmul_kernel.mlir
Labels: backend

#5006 misc: delete empty files
  GETTING_STARTED.md
  tests/interactive/test_get_all_available_passes.py
Labels: misc

#5005 misc: add `dependency-groups` to make `uv sync` work
  pyproject.toml
  uv.lock
Labels: misc

#5009 CI: lint benchmarks with pyright
  benchmarks/microbenchmarks.py
  pyproject.toml
Labels: CI

#4999 testing: add MLIR_ROUNDTRIP and MLIR_GENERIC_ROUNDTRIP
  tests/filecheck/mlir-conversion/with-mlir/affine_set.mlir
  tests/filecheck/mlir-conversion/with-mlir/affinet_set.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/arith/arith_attrs.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/emitc/emitc_types.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/llvm/arithmetic.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/llvm/attrs.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/llvm/icmp.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/llvm/inline_asm.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/llvm/llvm_types.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/math/math_ops_custom.mlir
  tests/filecheck/mlir-conversion/with-mlir/lit.local.cfg
  tests/filecheck/mlir-conversion/with-mlir/parser-printer/escaped_characters.mlir
  tests/filecheck/mlir-conversion/with-mlir/scope.mlir
  tests/filecheck/mlir-conversion/with-mlir/symbol_tests.mlir
Labels: testing

#5007 core: add Universe and plugin discovery
  docs/marimo/linalg_snitch.py
  pyproject.toml
  tests/dialects/test_universe.py
  tests/my_plugin/pyproject.toml
  tests/my_plugin/src/my_plugin/__init__.py
  tests/my_plugin/src/my_plugin/py.typed
  uv.lock
  xdsl/tools/command_line_tool.py
  xdsl/universe.py
  xdsl/xdsl_opt_main.py
Labels: core

#5021 installation: try renovate nix support
  renovate.json
Labels: installation

#5011 transformations: (apply-eqsat-pdl) Add option to apply patterns one by one
  tests/filecheck/mlir-conversion/with-mlir/apply-eqsat-pdl/egg_example.mlir
  xdsl/transforms/apply_eqsat_pdl.py
  xdsl/transforms/apply_pdl_interp.py
Labels: transformations

#5017 backend: (x86) add Arch enum and use for register type selection
  tests/filecheck/backend/x86/convert_ptr_to_x86.mlir
  xdsl/backend/x86/lowering/convert_arith_to_x86.py
  xdsl/backend/x86/lowering/convert_ptr_to_x86.py
  xdsl/backend/x86/lowering/convert_vector_to_x86.py
  xdsl/backend/x86/lowering/helpers.py
Labels: backend

#5022 core: (Operation) simplify `irdl_op_verify_arg_list`
  xdsl/irdl/operations.py
Labels: core

#5019 rewriting: add helper to add a listener to set inserted op name hints
  tests/test_op_builder.py
  xdsl/builder.py
  xdsl/pattern_rewriter.py
Labels: rewriting

#5029 dialects: Overload BvConstantOp.__init__
  tests/dialects/test_smt.py
  xdsl/dialects/smt.py
Labels: dialects

#5032 dependencies: remove [riscv] optional extra dependency
  pyproject.toml
  uv.lock
Labels: dependencies

#5038 misc: remove unused type_var_mapping parameter
  xdsl/irdl/attributes.py
Labels: misc

#5037 documentation: add make docs-serve-fast for easier debugging
  Makefile
  scripts/gen_ref_pages.py
Labels: documentation

#5040 core: add IntSetConstraint
  tests/irdl/test_int_constraint.py
  xdsl/dialects/emitc.py
  xdsl/irdl/constraints.py
Labels: core

#5055 core: (irdl_to_attr_constraint) slight refactor/cleanup
  xdsl/irdl/attributes.py
Labels: core

#5061 dialects: (builtin) Add `shape` argument to `TensorType.constr`
  tests/dialects/test_builtin.py
  xdsl/dialects/builtin.py
Labels: dialects

#5052 documentation: remove reference to Winter School schedule
  docs/marimo/pattern_rewrites.py
Labels: documentation

#5064 core: (Accessors) stricten typing
  xdsl/irdl/operations.py
Labels: minor, core

#5062 documentation: add test page for mkdocs-marimo
  docs/marimo/expressions.md
  docs/stylesheets/extra.css
  mkdocs.yml
  pyproject.toml
  uv.lock
Labels: documentation

#5065 dialects: (builtin) make IntegerType generic over width type
  tests/test_pyrdl.py
  xdsl/backend/csl/print_csl.py
  xdsl/dialects/arith.py
  xdsl/dialects/builtin.py
  xdsl/dialects/cf.py
  xdsl/dialects/comb.py
  xdsl/dialects/csl/csl.py
  xdsl/dialects/emitc.py
  xdsl/dialects/linalg.py
  xdsl/dialects/llvm.py
  xdsl/dialects/varith.py
  xdsl/irdl/attributes.py
  xdsl/parser/attribute_parser.py
  xdsl/transforms/constant_fold_interp.py
  xdsl/transforms/lower_csl_stencil.py
  xdsl/transforms/lower_mpi.py
  xdsl/transforms/varith_transformations.py
Labels: dialects

#5069 dialect: (emitc) simplify EmitCFloatTypeConstr definition
  xdsl/dialects/emitc.py
Labels: dialects

#5059 core: ((Operands|Results)Directive) refactor to allow multiple variadics
  tests/irdl/test_declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format_parser.py
  xdsl/irdl/operations.py
Labels: core

#5071 testing: (builtin) improve attrs filecheck
  tests/filecheck/dialects/builtin/attrs.mlir
Labels: testing

#5074 dialects: (builtin) make SignednessAttr generic
  tests/test_pyrdl.py
  xdsl/dialects/builtin.py
Labels: dialects

#5075 dialects: (builtin) make IntegerType generic over Signedness
  tests/filecheck/dialects/memref/invalid_ops.mlir
  tests/filecheck/dialects/snitch_runtime/snitch_runtime_invalid.mlir
  tests/test_pyrdl.py
  xdsl/dialects/builtin.py
  xdsl/dialects/experimental/fir.py
  xdsl/dialects/experimental/hlfir.py
  xdsl/irdl/attributes.py
  xdsl/irdl/declarative_assembly_format_parser.py
Labels: dialects

#5073 documentation: migrate expressions.md notebook to .py
  docs/marimo/expressions.md
  docs/marimo/expressions.py
  scripts/gen_ref_pages.py
Labels: documentation

#4880 dialects: (x86) add shufps operation
  tests/backend/x86/test_register_allocation.py
  tests/filecheck/dialects/x86/x86_assembly_emission.mlir
  tests/filecheck/dialects/x86/x86_ops.mlir
  xdsl/dialects/x86/__init__.py
  xdsl/dialects/x86/ops.py
Labels: dialects

#5081 core: make `operation._successor_uses` public
  xdsl/ir/core.py
Labels: core

#5079 documentation: (Toy) move canonicalization patterns into dialect definition
  docs/Toy/toy/dialects/toy.py
  docs/Toy/toy/rewrites/optimise_toy.py
Labels: documentation

#5087 dialects: (emitc) use EmitCArrayElementType in ArrayType
  tests/filecheck/dialects/emitc/emitc_types_invalid.mlir
  xdsl/dialects/emitc.py
Labels: dialects

#5089 dialects: (emitc) Make EmitC_ArrayType generically-specializable
  xdsl/dialects/emitc.py
Labels: dialects

#5085 transformations: (convert-memref-to-ptr) add get_offset_pointer helper
  xdsl/transforms/convert_memref_to_ptr.py
Labels: transformations

#5039 dialects: (emitc) Add EmitCTypeConstraint
  tests/filecheck/dialects/emitc/emitc_types_invalid.mlir
  xdsl/dialects/emitc.py
Labels: dialects

#5104 documentation: fix link to GETTING_STARTED.md
  README.md
Labels: documentation

#5107 documentation: use marimo directory for micropip
  docs/marimo/expressions.py
Labels: documentation

#5108 documentation: make mkdocs-marimo work on 'latest' branch
  docs/marimo/expressions.py
Labels: documentation

#5115 documentation: use text_area in expression example
  docs/marimo/expressions.py
Labels: documentation
