Repository xdslproject/xdsl, pull requests merged in 2025-01, with the labels that each got.

#3685 dialects: (builtin) Fix TensorOrMemrefOf and add some tests
  tests/dialects/test_builtin.py
  xdsl/dialects/builtin.py
Labels: dialects

#3688 interpreter: sort interpreter functions registering
  xdsl/interpreters/__init__.py
Labels: minor, interpreter

#3690 dialects: (builtin) make DictionaryAttr data an immutabledict
  xdsl/dialects/builtin.py
  xdsl/dialects/csl/csl.py
  xdsl/dialects/csl/csl_stencil.py
  xdsl/dialects/hw.py
  xdsl/dialects/riscv_scf.py
  xdsl/dialects/scf.py
  xdsl/dialects/seq.py
  xdsl/dialects/stencil.py
  xdsl/printer.py
  xdsl/transforms/function_transformations.py
Labels: dialects

#3681 core: Allow to erase orphan operations
  tests/test_rewriter.py
  xdsl/rewriter.py
Labels: core

#3682 core: Delete properly regions in pattern rewriter
  tests/pattern_rewriter/test_pattern_rewriter.py
  xdsl/pattern_rewriter.py
Labels: core

#3683 core: Make PatternRewriter a Builder
  tests/pattern_rewriter/test_pattern_rewriter.py
  xdsl/backend/riscv/riscv_scf_to_asm.py
  xdsl/pattern_rewriter.py
  xdsl/transforms/convert_scf_to_openmp.py
Labels: core

#3687 transformations: (mlir-opt) separate mlir-opt pass errors
  tests/filecheck/mlir-conversion/with-mlir/mlir_opt_fail.mlir
  xdsl/transforms/mlir_opt.py
Labels: transformations

#3694 interpreter: (riscv_cf) register riscv_cf functions
  xdsl/interpreters/__init__.py
Labels: interpreter

#3695 interpreter: support a tuple of listeners in Interpreter
  docs/marimo/linalg_snitch.py
  tests/interpreters/test_scf_interpreter.py
  tests/test_interpreter.py
  xdsl/interpreter.py
Labels: interpreter

#3653 transforms: (memref-to-dsd) Support 1d subview of nd memref
  tests/filecheck/transforms/memref-to-dsd.mlir
  xdsl/transforms/lower_csl_stencil.py
  xdsl/transforms/memref_to_dsd.py
Labels: transformations

#3646 CI: trigger lockfile CI automatically on dependabot PRs
  .github/workflows/update-lockfile-bot.yml
Labels: CI

#3701 core: Remove deprecated methods in Rewriter
  xdsl/rewriter.py
Labels: core

#3702 core: Remove some constructors from `Builder`
  docs/Toy/toy/frontend/ir_gen.py
  docs/Toy/toy/rewrites/lower_toy_affine.py
  tests/test_op_builder.py
  xdsl/backend/riscv/prologue_epilogue_insertion.py
  xdsl/builder.py
  xdsl/dialects/irdl/pyrdl_to_irdl.py
  xdsl/frontend/jaxpr/__init__.py
Labels: core

#3706 dialects: (builtin) add unpack and iter_unpack to IntegerAttr and FloatAttr
  tests/dialects/test_builtin.py
  xdsl/dialects/builtin.py
Labels: dialects

#3708 transformations: (lower-linalg-to-snitch) remove LINALG_SNITCH_OPTIMIZATION_PASSES [NFC]
  xdsl/transforms/test_lower_linalg_to_snitch.py
Labels: minor, transformations

#3709 interpreter: add type property to ShapedArray
  tests/interpreters/test_shaped_array.py
  xdsl/interpreters/shaped_array.py
Labels: minor, interpreter

#3662 dialects: (scf/scf_for) Factor out print and parse methods for For-like operations
  xdsl/dialects/riscv_scf.py
  xdsl/dialects/scf.py
  xdsl/dialects/utils/format.py
Labels: dialects

#3711 documentation: (marimo) use default code editor for displaying assembly
  docs/marimo/linalg_snitch.py
Labels: documentation

#3627 misc: use base printer infrastructure in WGSL printing
  tests/backend/wgsl/test_wgsl_printer.py
  xdsl/backend/wgsl/wgsl_printer.py
  xdsl/interpreters/wgpu.py
  xdsl/xdsl_opt_main.py
Labels: misc

#3716 dialects: (builtin) fix spelling
  xdsl/dialects/builtin.py
Labels: dialects

#3715 dialects: (builtin) DenseIntOrFPElementsAttr: add iterators for values and attrs
  tests/dialects/test_builtin.py
  xdsl/dialects/builtin.py
Labels: dialects

#3717 backend: (csl) use iter_attrs method for DenseIntOrFPElementsArray
  xdsl/backend/csl/print_csl.py
Labels: backend

#3623 dialects: (builtin) change data representation of DenseIntOrFPElements to use bytes
  xdsl/dialects/builtin.py
Labels: dialects

#3720 interpreter: (riscv) add fmadd.d interpreter function
  tests/interpreters/test_riscv_interpreter.py
  xdsl/interpreters/riscv.py
Labels: interpreter

#3721 transformations: (memref-stream-interleave) always take bigger factor
  xdsl/transforms/memref_stream_interleave.py
Labels: transformations

#3723 interactive: store passes in app instead of class+spec tuples
  tests/interactive/test_app.py
  tests/interactive/test_get_all_available_passes.py
  xdsl/interactive/app.py
  xdsl/interactive/get_all_available_passes.py
  xdsl/interactive/passes.py
Labels: interactive

#3722 documentation: (marimo) use jupyter notebooks for easier reviewing
  .github/workflows/ci-notebooks.yml
  Makefile
  docs/marimo/__marimo__/linalg_snitch.ipynb
  docs/marimo/linalg_snitch.py
  docs/marimo/onnx/__marimo__/onnx_demo.ipynb
  docs/marimo/onnx/onnx_demo.py
  pyproject.toml
Labels: documentation

#3725 interactive: AvailablePass now has either a pass type or instance, no spec
  tests/interactive/test_app.py
  tests/interactive/test_get_all_available_passes.py
  tests/interactive/test_rewrites.py
  xdsl/interactive/app.py
  xdsl/interactive/get_all_available_passes.py
  xdsl/interactive/passes.py
  xdsl/interactive/rewrites.py
Labels: interactive

#3726 interactive: App tree holds either a pass type or instance, no spec
  tests/interactive/test_app.py
  xdsl/interactive/app.py
  xdsl/interactive/pass_list_item.py
Labels: interactive

#3713 Move benchmarks to xdsl-bench and add documentation
  README.md
  asv.conf.json
  bench/asv_bench/README.md
  bench/asv_bench/__init__.py
  bench/asv_bench/import_xdsl_opt.py
  bench/parser/bench_lexer.py
  bench/parser/bench_parser.py
  pyproject.toml
Labels: testing

#3728 dialects: (builtin) add support for IntegerType packing with arbitrary bitwidth up to 64
  tests/dialects/test_builtin.py
  xdsl/dialects/builtin.py
Labels: dialects

#3729 testing: (wgpu interpreter) remove wgpy pytest
  tests/interpreters/test_wgpu.py
Labels: testing

#3733 CI: update ruff to 0.9
  .pre-commit-config.yaml
  docs/Toy/toy/frontend/toy_ast.py
  docs/Toy/toy/rewrites/lower_toy_affine.py
  pyproject.toml
  tests/dialects/stim/test_stim_printer_parser.py
  tests/dialects/test_hw.py
  tests/dialects/test_mpi_lowering.py
  tests/irdl/test_declarative_assembly_format.py
  tests/test_frontend_op_inserter.py
  tests/test_op_builder.py
  tests/test_traits.py
  uv.lock
  xdsl/backend/csl/print_csl.py
  xdsl/backend/riscv/lowering/convert_memref_to_riscv.py
  xdsl/backend/riscv/register_allocation.py
  xdsl/backend/riscv/register_queue.py
  xdsl/builder.py
  xdsl/dialects/accfg.py
  xdsl/dialects/csl/csl.py
  xdsl/dialects/csl/csl_wrapper.py
  xdsl/dialects/experimental/dmp.py
  xdsl/dialects/func.py
  xdsl/dialects/onnx.py
  xdsl/dialects/riscv_scf.py
  xdsl/dialects/scf.py
  xdsl/dialects/snitch.py
  xdsl/dialects/stencil.py
  xdsl/frontend/code_generation.py
  xdsl/frontend/python_code_check.py
  xdsl/interactive/app.py
  xdsl/interpreters/eqsat_pdl.py
  xdsl/interpreters/pdl.py
  xdsl/irdl/attributes.py
  xdsl/irdl/declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format_parser.py
  xdsl/irdl/operations.py
  xdsl/parser/attribute_parser.py
  xdsl/parser/base_parser.py
  xdsl/transforms/convert_stencil_to_csl_stencil.py
  xdsl/transforms/csl_stencil_handle_async_flow.py
  xdsl/transforms/csl_stencil_to_csl_wrapper.py
  xdsl/transforms/eqsat_extract.py
  xdsl/transforms/experimental/function_constant_pinning.py
  xdsl/transforms/lower_csl_stencil.py
  xdsl/transforms/memref_to_dsd.py
  xdsl/utils/deprecation.py
  xdsl/utils/mlir_lexer.py
  xdsl/utils/parse_pipeline.py
  xdsl/xdsl_opt_main.py
Labels: CI

#3731 misc: add __init__.py file to wgpu backend folder
  xdsl/backend/wgsl/__init__.py
Labels: bug, minor, misc

#3737 interactive: move pass parsing logic to AddArgumentsScreen
  tests/interactive/test_add_arguments_screen.py
  xdsl/interactive/add_arguments_screen.py
  xdsl/interactive/app.py
Labels: interactive

#3730 CI: update Wandalen/wretry.action and codecov/codecov-action
  .github/workflows/ci-mlir.yml
Labels: CI

#3732 dependencies: (wgpu) remove wgpu dependency
  .github/workflows/ci-mlir.yml
  README.md
  docs/marimo/__marimo__/linalg_snitch.ipynb
  docs/marimo/linalg_snitch.py
  pyproject.toml
  tests/filecheck/runner/with-wgpu/global_id_inc.mlir
  tests/filecheck/runner/with-wgpu/lit.local.cfg
  uv.lock
  xdsl/interpreters/__init__.py
  xdsl/interpreters/wgpu.py
  xdsl/tools/xdsl_run.py
  xdsl/transforms/constant_fold_interp.py
Labels: dependencies

#3738 dialects: (onnx) remove ONNX-related code
  .github/workflows/ci-mlir.yml
  Makefile
  README.md
  docs/marimo/__marimo__/linalg_snitch.ipynb
  docs/marimo/linalg_snitch.py
  docs/marimo/onnx/README.md
  docs/marimo/onnx/__marimo__/onnx_demo.ipynb
  docs/marimo/onnx/onnx_demo.py
  pyproject.toml
  tests/dialects/onnx/test_broadcast.py
  tests/filecheck/dialects/onnx/onnx_invalid.mlir
  tests/filecheck/dialects/onnx/onnx_ops.mlir
  tests/filecheck/transforms/convert_onnx_to_linalg.mlir
  tests/frontend/onnx/test_build_onnx_ir.py
  tests/frontend/onnx/test_type.py
  tests/interpreters/test_onnx_interpreter.py
  uv.lock
  xdsl/dialects/__init__.py
  xdsl/dialects/onnx.py
  xdsl/frontend/onnx/__init__.py
  xdsl/frontend/onnx/ir_builder.py
  xdsl/frontend/onnx/type.py
  xdsl/interpreters/__init__.py
  xdsl/interpreters/onnx.py
  xdsl/tools/xdsl_run.py
  xdsl/transforms/__init__.py
  xdsl/transforms/constant_fold_interp.py
  xdsl/transforms/convert_onnx_to_linalg.py
Labels: dialects

#3745 dialects (arm): add LabelAttr
  tests/test_assembly_arg_str.py
  xdsl/dialects/arm/assembly.py
  xdsl/dialects/arm/attrs.py
Labels: dialects

#3746 Revert "dialects (arm): add LabelAttr (#3745)"
  tests/test_assembly_arg_str.py
  xdsl/dialects/arm/assembly.py
  xdsl/dialects/arm/attrs.py
Labels: dialects

#3748 CI: Create missing virtual enviroment in the publish job
  .github/workflows/pythonpublish.yml
Labels: CI

#3750 CI: Fix PyPi publish CI
  .github/workflows/pythonpublish.yml
Labels: CI

#3749 dialects (arm): Add LabelOp
  tests/filecheck/dialects/arm/test_ops.mlir
  xdsl/dialects/arm/__init__.py
  xdsl/dialects/arm/ops.py
Labels: dialects

#3754 documentation: add mkdocs-based documentation
  Makefile
  docs/api/index.md
  docs/api/ir/attribute.md
  docs/api/ir/block.md
  docs/api/ir/dialect.md
  docs/api/ir/index.md
  docs/api/ir/ir_node.md
  docs/api/ir/operation.md
  docs/api/ir/region.md
  docs/api/ir/ssa_value.md
  docs/index.md
  mkdocs.yml
  pyproject.toml
  uv.lock
  xdsl/ir/core.py
Labels: documentation

#3756 dialects (arm): Add CmpRegOp instruction
  tests/filecheck/dialects/arm/test_ops.mlir
  xdsl/dialects/arm/__init__.py
  xdsl/dialects/arm/ops.py
Labels: dialects

#3703 core: Add BlockInsertPoint to simplify the builder API
  tests/test_op_builder.py
  xdsl/rewriter.py
Labels: core

#3704 core: Refactor some methods using BlockInsertPoint
  tests/test_rewriter.py
  xdsl/builder.py
  xdsl/pattern_rewriter.py
  xdsl/rewriter.py
Labels: core

#3705 core: Deprecate methods that should be using BlockInsertPoint
  tests/pattern_rewriter/test_pattern_rewriter.py
  tests/test_op_builder.py
  tests/test_rewriter.py
  xdsl/backend/riscv/lowering/convert_riscv_scf_to_riscv_cf.py
  xdsl/builder.py
  xdsl/pattern_rewriter.py
  xdsl/rewriter.py
  xdsl/transforms/convert_scf_to_cf.py
Labels: core

#3751 core: (traits) Add `SameOperandsAndResultType` trait
  tests/test_traits.py
  tests/utils/test_type.py
  xdsl/traits.py
  xdsl/utils/type.py
Labels: core

#3761 dialects: (math) Use `SameOperandsAndResultType` trait
  tests/dialects/test_math.py
  xdsl/dialects/experimental/math.py
Labels: dialects

#3768 dialects: (math) Move `math` dialect out of experimental [NFC]
  tests/dialects/test_math.py
  xdsl/dialects/__init__.py
  xdsl/dialects/math.py
  xdsl/transforms/experimental/replace_incompatible_fpga.py
  xdsl/transforms/printf_to_putchar.py
Labels: dialects

#3769 installation: (nix) update flake
  flake.lock
Labels: installation

#3770 documentation: move num_chunks doc comment in ConvertApplyOpPattern
  xdsl/transforms/convert_stencil_to_csl_stencil.py
Labels: documentation

#3771 documentation: code block in doc comments
  xdsl/dialects/experimental/fir.py
  xdsl/dialects/riscv.py
  xdsl/dialects/riscv_snitch.py
  xdsl/dialects/x86/ops.py
  xdsl/transforms/lower_snitch.py
Labels: documentation

#3758 documentation: automatically generate documentation from all .py files in xDSL
  docs/guides/mlir_interoperation.md
  mkdocs.yml
  pyproject.toml
  scripts/gen_ref_pages.py
  uv.lock
Labels: documentation

#3776 dialects: (LLVM) Add bitcast op
  tests/filecheck/dialects/llvm/example.mlir
  xdsl/dialects/llvm.py
Labels: dialects

#3782 documentation: update ImplicitBuilder doc comment
  xdsl/builder.py
Labels: documentation

#3783 core: (assembly-format) omit default attributes/properties from attr-dict directive
  tests/irdl/test_declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format.py
Labels: bug, core

#3699 core: Introduce integer constraints
  tests/irdl/test_declarative_assembly_format.py
  xdsl/irdl/constraints.py
  xdsl/irdl/declarative_assembly_format_parser.py
Labels: core

#3788 documentation: update MLIR interoperation reference
  README.md
Labels: documentation

#3786 dialects: (math) Add support for custom format and container types to `math` dialect ops
  tests/filecheck/dialects/math/math_ops_custom.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/math/math_ops_custom.mlir
  xdsl/dialects/math.py
Labels: dialects

#3789 dialects: (builtin) fix formatting of module printing with attributes
  tests/filecheck/dialects/builtin/module.mlir
  xdsl/dialects/builtin.py
Labels: bug, dialects, minor

#3790 docs: (mlir-winter-school) improve attribute dictionary example
  docs/marimo/mlir_winter_school/1_mlir_ir.py
Labels: documentation

#3791 docs: (mlir-winter-school) Add descriptions for func and scf
  docs/marimo/mlir_winter_school/1_mlir_ir.py
Labels: documentation

#3781 dialects: (llvm) Add a bunch of float methods
  tests/filecheck/dialects/llvm/arithmetic.mlir
  tests/filecheck/dialects/llvm/example.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/llvm/arithmetic.mlir
  xdsl/dialects/llvm.py
Labels: dialects

#3793 dependencies: remove pip
  pyproject.toml
  uv.lock
Labels: dependencies

#3799 dialects: (builtin) integer bitwidths must not be negative
  tests/dialects/test_builtin.py
  xdsl/dialects/builtin.py
Labels: dialects

#3796 misc: Add GH issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: misc

#3801 documentation: add MLIR IR notebook from workshop
  docs/marimo/mlir_ir.py
Labels: documentation

#3804 documentation: add Builders notebook from workshop
  docs/marimo/builders.py
Labels: documentation

#3800 core: (ContainerOf) improve python typing
  xdsl/dialects/builtin.py
  xdsl/dialects/varith.py
Labels: core

#3808 dependencies: remove asv
  pyproject.toml
  uv.lock
Labels: dependencies

#3809 tests: Remove module from `arith` filecheck tests
  tests/filecheck/dialects/arith/arith_attrs.mlir
  tests/filecheck/dialects/arith/arith_invalid.mlir
  tests/filecheck/dialects/arith/arith_ops.mlir
  tests/filecheck/dialects/arith/arith_ops_custom.mlir
Labels: testing, minor

#3689 dialects: (builtin) Fix documentation for parsing of bools, and add conversion to Python bool
  tests/dialects/test_builtin.py
  xdsl/backend/csl/print_csl.py
  xdsl/dialects/builtin.py
Labels: dialects

#3797 core: (constraints) add IntAttrConstraint
  tests/irdl/test_declarative_assembly_format.py
  xdsl/dialects/builtin.py
Labels: core

#3812 documentation: add RISC-V Dialects notebook from workshop
  docs/marimo/riscv_dialects.py
Labels: documentation

#3813 testing: move frontend desymref test to custom format
  tests/filecheck/frontend/passes/desymref.mlir
Labels: testing
