Repository xdslproject/xdsl, pull requests merged in 2025-09, with the labels that each got.

#5124 documentation: marimo expressions - make pass pipeline work
  docs/marimo/expressions.py
Labels: documentation

#5126 documentation: load xdsl for marimo released builds
  docs/marimo/expressions.py
Labels: documentation

#5131 documentation: marimo-expressions - show pass output dynamically
  docs/marimo/expressions.py
Labels: documentation

#5132 documentation: update list-lang to include lowerings
  xdsl/frontend/listlang/lang_types.py
  xdsl/frontend/listlang/list_dialect.py
  xdsl/frontend/listlang/lowerings.py
  xdsl/frontend/listlang/main.py
  xdsl/frontend/listlang/source.py
Labels: documentation

#5135 docs: Add an MLIR introduction notebook
  docs/marimo/mlir_introduction.py
Labels: documentation

#5077 dialects: (complex) Add complex dialect
  tests/filecheck/dialects/complex/ops.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/complex/ops.mlir
  xdsl/dialects/__init__.py
  xdsl/dialects/builtin.py
  xdsl/dialects/complex.py
Labels: dialects

#5147 misc: use f16, f32, etc constants instead of inits
  benchmarks/workloads.py
  tests/dialects/test_arm_neon.py
  tests/dialects/test_builtin.py
  tests/dialects/test_csl.py
  tests/dialects/test_dlti.py
  tests/dialects/test_gpu.py
  tests/filecheck/utils/codegen/simple.py
  tests/interpreters/test_memref_stream_interpreter.py
  tests/irdl/test_declarative_assembly_format.py
  tests/test_rewriter.py
  xdsl/dialects/builtin.py
  xdsl/dialects/csl/csl.py
  xdsl/dialects/stim/ops.py
  xdsl/interpreters/snitch_stream.py
  xdsl/parser/attribute_parser.py
  xdsl/transforms/csl_stencil_set_global_coeffs.py
  xdsl/transforms/function_transformations.py
  xdsl/transforms/linalg_to_csl.py
  xdsl/transforms/lower_csl_stencil.py
Labels: misc

#5148 docs: Use `mo.md` instead of code editor for MLIR
  docs/marimo/mlir_introduction.py
Labels: documentation

#5150 docs: Some improvement on the marimo SSA section
  docs/marimo/mlir_introduction.py
  xdsl/frontend/listlang/main.py
Labels: documentation

#5151 documentation: update list-lang to support `_` prefix
  xdsl/frontend/listlang/lowerings.py
  xdsl/frontend/listlang/main.py
Labels: documentation

#5154 documentation: shorten title
  docs/marimo/mlir_introduction.py
Labels: documentation

#5155 documentation: mlir_intro - interactivity example
  docs/marimo/mlir_introduction.py
Labels: documentation

#5156 documentation: mlir intro - interactivity - shorten text
  docs/marimo/mlir_introduction.py
Labels: documentation

#5157 documentation: disable marimo docs export
  scripts/gen_ref_pages.py
Labels: documentation

#5160 documentation: mlir intro - interactivity - no ':' after heading
  docs/marimo/mlir_introduction.py
Labels: documentation

#5076 documentation: build eqsat notebook to readonly marimo app
  docs/marimo/eqsat.py
  scripts/gen_ref_pages.py
Labels: documentation

#5161 documentation: build PDL notebook to readonly marimo app
  docs/marimo/pdl.py
  scripts/gen_ref_pages.py
Labels: documentation

#5163 documentation: mlir intro - interactive and arithmetic - improve form…
  docs/marimo/mlir_introduction.py
Labels: documentation

#5168 documentation: mlir intro - booleans - structure
  docs/marimo/mlir_introduction.py
  xdsl/utils/marimo.py
Labels: documentation

#5169 documentation: check for arith interpretation output
  docs/marimo/mlir_introduction.py
Labels: documentation

#5178 misc: show pipeline pass spec as str
  tests/test_pass_to_spec.py
  xdsl/passes.py
  xdsl/utils/marimo.py
Labels: misc

#5177 docs: Improve SSA section
  docs/marimo/mlir_introduction.py
Labels: documentation

#5179 interpreter: (arith) fix bitwidth issues
  tests/interpreters/test_arith_interpreter.py
  xdsl/interpreters/arith.py
Labels: interpreter

#5180 docs: Update pass section
  docs/marimo/mlir_introduction.py
Labels: documentation

#5181 docs: remove scf.if when printing bools in listlang
  xdsl/frontend/listlang/lang_types.py
  xdsl/frontend/listlang/marimo.py
Labels: documentation

#5183 docs: Add exercises for Pass section in MLIR introduction
  docs/marimo/mlir_introduction.py
Labels: documentation

#5184 docs: Move one cell
  docs/marimo/mlir_introduction.py
Labels: documentation

#5185 documentation: check pass exercise outputs
  docs/marimo/mlir_introduction.py
Labels: documentation

#5189 docs: Improve titles, and exercises of pass section
  docs/marimo/mlir_introduction.py
Labels: documentation

#5190 docs: Add exercises on passes section
  docs/marimo/mlir_introduction.py
Labels: documentation

#5191 documentation: mlir_intro - fix section title
  docs/marimo/mlir_introduction.py
Labels: documentation

#5196 documentation: copy over code from listlang
  xdsl/frontend/listlang/main.py
  xdsl/frontend/listlang/source.py
  xdsl/frontend/listlang/transforms.py
Labels: documentation

#5229 documentation: show reference for class even if missing doc string
  mkdocs.yml
Labels: documentation

#5233 core: add ConstantLikeInterface
  tests/dialects/test_arith.py
  tests/dialects/test_complex.py
  tests/dialects/test_riscv.py
  tests/dialects/test_smt.py
  tests/filecheck/utils/codegen/simple.py
  xdsl/dialects/arith.py
  xdsl/dialects/complex.py
  xdsl/dialects/riscv.py
  xdsl/dialects/smt.py
  xdsl/interfaces.py
  xdsl/traits.py
Labels: core

#5234 core: add ConstantMaterializationInterface
  docs/marimo/expressions.py
  tests/dialects/test_arith.py
  xdsl/dialect_interfaces.py
  xdsl/dialects/arith.py
  xdsl/transforms/constant_fold_interp.py
Labels: core

#5223 transformations: (eqsat-add-costs) Support external costs from a JSON file
  tests/filecheck/transforms/eqsat-add-costs/costs.json
  tests/filecheck/transforms/eqsat-add-costs/eqsat-add-costs-with-default.mlir
  tests/filecheck/transforms/eqsat-add-costs/eqsat-add-costs-with-json.mlir
  tests/filecheck/transforms/eqsat-add-costs/eqsat-add-costs.mlir
  xdsl/transforms/eqsat_add_costs.py
Labels: transformations

#5236 dialects: (tosa) Add ConcatOp
  tests/dialects/test_tosa.py
  tests/filecheck/dialects/tosa/ops.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/tosa/ops.mlir
  xdsl/dialects/tosa.py
Labels: dialects

#5231 core: use Lexer token in spec parser
  tests/test_pass_lexer.py
  xdsl/utils/exceptions.py
  xdsl/utils/parse_pipeline.py
Labels: core

#5201 docs: Refresh installation docs
  README.md
  benchmarks/README.md
Labels: documentation

#5216 backend: add cost model interface
  tests/backend/test_asm_reporter.py
  xdsl/backend/block_throughput_cost_model.py
  xdsl/dialects/x86/ops.py
Labels: backend

#5247 dialects: (riscv_snitch) use i3 and i4 for frep params
  tests/filecheck/dialects/riscv/frep_verification.mlir
  tests/filecheck/dialects/riscv_snitch/ops.mlir
  tests/filecheck/dialects/riscv_snitch/verification.mlir
  tests/filecheck/dialects/snitch_stream/ops.mlir
  xdsl/dialects/riscv.py
  xdsl/dialects/riscv_snitch.py
Labels: dialects

#5255 documentation: fix method signature doc in tutorial notebook
  docs/marimo/ir_gen.py
Labels: documentation

#5232 core: add folding mechanism
  tests/dialects/test_arith.py
  xdsl/dialects/arith.py
  xdsl/interfaces.py
  xdsl/traits.py
Labels: core

#5260 misc: fix cross-platform llvm-mca call
  tests/backend/test_asm_reporter.py
  xdsl/backend/block_throughput_cost_model.py
Labels: misc

#5266 dialects: (x86) make vmovapd not inout
  tests/filecheck/dialects/x86/x86_assembly_emission.mlir
  tests/filecheck/dialects/x86/x86_ops.mlir
  xdsl/dialects/x86/__init__.py
  xdsl/dialects/x86/ops.py
Labels: dialects

#5268 backend: (x86) handle pointer type conversion
  tests/backend/x86/test_lowering_utils.py
  xdsl/backend/x86/lowering/helpers.py
  xdsl/dialects/ptr.py
Labels: backend

#5274 backend: (x86) allocate avx512 registers
  tests/filecheck/backend/x86/x86_allocate_registers.mlir
  xdsl/backend/x86/register_stack.py
  xdsl/dialects/x86/registers.py
Labels: backend

#5277 dialects: (x86_scf) ForRofOperation: RegisterAllocatableOperation
  tests/filecheck/backend/x86/x86_allocate_registers.mlir
  xdsl/dialects/x86_scf.py
Labels: dialects

#5279 transformations: (convert-scf-to-x86-scf) add lowering from scf to x86
  tests/filecheck/transforms/convert-scf-to-x86-scf.mlir
  xdsl/transforms/__init__.py
  xdsl/transforms/convert_scf_to_x86_scf.py
Labels: transformations

#5283 dialects: (memref) remove memref.SubviewOp.DYNAMIC_INDEX
  tests/dialects/test_tensor.py
  xdsl/backend/riscv/lowering/convert_memref_to_riscv.py
  xdsl/dialects/memref.py
  xdsl/dialects/tensor.py
  xdsl/transforms/convert_stencil_to_csl_stencil.py
  xdsl/transforms/csl_stencil_bufferize.py
  xdsl/transforms/memref_to_dsd.py
Labels: dialects

#5284 transformations: (convert-memref-to-ptr) lower memref.subview
  tests/filecheck/transforms/convert_memref_to_ptr.mlir
  xdsl/transforms/convert_memref_to_ptr.py
Labels: transformations

#5285 backend: (JAX) remove jax backend
  tests/backend/test_jax_executable.py
  xdsl/backend/jax_executable.py
Labels: backend

#5287 core: (assembly-format) Add optional anchor support for `Custom<DynamicIndexList>`
  tests/irdl/test_declarative_assembly_format.py
  xdsl/dialects/utils/dynamic_index_list.py
Labels: enhancement, minor, core
