Repository xdslproject/xdsl, pull requests merged in 2025-03, with the labels that each got.

#3993 documentation: use strict flag for building website and add to CI
  .github/workflows/ci-docs.yml
  mkdocs.yml
Labels: documentation

#3994 dependencies: add viztracer and orjson to bench dependency group
  pyproject.toml
  uv.lock
Labels: dependencies

#3980 dialects: (stablehlo) Add support for xor and op operations
  tests/filecheck/dialects/stablehlo/ops.mlir
  xdsl/dialects/stablehlo.py
Labels: dialects

#3997 misc: store context as property on ParsingState
  xdsl/irdl/declarative_assembly_format.py
Labels: misc

#3999 misc: ConstraintContext keys properties are abstract sets
  xdsl/irdl/constraints.py
Labels: minor, misc

#4000 core: split InferenceContext dictionaries
  xdsl/irdl/constraints.py
  xdsl/irdl/declarative_assembly_format.py
Labels: core

#4001 core: use ConstraintContext for inference
  tests/dialects/test_bufferization.py
  tests/irdl/test_attr_constraint.py
  xdsl/dialects/bufferization.py
  xdsl/dialects/builtin.py
  xdsl/irdl/constraints.py
  xdsl/irdl/declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format_parser.py
Labels: core

#3984 backend: (riscv) make LiOp and float binary ops not take str for rd
  xdsl/dialects/riscv.py
Labels: backend

#3985 backend: (x86) use named register constants in ops file
  xdsl/dialects/x86/ops.py
Labels: backend

#4014 dialects: (stablehlo) Add support for some unary and binary operations
  tests/filecheck/dialects/stablehlo/ops.mlir
  xdsl/dialects/stablehlo.py
Labels: dialects

#4016 core: reuse field definition functions across op definitions
  xdsl/irdl/operations.py
Labels: core

#4011 backend: (riscv) use infinite register helper in more tests
  tests/backend/riscv/test_register_allocation.py
  tests/backend/riscv/test_register_queue.py
  tests/dialects/test_riscv.py
Labels: backend

#4012 misc: make xDSL version getting lazy
  xdsl/xdsl_opt_main.py
Labels: minor, misc

#4013 documentation: remove database example notebook
  docs/database_example.ipynb
Labels: documentation

#4018 bench: add gitignore file for profile outputs
  benchmarks/.gitignore
Labels: bench

#4019 ci: use ubuntu-latest in ci-mlir
  .github/workflows/ci-mlir.yml
Labels: CI

#4007 core: (affine) Add functions dealing with dimensions to AffineMap and AffineExpr
  tests/test_affine_builtins.py
  xdsl/ir/affine/affine_map.py
Labels: core

#3802 dialects: (arith) Fix `arith.constant` to return only signless integers
  tests/filecheck/dialects/arith/arith_invalid.mlir
  xdsl/dialects/arith.py
Labels: dialects

#4022 backend: (riscv) narrow verifier of float and int infinite register names
  tests/filecheck/dialects/riscv/riscv_assembly_emission.mlir
  xdsl/dialects/riscv.py
Labels: backend

#4021 backend: spelling -> register_name
  docs/marimo/riscv_dialects.py
  tests/backend/riscv/test_register_allocation.py
  tests/backend/riscv/test_register_queue.py
  tests/backend/test_register.py
  tests/dialects/test_riscv.py
  tests/dialects/test_x86.py
  tests/test_assembly_arg_str.py
  tests/test_parser.py
  xdsl/backend/register_type.py
  xdsl/backend/riscv/register_allocation.py
  xdsl/backend/riscv/riscv_register_queue.py
  xdsl/dialects/arm/assembly.py
  xdsl/dialects/arm/register.py
  xdsl/dialects/riscv.py
  xdsl/dialects/x86/assembly.py
  xdsl/dialects/x86/register.py
  xdsl/interpreters/riscv.py
  xdsl/parser/base_parser.py
  xdsl/utils/mlir_lexer.py
Labels: backend

#4026 misc: (makefile) Remove prerequisites for removing hidden ASV directory
  Makefile
Labels: minor, misc

#4028 documentation: migrate xDSL introduction notebook from jupyter to marimo
  docs/marimo/xdsl_introduction.py
  docs/xdsl-introduction.ipynb
Labels: documentation

#4029 backend: move register type verification from all subclasses to superclass
  tests/backend/test_register.py
  tests/dialects/test_riscv.py
  tests/filecheck/dialects/riscv/riscv_registers_invalid.mlir
  tests/filecheck/dialects/x86/x86_registers_invalid.mlir
  xdsl/backend/register_type.py
  xdsl/dialects/arm/register.py
  xdsl/dialects/riscv.py
  xdsl/dialects/x86/register.py
Labels: backend

#4030 backend: (riscv) allow x0... and f0... register names
  tests/filecheck/dialects/riscv/riscv_registers_invalid.mlir
  xdsl/dialects/riscv.py
Labels: backend

#3916 dialects: (arith) fix `arith.constant` construction
  tests/dialects/test_arith.py
  xdsl/dialects/arith.py
  xdsl/transforms/experimental/function_constant_pinning.py
Labels: dialects

#4031 backend: (riscv) x0 is same as zero for CSR for verification
  tests/dialects/test_riscv.py
  tests/filecheck/dialects/riscv/csr_invalid.mlir
  xdsl/dialects/riscv.py
Labels: backend

#4037 transformations: Make loop folding consistent with mlir
  tests/filecheck/transforms/scf_for_loop_range_folding.mlir
  xdsl/transforms/scf_for_loop_range_folding.py
Labels: transformations

#4032 interactive: return structured tuple in get_pass_argument_names_and_types
  tests/test_pass_to_arg_and_types_str.py
  xdsl/interactive/add_arguments_screen.py
  xdsl/passes.py
Labels: interactive

#4036 documentation: Remove notebook
  docs/tutorial.ipynb
Labels: documentation

#4035 misc: (makefile) Run all marimo tests and report at the end
  Makefile
Labels: minor, misc

#4042 backend: add abi_name_by_index helper to RegisterType
  tests/backend/test_register.py
  tests/dialects/test_riscv.py
  xdsl/backend/register_type.py
  xdsl/dialects/arm/register.py
  xdsl/dialects/riscv.py
  xdsl/dialects/x86/register.py
Labels: backend

#4043 documentation: deploy docs website to readthedocs
  .readthedocs.yaml
Labels: documentation

#4045 CI: fix tests-marimo on mac
  Makefile
Labels: CI

#4006 core: (affine) Add Affine.binary
  tests/test_affine_builtins.py
  xdsl/ir/affine/affine_expr.py
Labels: core

#4044 backend: add from_index method to register
  tests/backend/test_register.py
  tests/dialects/test_riscv.py
  xdsl/backend/register_type.py
Labels: backend

#4046 CI: use relative files in coverage report
  .github/workflows/ci-mlir.yml
  codecov.yml
  pyproject.toml
Labels: CI

#4051 CI: only collect coverage data for one Python version
  .github/workflows/ci-mlir.yml
Labels: CI

#3953 testing: don't cd to git root dir in lit
  pyproject.toml
  tests/filecheck/lit.cfg
Labels: testing

#4058 documentation: fix commit hash in readme
  README.md
Labels: documentation

#4060 backend: (riscv) RiscvRegisterQueue makes empty queue, add helper
  tests/backend/riscv/test_register_allocation.py
  tests/backend/riscv/test_register_queue.py
  xdsl/backend/riscv/riscv_register_queue.py
  xdsl/transforms/riscv_register_allocation.py
Labels: backend

#4054 fix: handle-async-flow to work with no `iter_args`
  tests/filecheck/transforms/csl-stencil-handle-async-flow-no-args.mlir
  xdsl/transforms/csl_stencil_handle_async_flow.py
Labels: minor, transformations

#4062 backend: (riscv) use register indices to track available registers
  tests/backend/riscv/test_register_queue.py
  xdsl/backend/riscv/riscv_register_queue.py
Labels: backend

#4066 bench: add lexing benchmarks and their workloads
  benchmarks/lexer.py
  benchmarks/workloads.py
Labels: bench

#4076 transforms: (csl) Support sdk 1.3
  tests/filecheck/transforms/csl-stencil-to-csl-wrapper.mlir
  tests/filecheck/transforms/lower-csl-wrapper.mlir
  xdsl/transforms/csl_stencil_to_csl_wrapper.py
  xdsl/transforms/lower_csl_wrapper.py
Labels: transformations

#4074 dependencies: make pre-commit version less strict
  pyproject.toml
  uv.lock
Labels: dependencies

#4077 minor: (csl-stencil-handle-async-flow) Provide task ids as list
  tests/filecheck/transforms/csl-stencil-handle-async-flow-no-args.mlir
  tests/filecheck/transforms/csl-stencil-handle-async-flow.mlir
  xdsl/transforms/csl_stencil_handle_async_flow.py
Labels: minor, transformations

#4061 backend: (arm) make AssemblyInstructionArg an ABC
  tests/dialects/arm/test_assembly_arg_str.py
  tests/test_assembly_arg_str.py
  xdsl/dialects/arm/assembly.py
  xdsl/dialects/arm/ops.py
  xdsl/dialects/arm/register.py
Labels: backend

#4080 dialects: (vector) add assembly format to vector ops
  tests/dialects/test_vector.py
  tests/filecheck/dialects/vector/vector_fma_res_acc_shape_matching.mlir
  tests/filecheck/dialects/vector/vector_fma_res_acc_type_matching.mlir
  tests/filecheck/dialects/vector/vector_fma_res_lhs_shape_matching.mlir
  tests/filecheck/dialects/vector/vector_fma_res_lhs_type_matching.mlir
  tests/filecheck/dialects/vector/vector_fma_res_rhs_shape_matching.mlir
  tests/filecheck/dialects/vector/vector_fma_res_rhs_type_matching.mlir
  tests/filecheck/dialects/vector/vector_ops.mlir
  tests/filecheck/dialects/vector/vector_pure_ops.mlir
  xdsl/dialects/vector.py
Labels: dialects

#4059 documentation: migrate interoperability notebook from jupyter to marimo
  .github/workflows/ci-mlir.yml
  Makefile
  docs/marimo/mlir_interoperation.py
  docs/marimo/source.mlir
  docs/mlir_interoperation.ipynb
Labels: documentation

#4087 dialects: (bigint) Add start of bigint dialect
  tests/filecheck/dialects/bigint/attrs.mlir
  xdsl/dialects/__init__.py
  xdsl/dialects/bigint.py
Labels: dialects

#4090 dialects: (stablehlo) add more operations
  tests/filecheck/dialects/stablehlo/attrs.mlir
  tests/filecheck/dialects/stablehlo/invalid.mlir
  tests/filecheck/dialects/stablehlo/ops.mlir
  xdsl/dialects/stablehlo.py
Labels: dialects

#4093 dialects: (builtin) add custom repr to IntegerType
  tests/dialects/test_builtin.py
  xdsl/dialects/builtin.py
Labels: dialects

#4094 core: add custom repr to BaseAttr and ParamAttrConstraint
  tests/irdl/test_attr_constraint.py
  xdsl/irdl/constraints.py
Labels: core

#4095 misc: add python dialect codegen file with minimal functionality
  tests/filecheck/utils/codegen/simple.py
  xdsl/utils/dialect_codegen.py
Labels: misc

#4096 dialects: (stablehlo) Improve documentation
  xdsl/dialects/stablehlo.py
Labels: dialects

#4097 misc: Python dialect codegen - operands and results
  tests/filecheck/utils/codegen/simple.py
  xdsl/utils/dialect_codegen.py
Labels: misc

#4098 misc: loosen type restriction in dialect_codegen out parameter
  xdsl/utils/dialect_codegen.py
Labels: bug, misc

#4102 misc: Add explicit key check in ScopedDict.
  xdsl/utils/scoped_dict.py
Labels: misc

#4108 core: fix spacing in print_func_op_like
  tests/filecheck/dialects/csl/ops.mlir
  tests/filecheck/dialects/stencil/oec-kernels/fvtp2d_qi.mlir
  tests/filecheck/dialects/stencil/stencil_ops.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/stencil/ops.mlir
  tests/filecheck/transforms/convert-stencil-to-ll-mlir.mlir
  tests/filecheck/transforms/csl-stencil-handle-async-flow-no-args.mlir
  tests/filecheck/transforms/csl-stencil-handle-async-flow.mlir
  tests/filecheck/transforms/distribute-stencil.mlir
  tests/filecheck/transforms/lower-csl-stencil.mlir
  tests/filecheck/transforms/stencil-bufferize.mlir
  tests/filecheck/transforms/stencil-inlining.mlir
  tests/filecheck/transforms/stencil-shape-inference.mlir
  tests/filecheck/transforms/stencil-unroll.mlir
  xdsl/dialects/utils/format.py
Labels: core

#4106 backend: add emit_section helper to AssemblyPrinter
  tests/filecheck/projects/riscv-backend-paper/bottom_up_f32.mlir
  tests/filecheck/projects/riscv-backend-paper/bottom_up_f64.mlir
  xdsl/backend/assembly_printer.py
  xdsl/dialects/riscv.py
Labels: backend

#4110 misc: catch DiagnosticExceptions thrown in xDSLOptMain targets
  tests/xdsl_opt/test_xdsl_opt.py
  xdsl/xdsl_opt_main.py
Labels: misc

#4115 documentation: Fix HTML markup for URL links in docstrings
  xdsl/backend/csl/__init__.py
  xdsl/backend/csl/print_csl.py
  xdsl/backend/riscv/traits.py
  xdsl/builder.py
  xdsl/dialects/affine.py
  xdsl/dialects/arith.py
  xdsl/dialects/arm/__init__.py
  xdsl/dialects/arm/ops.py
  xdsl/dialects/builtin.py
  xdsl/dialects/comb.py
  xdsl/dialects/csl/csl.py
  xdsl/dialects/experimental/fir.py
  xdsl/dialects/experimental/hlfir.py
  xdsl/dialects/fsm.py
  xdsl/dialects/hw.py
  xdsl/dialects/linalg.py
  xdsl/dialects/llvm.py
  xdsl/dialects/ltl.py
  xdsl/dialects/math.py
  xdsl/dialects/ml_program.py
  xdsl/dialects/mpi.py
  xdsl/dialects/pdl.py
  xdsl/dialects/riscv.py
  xdsl/dialects/riscv_cf.py
  xdsl/dialects/riscv_snitch.py
  xdsl/dialects/seq.py
  xdsl/dialects/stablehlo.py
  xdsl/dialects/transform.py
  xdsl/dialects/x86/ops.py
  xdsl/dialects/x86/register.py
  xdsl/ir/affine/affine_expr.py
  xdsl/ir/core.py
  xdsl/irdl/dominance.py
  xdsl/rewriter.py
  xdsl/traits.py
  xdsl/transforms/loop_invariant_code_motion.py
  xdsl/utils/comparisons.py
  xdsl/utils/disjoint_set.py
Labels: documentation, minor

#4113 dialects: (arm) add helper to print register SSAValues in ARM assembly
  xdsl/dialects/arm/assembly.py
  xdsl/dialects/arm/ops.py
Labels: dialects

#3778 documentation: embed marimo notebooks in docs website
  docs/__init__.py
  docs/blocks.py
  docs/marimo/index.md
  mkdocs.yml
  pyproject.toml
  scripts/gen_ref_pages.py
  uv.lock
Labels: documentation

#4116 dialects (arm): add arrangement specifier attribute
  tests/filecheck/dialects/arm_neon/test_attrs.mlir
  xdsl/dialects/arm_neon.py
Labels: dialects

#4117 dialects (arm): Add vector with arrangement
  tests/dialects/test_arm_neon.py
  xdsl/dialects/arm_neon.py
Labels: dialects

#4114 transforms: Add csl-stencil-set-global-coeffs pass
  tests/filecheck/transforms/csl-stencil-set-global-coeffs.mlir
  xdsl/transforms/__init__.py
  xdsl/transforms/csl_stencil_set_global_coeffs.py
  xdsl/transforms/lower_csl_stencil.py
Labels: transformations

#4118 misc: lint some markdown files in project
  .github/pull_request_template.md
  README.md
  docs/guides/mlir_interoperation.md
  tests/xdsl_opt/README.md
  tests/xdsl_opt/test_xdsl_opt.py
Labels: misc

#4124 dialects: (builtin) handle unsigned integer packing
  tests/dialects/test_builtin.py
  tests/filecheck/dialects/builtin/packed.mlir
  xdsl/dialects/builtin.py
Labels: dialects

#3990 dialects: Raise a parsing error in accfg.setup when result type is invalid
  tests/filecheck/dialects/accfg/invalid.mlir
  xdsl/dialects/accfg.py
Labels: dialects

#4130 misc: (makefile) remove directive defining bash location
  Makefile
Labels: misc

#4125 core: Make SSAValue type immutable
  docs/Toy/toy/dialects/toy.py
  tests/backend/riscv/test_register_allocation.py
  tests/dialects/test_func.py
  tests/pattern_rewriter/test_pattern_rewriter.py
  xdsl/backend/riscv/lowering/utils.py
  xdsl/backend/riscv/register_allocation.py
  xdsl/dialects/func.py
  xdsl/ir/core.py
  xdsl/pattern_rewriter.py
  xdsl/rewriter.py
  xdsl/transforms/convert_memref_stream_to_snitch_stream.py
  xdsl/transforms/convert_memref_to_ptr.py
  xdsl/transforms/experimental/convert_stencil_to_ll_mlir.py
  xdsl/transforms/experimental/hls_convert_stencil_to_ll_mlir.py
  xdsl/transforms/experimental/lower_hls.py
  xdsl/transforms/experimental/stencil_tensorize_z_dimension.py
  xdsl/transforms/memref_stream_legalize.py
  xdsl/transforms/shape_inference_patterns/dmp.py
  xdsl/transforms/shape_inference_patterns/stencil.py
  xdsl/transforms/snitch_register_allocation.py
Labels: core

#4112 dialects: (riscv_func) print visibility in riscv_func.func
  tests/filecheck/dialects/riscv_func/riscv_func_asm.mlir
  tests/filecheck/projects/riscv-backend-paper/add_snitch_stream.mlir
  tests/filecheck/projects/riscv-backend-paper/ddot_regalloc.mlir
  tests/filecheck/projects/riscv-backend-paper/relu_snitch_stream.mlir
  tests/filecheck/with-riscemu/riscv_emulation.mlir
  tests/interpreters/test_riscv_emulator.py
  xdsl/dialects/riscv_func.py
Labels: dialects

#3987 core: Make SSAValue generic
  xdsl/ir/core.py
  xdsl/printer.py
  xdsl/utils/test_value.py
Labels: core

#3988 core: Add support for typed SSA values in isa
  tests/test_is_satisfying_hint.py
  xdsl/utils/hints.py
Labels: core

#3989 core: Make OpResult and BlockArgument generic like SSAValue
  xdsl/ir/core.py
Labels: core

#3991 core: Make IRDLOperation results typed
  docs/Toy/toy/rewrites/lower_toy_affine.py
  docs/Toy/toy/rewrites/optimise_toy.py
  xdsl/backend/csl/print_csl.py
  xdsl/backend/riscv/lowering/convert_memref_to_riscv.py
  xdsl/dialects/csl/csl.py
  xdsl/dialects/memref.py
  xdsl/dialects/riscv.py
  xdsl/dialects/stablehlo.py
  xdsl/dialects/stencil.py
  xdsl/dialects/tensor.py
  xdsl/interpreters/memref.py
  xdsl/interpreters/riscv.py
  xdsl/interpreters/tensor.py
  xdsl/irdl/operations.py
  xdsl/transforms/canonicalization_patterns/riscv.py
  xdsl/transforms/canonicalization_patterns/stencil.py
  xdsl/transforms/convert_stencil_to_csl_stencil.py
  xdsl/transforms/experimental/hls_convert_stencil_to_ll_mlir.py
  xdsl/transforms/experimental/stencil_tensorize_z_dimension.py
  xdsl/transforms/lower_riscv_func.py
  xdsl/transforms/memref_to_dsd.py
  xdsl/transforms/shape_inference_patterns/dmp.py
  xdsl/transforms/shape_inference_patterns/stencil.py
  xdsl/transforms/stencil_inlining.py
Labels: core

#4131 CI: add some more Pyright rules and add comments
  pyproject.toml
Labels: CI
