Repository xdslproject/xdsl, pull requests merged in 2025-07, with the labels that each got.

#4695 misc: simplify FloatAttr[AnyFloat]
  xdsl/dialects/arith.py
  xdsl/dialects/csl/csl_stencil.py
  xdsl/dialects/tosa.py
Labels: misc

#4700 backend: (x86_func) lower return without arguments
  tests/filecheck/backend/x86/convert_func_to_x86.mlir
  xdsl/backend/x86/lowering/convert_func_to_x86_func.py
Labels: backend

#4701 transformations: add test-transform-dialect-erase-schedule
  tests/filecheck/transforms/test_transform_dialect_erase_schedule.mlir
  xdsl/transforms/__init__.py
  xdsl/transforms/test_transform_dialect_erase_schedule.py
Labels: transformations

#4474 API: migrate xDSL to param_def API for parametrized attributes
  docs/marimo/defining_dialects.py
  docs/marimo/irdl.py
  tests/filecheck/dialects/irdl/irdl-to-pyrdl/testd.irdl.mlir
  tests/irdl/test_attr_constraint.py
  tests/irdl/test_attribute_definition.py
  tests/irdl/test_declarative_assembly_format.py
  tests/test_is_satisfying_hint.py
  tests/test_printer.py
  tests/test_pyrdl.py
  xdsl/backend/register_type.py
  xdsl/dialects/accfg.py
  xdsl/dialects/builtin.py
  xdsl/dialects/csl/csl.py
  xdsl/dialects/csl/csl_stencil.py
  xdsl/dialects/csl/csl_wrapper.py
  xdsl/dialects/emitc.py
  xdsl/dialects/experimental/dmp.py
  xdsl/dialects/experimental/fir.py
  xdsl/dialects/experimental/hlfir.py
  xdsl/dialects/experimental/hls.py
  xdsl/dialects/gpu.py
  xdsl/dialects/hw.py
  xdsl/dialects/irdl/irdl.py
  xdsl/dialects/irdl/irdl_to_pyrdl.py
  xdsl/dialects/llvm.py
  xdsl/dialects/memref_stream.py
  xdsl/dialects/mpi.py
  xdsl/dialects/omp.py
  xdsl/dialects/pdl.py
  xdsl/dialects/smt.py
  xdsl/dialects/snitch.py
  xdsl/dialects/snitch_stream.py
  xdsl/dialects/stablehlo.py
  xdsl/dialects/stencil.py
  xdsl/dialects/stim/ops.py
  xdsl/dialects/transform.py
  xdsl/irdl/attributes.py
Labels: API

#4707 dialects: (stablehlo) make batching dimensions optional
  tests/filecheck/dialects/stablehlo/attrs.mlir
  xdsl/dialects/stablehlo.py
Labels: dialects

#4706 dialects:(omp) add `omp.target_data` op
  tests/filecheck/dialects/omp/ops.mlir
  tests/filecheck/dialects/omp/ops_invalid.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/omp/ops.mlir
  xdsl/dialects/omp.py
Labels: dialects

#4709 dialects:(omp) add task based data mapping ops
  tests/filecheck/dialects/omp/ops.mlir
  tests/filecheck/dialects/omp/ops_invalid.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/omp/ops.mlir
  xdsl/dialects/omp.py
Labels: dialects

#4712 transformations: (memref-stream-interleave) add factors helper
  tests/transforms/test_memref_stream_interleave.py
  xdsl/transforms/memref_stream_interleave.py
Labels: transformations

#4713 interpreter: (ScopedDict) Don't recurse when getting an item
  xdsl/utils/scoped_dict.py
Labels: interpreter

#4717 core: make Region hashable again
  tests/test_ir.py
  xdsl/ir/core.py
Labels: core

#4714 dialects: Add a reshape_ops_utils.py
  tests/filecheck/dialects/memref/invalid_ops.mlir
  tests/filecheck/dialects/tensor/invalid_ops.mlir
  xdsl/dialects/memref.py
  xdsl/dialects/tensor.py
  xdsl/dialects/utils/reshape_ops_utils.py
Labels: dialects

#4718 API: add region_utils and used_values_defined_above
  tests/ir/test_region_utils.py
  xdsl/ir/region_utils.py
Labels: API

#4727 documentation: (Toy) use snake_case in ToyParser methods
  docs/Toy/Toy_Ch1.ipynb
  docs/Toy/toy/__main__.py
  docs/Toy/toy/compiler.py
  docs/Toy/toy/frontend/parser.py
  docs/Toy/toy/tests/test_ir_gen.py
  docs/Toy/toy/tests/test_parser.py
Labels: documentation

#4725 documentation: (Toy) make Location a NamedTuple
  docs/Toy/toy/frontend/location.py
Labels: documentation

#4729 documentation: (Toy) remove flattened_values from LiteralExprAST
  docs/Toy/toy/frontend/ir_gen.py
  docs/Toy/toy/frontend/toy_ast.py
Labels: documentation

#4731 misc: IRNode = Operation | Region | Block
  xdsl/ir/core.py
  xdsl/utils/diagnostic.py
Labels: misc

#4732 documentation: (Toy) use NamedTuple for Toy AST
  docs/Toy/Toy_Ch1.ipynb
  docs/Toy/examples/ast.toy
  docs/Toy/toy/frontend/toy_ast.py
Labels: documentation

#4738 backend: (x86) comment-out 32-bit x86 register names
  tests/dialects/test_x86.py
  tests/filecheck/dialects/x86/x86_assembly_emission.mlir
  tests/filecheck/dialects/x86/x86_ops.mlir
  xdsl/dialects/x86/register.py
Labels: backend

#4740 documentation: (Toy) remove redundant pytests
  Makefile
  docs/Toy/toy/tests/__init__.py
  docs/Toy/toy/tests/test_ir_gen.py
  docs/Toy/toy/tests/test_parser.py
Labels: documentation

#4742 dialects: (emitc) Add OpaqueType
  tests/filecheck/dialects/emitc/emitc_types.mlir
  tests/filecheck/dialects/emitc/emitc_types_invalid.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/emitc/emitc_types.mlir
  xdsl/dialects/emitc.py
Labels: dialects

#4245 dialects: (tensor) add ExpandShapeOp
  tests/filecheck/dialects/tensor/invalid_ops.mlir
  tests/filecheck/dialects/tensor/ops.mlir
  xdsl/dialects/tensor.py
  xdsl/dialects/utils/reshape_ops_utils.py
Labels: dialects

#4745 documentation: (Toy) clean up toy dialect
  docs/Toy/Toy_Ch3.ipynb
  docs/Toy/toy/dialects/toy.py
  docs/Toy/toy/frontend/ir_gen.py
  docs/Toy/toy/interpreter.py
  docs/Toy/toy/rewrites/optimise_toy.py
Labels: documentation

#4743 misc: remove parameter parsing and printing for builtin data attributes
  xdsl/dialects/builtin.py
  xdsl/parser/attribute_parser.py
Labels: misc

#4748 misc: replace PipelinePass.iter_passes with parse_spec
  tests/xdsl_opt/test_xdsl_opt.py
  xdsl/interactive/app.py
  xdsl/interpreters/transform.py
  xdsl/passes.py
  xdsl/xdsl_opt_main.py
Labels: misc

#4751 API: PipelinePass -> PassPipeline
  docs/marimo/linalg_snitch.py
  xdsl/interactive/app.py
  xdsl/interactive/get_all_available_passes.py
  xdsl/interactive/passes.py
  xdsl/interpreters/transform.py
  xdsl/passes.py
  xdsl/utils/marimo.py
  xdsl/xdsl_opt_main.py
Labels: API

#4756 core: (ConstraintContext) deprecate copy and update
  xdsl/irdl/constraints.py
Labels: core

#4753 core: add AffineMap inverse_and_broadcast_projected_permutation and drop_results
  tests/test_affine_builtins.py
  xdsl/ir/affine/affine_map.py
Labels: core

#4754 dialects: (linalg) use `Operation` as abstract operation suffix
  xdsl/dialects/linalg.py
  xdsl/transforms/csl_stencil_bufferize.py
  xdsl/transforms/linalg_to_csl.py
  xdsl/transforms/linalg_transformations.py
Labels: dialects

#4761 core: (Data) add get method
  tests/ir/test_attribute.py
  xdsl/ir/core.py
Labels: core

#4770 misc: add Input.get_start_of_line and .get_end_of_line
  tests/test_lexer.py
  xdsl/utils/lexer.py
Labels: misc

#4771 dialects: (emitc) Add SignedSizeTType
  tests/filecheck/dialects/emitc/emitc_types.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/emitc/emitc_types.mlir
  xdsl/dialects/emitc.py
Labels: dialects

#4768 API: unify PatternRewriter.insert and .insert_op
  xdsl/builder.py
  xdsl/pattern_rewriter.py
Labels: API

#4767 core: (affine) add AffineMap.unused_dims and .unused_dims_bit_vector
  tests/test_affine_builtins.py
  xdsl/ir/affine/affine_map.py
Labels: core

#4766 core: (affine) add apply_permutation helper to AffineMap
  tests/test_affine_builtins.py
  xdsl/ir/affine/affine_map.py
Labels: core

#4769 misc: columns in debug messages start at 1
  tests/filecheck/dialects/arm_neon/test_attrs.mlir
  tests/filecheck/parser-printer/graph_region.mlir
  tests/filecheck/parser-printer/parse_error.mlir
  tests/interactive/test_app.py
  tests/test_parser_error.py
  xdsl/utils/lexer.py
Labels: misc

#4773 dialects: (emitc) Add SizeTType
  tests/filecheck/dialects/emitc/emitc_types.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/emitc/emitc_types.mlir
  xdsl/dialects/emitc.py
Labels: dialects

#4776 frontend: (pyast) rename widened function registry from type to constructor
  tests/filecheck/frontend/dialects/arith.py
  tests/filecheck/frontend/dialects/scf.py
  xdsl/frontend/pyast/code_generation.py
  xdsl/frontend/pyast/program.py
  xdsl/frontend/pyast/type_conversion.py
Labels: frontend

#4651 frontend: (pyast) restructure pyast implementation and filecheck tests
  pyproject.toml
  tests/filecheck/frontend/dialects/affine.py
  tests/filecheck/frontend/dialects/arith.py
  tests/filecheck/frontend/dialects/cf.py
  tests/filecheck/frontend/dialects/scf.py
  tests/filecheck/frontend/programs/code_generation_exceptions.py
  tests/filecheck/frontend/programs/example.py
  tests/filecheck/frontend/programs/frontend_program_exceptions.py
  tests/filecheck/frontend/programs/programs.py
  tests/filecheck/frontend/programs/registered_functions.py
  tests/filecheck/transforms/desymref.mlir
  tests/test_frontend_op_inserter.py
  tests/test_frontend_python_code_check.py
  xdsl/dialects/__init__.py
  xdsl/dialects/symref.py
  xdsl/frontend/pyast/README.md
  xdsl/frontend/pyast/code_generation.py
  xdsl/frontend/pyast/context.py
  xdsl/frontend/pyast/program.py
  xdsl/frontend/pyast/utils/__init__.py
  xdsl/frontend/pyast/utils/block.py
  xdsl/frontend/pyast/utils/const.py
  xdsl/frontend/pyast/utils/exceptions.py
  xdsl/frontend/pyast/utils/op_inserter.py
  xdsl/frontend/pyast/utils/python_code_check.py
  xdsl/frontend/pyast/utils/type_conversion.py
  xdsl/transforms/__init__.py
  xdsl/transforms/desymref.py
Labels: frontend

#4783 documentation: (Toy) LowerToAffinePass -> LowerToyPass
  docs/Toy/toy/compiler.py
  docs/Toy/toy/rewrites/lower_toy.py
Labels: documentation

#4759 documentation: (Toy) use FileLineColLoc in Toy
  docs/Toy/toy/frontend/ir_gen.py
  docs/Toy/toy/frontend/location.py
  docs/Toy/toy/frontend/parser.py
  docs/Toy/toy/frontend/toy_ast.py
  tests/test_parser_error.py
  xdsl/utils/lexer.py
Labels: documentation

#4295 Add support for optional groups' `else-elements`
  tests/irdl/test_declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format_parser.py
Labels: core

#4790 transformations: (convert-ptr-to-x86) insert mov to inout reg
  tests/filecheck/backend/x86/convert_ptr_to_x86.mlir
  xdsl/backend/x86/lowering/convert_ptr_to_x86.py
Labels: transformations

#4778 core: (ParametrizedAttribute) Allow bare ClassVar in definition
  tests/irdl/test_attribute_definition.py
  xdsl/irdl/attributes.py
Labels: testing, core

#4792 CI: add specific Pyright ignores to frontend tests
  pyproject.toml
  tests/filecheck/frontend/programs/code_generation_exceptions.py
  tests/filecheck/frontend/programs/frontend_program_exceptions.py
  tests/test_frontend_python_code_check.py
Labels: CI

#4787 misc: use ValueError in core.py
  tests/pattern_rewriter/test_pattern_rewriter.py
  tests/test_ir.py
  xdsl/ir/core.py
Labels: misc

#4794 dialects: (snitch-runtime) remove `ConstraintVar`
  tests/filecheck/dialects/snitch_runtime/snitch_runtime_invalid.mlir
  xdsl/dialects/snitch_runtime.py
Labels: dialects

#4797 testing: use match argument for error testing
  pyproject.toml
  tests/dialects/test_arith.py
  tests/dialects/test_llvm.py
  tests/dialects/test_pdl.py
  tests/irdl/test_operation_builder.py
  tests/test_dialect_interfaces.py
  tests/test_frontend_op_inserter.py
  tests/test_frontend_python_code_check.py
  tests/test_immutable_list.py
  tests/test_interpreter.py
  tests/test_ir.py
  tests/test_op_builder.py
  tests/test_rewriter.py
  tests/test_ssa_value.py
  tests/test_traits.py
Labels: testing

#4798 dialects: (builtin) make `type` positional in IntegerAttr.constr
  tests/filecheck/utils/codegen/simple.py
  tests/xdsl_tblgen/test.py
  xdsl/dialects/arith.py
  xdsl/dialects/builtin.py
  xdsl/tools/xdsl_tblgen.py
Labels: dialects

#4796 core: (Constraints) deprecate `ConstraintVar`
  tests/irdl/test_operation_definition.py
  xdsl/irdl/attributes.py
  xdsl/irdl/operations.py
Labels: core

#4800 core: (ParametrizedAttribute) add `ParamDef` for "resolved" fields
  tests/irdl/test_attribute_definition.py
  xdsl/dialects/irdl/pyrdl_to_irdl.py
  xdsl/interpreters/irdl.py
  xdsl/irdl/attributes.py
  xdsl/utils/dialect_stub.py
Labels: core

#4811 core: (SymbolNameConstraint) add assembly format symbol names
  tests/irdl/test_declarative_assembly_format.py
  xdsl/dialects/builtin.py
  xdsl/irdl/declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format_parser.py
Labels: core

#4814 documentation: move notebook references from nav to readme
  docs/marimo/README.md
  mkdocs.yml
  scripts/gen_ref_pages.py
Labels: documentation

#4813 documentation: automatically generate the navigation for code reference
  docs/api/index.md
  docs/api/ir/attribute.md
  docs/api/ir/block.md
  docs/api/ir/dialect.md
  docs/api/ir/index.md
  docs/api/ir/ir_node.md
  docs/api/ir/operation.md
  docs/api/ir/region.md
  docs/api/ir/ssa_value.md
  docs/index.md
  mkdocs.yml
  pyproject.toml
  scripts/gen_ref_pages.py
  uv.lock
  xdsl/parser/__init__.py
Labels: documentation

#4802 dialects:(omp) add private and reduction declarations
  tests/filecheck/dialects/omp/ops.mlir
  tests/filecheck/dialects/omp/ops_invalid.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/omp/ops.mlir
  xdsl/dialects/omp.py
Labels: dialects

#4821 misc: don't construct a new DenseArrayBase.constr(i32)
  xdsl/irdl/operations.py
Labels: misc

#4815 API: use default values for attr constraints
  tests/irdl/test_attribute_definition.py
  tests/irdl/test_declarative_assembly_format.py
  xdsl/dialects/bufferization.py
  xdsl/dialects/builtin.py
  xdsl/dialects/irdl/pyrdl_to_irdl.py
  xdsl/dialects/memref_stream.py
  xdsl/dialects/pdl_interp.py
  xdsl/dialects/smt.py
  xdsl/dialects/snitch.py
  xdsl/dialects/stencil.py
  xdsl/dialects/utils/reshape_ops_utils.py
  xdsl/irdl/attributes.py
  xdsl/irdl/constraints.py
  xdsl/irdl/operations.py
  xdsl/pattern_rewriter.py
  xdsl/utils/dialect_codegen.py
  xdsl/utils/isattr.py
Labels: API

#4822 dialects:(omp) add omp.distribute op
  tests/filecheck/dialects/omp/ops.mlir
  tests/filecheck/dialects/omp/ops_invalid.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/omp/ops.mlir
  xdsl/dialects/omp.py
Labels: dialects

#4820 core: (AnyOf) allow variable inference and use for arith.constant
  xdsl/dialects/arith.py
  xdsl/irdl/constraints.py
Labels: core

#4826 misc: remove a cast in declarative assembly format parser
  xdsl/irdl/declarative_assembly_format_parser.py
Labels: misc

#4828 core: (Constraints) deprecate TypedAttributeConstraint
  tests/irdl/test_declarative_assembly_format.py
  xdsl/irdl/constraints.py
Labels: core

#4825 dialects:(omp) add omp.teams operation
  tests/filecheck/dialects/omp/ops.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/omp/ops.mlir
  xdsl/dialects/omp.py
Labels: dialects

#4812 frontend: (pyast) add new decorator-based API for frontend code generation
  tests/filecheck/frontend/programs/new_api.py
  xdsl/frontend/builder.py
  xdsl/frontend/pyast/context.py
  xdsl/frontend/pyast/program.py
Labels: frontend

#3650 dialects: (vector) Add for `vector.transfer_read` and `vector.transfer_write` operations
  tests/dialects/test_vector.py
  tests/filecheck/dialects/vector/vector_transfer_read_verify.mlir
  tests/filecheck/dialects/vector/vector_transfer_write_verify.mlir
  xdsl/dialects/vector.py
Labels: dialects

#4836 core: fix RangeOf variables
  tests/irdl/test_range_constraint.py
  xdsl/irdl/constraints.py
Labels: core

#4837 core: add RangeLengthConstraint
  tests/irdl/test_range_constraint.py
  xdsl/irdl/constraints.py
Labels: core

#4838 dialects: (fir) FIR compatibility with Flang 20.7.1
  xdsl/dialects/experimental/fir.py
Labels: dialects

#4835 dialects: (linalg) Add support for copy operation
  tests/filecheck/dialects/linalg/linalg_ops.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/linalg/ops.mlir
  xdsl/dialects/linalg.py
Labels: dialects

#4840 bench: incorporate benchmark proposed in #4834
  benchmarks/parser.py
  benchmarks/workloads.py
Labels: bench

#4849 dialects: (eqsat) add verification for eclass operands
  tests/filecheck/dialects/eqsat/eqsat_invalid.mlir
  tests/filecheck/dialects/eqsat/eqsat_ops.mlir
  xdsl/dialects/eqsat.py
Labels: dialects

#4852 transformations: (eqsat-add-costs) add default cost
  tests/filecheck/transforms/eqsat-add-costs-with-default.mlir
  tests/filecheck/transforms/eqsat-add-costs.mlir
  xdsl/transforms/eqsat_add_costs.py
Labels: transformations

#4871 dialects: (memref) Add missing traits to operations
  tests/filecheck/dce.mlir
  xdsl/dialects/memref.py
Labels: dialects

#4863 dialects: Add DLTI dialect
  tests/filecheck/dialects/dlti/attrs.mlir
  tests/filecheck/dialects/dlti/attrs_invalid.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/dlti/attrs.mlir
  xdsl/dialects/__init__.py
  xdsl/dialects/dlti.py
Labels: dialects

#4872 dialects: (tosa) Add support for `tosa.add`
  tests/dialects/test_tosa.py
  tests/filecheck/dialects/tosa/ops.mlir
  tests/filecheck/dialects/tosa/ops_invalid.mlir
  xdsl/dialects/tosa.py
Labels: dialects

#4889 core: remove unnecessary isinstance in attribute parser
  xdsl/irdl/declarative_assembly_format_parser.py
Labels: core

#4884 misc: (FormatDirective) add getters and setters
  xdsl/irdl/declarative_assembly_format.py
Labels: misc

#4886 misc: (utils) move `is_const_classvar` to utils
  tests/dialects/test_irdl.py
  tests/dialects/test_irdl_with_annotations.py
  xdsl/irdl/attributes.py
  xdsl/irdl/operations.py
  xdsl/utils/classvar.py
Labels: misc

#4878 core: Add parse_identifier_or_str_literal method
  tests/test_parser.py
  xdsl/parser/attribute_parser.py
  xdsl/parser/base_parser.py
Labels: core

#4865 core: Allow non-keyword enums in StrEnum
  tests/irdl/test_attribute_definition.py
  tests/test_parser.py
  xdsl/ir/core.py
  xdsl/parser/base_parser.py
Labels: core

#4867 dialects: Add #llvm.target_features attribute
  tests/filecheck/dialects/llvm/attrs-invalid.mlir
  tests/filecheck/dialects/llvm/attrs.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/llvm/attrs.mlir
  xdsl/dialects/llvm.py
Labels: dialects

#4898 CI: use --allow-unregistered-dialect in LLVM attrs test
  tests/filecheck/mlir-conversion/with-mlir/dialects/llvm/attrs.mlir
Labels: CI

#4900 core: factor out parse_attr in AttributeVariable directive
  xdsl/irdl/declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format_parser.py
Labels: core

#4901 core: add `is_optional` field to AttributeVariable directive
  xdsl/irdl/declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format_parser.py
Labels: core

#4902 core: factor out SymbolNameAttributeVariable
  xdsl/irdl/declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format_parser.py
Labels: core

#4903 core: factor out UniqueBase and UniqueTypeAttributeVariable directives
  xdsl/irdl/declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format_parser.py
Labels: core

#4911 core: add special handling of DenseArrayBase in assembly format
  tests/irdl/test_declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format_parser.py
Labels: core

#4913 core: handle VarConstraint in attr/prop directive
  tests/irdl/test_declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format_parser.py
Labels: core

#4892 dialects: (linalg) Broadcast and transpose op init methods take sequence of result types
  tests/filecheck/mlir-conversion/with-mlir/dialects/linalg/ops.mlir
  xdsl/dialects/linalg.py
Labels: dialects

#4904 dialects: (tosa) implement trig operations
  tests/filecheck/dialects/tosa/ops.mlir
  xdsl/dialects/tosa.py
Labels: dialects

#4906 core: Abstract `uses` field from `IRWithUses`
  tests/test_use.py
  xdsl/ir/core.py
  xdsl/transforms/experimental/dmp/stencil_global_to_local.py
  xdsl/transforms/stencil_bufferize.py
  xdsl/transforms/test_constant_folding.py
Labels: core

#4908 core: Remove __len__ from IRUses
  docs/Toy/toy/rewrites/inline_toy.py
  docs/marimo/xdsl_introduction.py
  tests/dialects/test_llvm.py
  tests/interpreters/test_eqsat_pdl_interp_interpreter.py
  tests/test_ir.py
  xdsl/dialects/accfg.py
  xdsl/dialects/eqsat.py
  xdsl/interpreters/eqsat_pdl_interp.py
  xdsl/interpreters/irdl.py
  xdsl/ir/core.py
  xdsl/pattern_rewriter.py
  xdsl/transforms/canonicalization_patterns/arith.py
  xdsl/transforms/canonicalization_patterns/cf.py
  xdsl/transforms/canonicalization_patterns/csl.py
  xdsl/transforms/canonicalization_patterns/csl_stencil.py
  xdsl/transforms/canonicalization_patterns/memref.py
  xdsl/transforms/canonicalization_patterns/riscv.py
  xdsl/transforms/canonicalization_patterns/stencil.py
  xdsl/transforms/convert_memref_stream_to_snitch_stream.py
  xdsl/transforms/convert_stencil_to_csl_stencil.py
  xdsl/transforms/csl_stencil_bufferize.py
  xdsl/transforms/desymref.py
  xdsl/transforms/eqsat_serialize_egraph.py
  xdsl/transforms/experimental/convert_stencil_to_ll_mlir.py
  xdsl/transforms/linalg_transformations.py
  xdsl/transforms/lower_csl_stencil.py
  xdsl/transforms/riscv_scf_loop_range_folding.py
  xdsl/transforms/scf_for_loop_flatten.py
  xdsl/transforms/scf_for_loop_range_folding.py
  xdsl/transforms/stencil_bufferize.py
  xdsl/transforms/varith_transformations.py
Labels: core

#4916 misc: (ParametrizedAttribute) remove deprecated init
  tests/irdl/test_attribute_definition.py
  xdsl/ir/core.py
Labels: misc

#4920 core: (AssemblyFormat) add missing errors for duplicate keys
  tests/irdl/test_declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format_parser.py
Labels: core

#4856 interpreter: (linalg) handle tensors in linalg.generic interpreter
  tests/interpreters/test_linalg_interpreter.py
  xdsl/interpreters/linalg.py
Labels: interpreter

#4923 misc: (Format parser) use `in_parens`
  xdsl/irdl/declarative_assembly_format_parser.py
Labels: misc

#4909 core: Use linked list for SSAValue uses
  tests/test_use.py
  xdsl/interpreters/eqsat_pdl_interp.py
  xdsl/ir/core.py
  xdsl/transforms/test_constant_folding.py
Labels: core

#4921 core: (Assembly Format) add ref directive
  tests/irdl/test_declarative_assembly_format.py
  xdsl/irdl/declarative_assembly_format_parser.py
Labels: core

#4755 core: (ParametrizedAttribute) add converters
  tests/filecheck/utils/codegen/simple.py
  tests/irdl/test_attribute_definition.py
  xdsl/dialects/builtin.py
  xdsl/ir/core.py
  xdsl/irdl/attributes.py
  xdsl/parser/attribute_parser.py
Labels: core

#4928 misc: (Assembly Format) add more getters/setters
  xdsl/irdl/declarative_assembly_format.py
Labels: misc

#4919 dialects: (linalg) add reduction operation to linalg dialect
  tests/filecheck/dialects/linalg/invalid.mlir
  tests/filecheck/dialects/linalg/linalg_ops.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/linalg/ops.mlir
  xdsl/dialects/linalg.py
Labels: dialects

#4934 dialects: (dlti) add mapattr
  tests/filecheck/dialects/dlti/attrs.mlir
  tests/filecheck/dialects/dlti/attrs_invalid.mlir
  tests/filecheck/mlir-conversion/with-mlir/dialects/dlti/attrs.mlir
  xdsl/dialects/dlti.py
Labels: dialects
